-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2019.1
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity top is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    wt_i_V_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    wt_i_V_ce0 : OUT STD_LOGIC;
    wt_i_V_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    kh_i_V_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    kh_i_V_ce0 : OUT STD_LOGIC;
    kh_i_V_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    dmem_i_V_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    dmem_i_V_ce0 : OUT STD_LOGIC;
    dmem_i_V_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    dmem_o_V_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    dmem_o_V_ce0 : OUT STD_LOGIC;
    dmem_o_V_we0 : OUT STD_LOGIC;
    dmem_o_V_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    n_inputs_V : IN STD_LOGIC_VECTOR (15 downto 0);
    n_outputs_V : IN STD_LOGIC_VECTOR (15 downto 0);
    input_words_V : IN STD_LOGIC_VECTOR (15 downto 0);
    output_words_V : IN STD_LOGIC_VECTOR (15 downto 0);
    layer_mode_V : IN STD_LOGIC_VECTOR (2 downto 0);
    dmem_mode_V : IN STD_LOGIC_VECTOR (0 downto 0);
    width_mode_V : IN STD_LOGIC_VECTOR (1 downto 0);
    norm_mode_V : IN STD_LOGIC_VECTOR (1 downto 0) );
end;


architecture behav of top is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "top,hls_ip_2019_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7k70t-fbv676-1,HLS_INPUT_CLOCK=25.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=19.295250,HLS_SYN_LAT=5048,HLS_SYN_TPT=none,HLS_SYN_MEM=50,HLS_SYN_DSP=1,HLS_SYN_FF=3965,HLS_SYN_LUT=54770,HLS_VERSION=2019_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000010";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (10 downto 0) := "00000000100";
    constant ap_ST_fsm_pp1_stage0 : STD_LOGIC_VECTOR (10 downto 0) := "00000001000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (10 downto 0) := "00000010000";
    constant ap_ST_fsm_pp2_stage0 : STD_LOGIC_VECTOR (10 downto 0) := "00000100000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (10 downto 0) := "00001000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (10 downto 0) := "00010000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (10 downto 0) := "00100000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (10 downto 0) := "01000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (10 downto 0) := "10000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv7_40 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv13_124A : STD_LOGIC_VECTOR (12 downto 0) := "1001001001010";
    constant ap_const_lv13_1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv13_925 : STD_LOGIC_VECTOR (12 downto 0) := "0100100100101";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal kh_index_V : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal o_index_V : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal dmem_V_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal dmem_V_ce0 : STD_LOGIC;
    signal dmem_V_we0 : STD_LOGIC;
    signal dmem_V_d0 : STD_LOGIC_VECTOR (63 downto 0);
    signal dmem_V_q0 : STD_LOGIC_VECTOR (63 downto 0);
    signal dmem_V_ce1 : STD_LOGIC;
    signal dmem_V_q1 : STD_LOGIC_VECTOR (63 downto 0);
    signal wt_mem_V_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal wt_mem_V_ce0 : STD_LOGIC;
    signal wt_mem_V_we0 : STD_LOGIC;
    signal wt_mem_V_q0 : STD_LOGIC_VECTOR (63 downto 0);
    signal wt_mem_V_ce1 : STD_LOGIC;
    signal wt_mem_V_q1 : STD_LOGIC_VECTOR (63 downto 0);
    signal kh_mem_V_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal kh_mem_V_ce0 : STD_LOGIC;
    signal kh_mem_V_we0 : STD_LOGIC;
    signal kh_mem_V_q0 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_0730_0_reg_318 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_0886_0_reg_329 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0214_0_reg_340 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_0474_0_reg_351 : STD_LOGIC_VECTOR (12 downto 0);
    signal p_0582_0_reg_362 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln792_fu_399_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln792_reg_827 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln880_fu_413_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln880_reg_832 : STD_LOGIC_VECTOR (0 downto 0);
    signal t_V_fu_421_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal t_V_reg_837 : STD_LOGIC_VECTOR (0 downto 0);
    signal t_V_1_fu_427_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal t_V_1_reg_843 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_V_2_fu_435_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_2_reg_849 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln812_fu_449_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln812_reg_855 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln879_fu_463_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln879_reg_860 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln879_fu_469_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln879_reg_864 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln879_1_fu_473_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln879_1_reg_869 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln887_fu_479_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_block_state2_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal i_V_2_fu_485_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal ret_V_5_fu_495_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_V_5_reg_882 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_V_3_fu_499_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal ret_V_3_reg_887 : STD_LOGIC_VECTOR (5 downto 0);
    signal ret_V_6_reg_892 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln180_fu_569_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln180_reg_907 : STD_LOGIC_VECTOR (13 downto 0);
    signal select_ln827_fu_597_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln827_1_fu_605_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln887_1_fu_648_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln887_1_reg_927 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp1_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp1_stage0 : signal is "none";
    signal ap_block_state5_pp1_stage0_iter0 : BOOLEAN;
    signal ap_block_state6_pp1_stage0_iter1 : BOOLEAN;
    signal ap_block_pp1_stage0_11001 : BOOLEAN;
    signal i_V_fu_654_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_enable_reg_pp1_iter0 : STD_LOGIC := '0';
    signal add_ln180_1_fu_686_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln180_1_reg_936 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln887_2_fu_701_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln887_2_reg_946 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp2_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp2_stage0 : signal is "none";
    signal ap_block_state8_pp2_stage0_iter0 : BOOLEAN;
    signal ap_block_state9_pp2_stage0_iter1 : BOOLEAN;
    signal ap_block_pp2_stage0_11001 : BOOLEAN;
    signal i_V_1_fu_707_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_enable_reg_pp2_iter0 : STD_LOGIC := '0';
    signal zext_ln544_4_fu_713_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln544_4_reg_955 : STD_LOGIC_VECTOR (63 downto 0);
    signal nc_V_fu_760_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal nc_V_reg_965 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state2 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_block_pp1_stage0_subdone : BOOLEAN;
    signal ap_condition_pp1_exit_iter0_state5 : STD_LOGIC;
    signal ap_enable_reg_pp1_iter1 : STD_LOGIC := '0';
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal ap_block_pp2_stage0_subdone : BOOLEAN;
    signal ap_condition_pp2_exit_iter0_state8 : STD_LOGIC;
    signal ap_enable_reg_pp2_iter1 : STD_LOGIC := '0';
    signal grp_bin_conv_fu_373_ap_start : STD_LOGIC;
    signal grp_bin_conv_fu_373_ap_done : STD_LOGIC;
    signal grp_bin_conv_fu_373_ap_idle : STD_LOGIC;
    signal grp_bin_conv_fu_373_ap_ready : STD_LOGIC;
    signal grp_bin_conv_fu_373_wt_mem_V_2_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_bin_conv_fu_373_wt_mem_V_2_ce0 : STD_LOGIC;
    signal grp_bin_conv_fu_373_wt_mem_V_2_address1 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_bin_conv_fu_373_wt_mem_V_2_ce1 : STD_LOGIC;
    signal grp_bin_conv_fu_373_dmem_V_2_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_bin_conv_fu_373_dmem_V_2_ce0 : STD_LOGIC;
    signal grp_bin_conv_fu_373_dmem_V_2_we0 : STD_LOGIC;
    signal grp_bin_conv_fu_373_dmem_V_2_d0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_bin_conv_fu_373_dmem_V_2_address1 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_bin_conv_fu_373_dmem_V_2_ce1 : STD_LOGIC;
    signal grp_bin_conv_fu_373_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal zext_ln544_3_fu_513_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln544_2_fu_518_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln544_fu_575_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln180_2_fu_626_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln180_1_fu_639_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln180_5_fu_644_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln544_1_fu_692_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp1_stage0 : BOOLEAN;
    signal zext_ln180_6_fu_697_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp2_stage0 : BOOLEAN;
    signal zext_ln180_3_fu_799_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln700_fu_768_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln700_fu_775_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal p_Result_s_fu_403_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln_fu_441_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln812_1_fu_453_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal layer_type_V_fu_389_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal words_per_image_V_fu_457_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ret_V_9_fu_523_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal ret_V_8_fu_533_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_V_fu_537_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln180_fu_542_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal zext_ln180_fu_546_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal ret_V_7_fu_491_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_fu_556_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln180_2_fu_550_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal zext_ln180_4_fu_565_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal img_off_V_fu_580_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln879_2_fu_586_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal img_idx_V_fu_591_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ret_V_4_fu_613_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_5_fu_616_p5 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_4_fu_631_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_7_fu_664_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal ret_V_fu_660_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln180_fu_678_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln1372_fu_674_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal xor_ln879_fu_718_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln879_fu_723_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_V_fu_728_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_V_2_fu_742_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_V_1_fu_732_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln879_fu_752_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_6_fu_792_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_idle_pp1 : STD_LOGIC;
    signal ap_enable_pp1 : STD_LOGIC;
    signal ap_idle_pp2 : STD_LOGIC;
    signal ap_enable_pp2 : STD_LOGIC;
    signal ap_condition_745 : BOOLEAN;

    component bin_conv IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        wt_mem_V_2_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
        wt_mem_V_2_ce0 : OUT STD_LOGIC;
        wt_mem_V_2_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
        wt_mem_V_2_address1 : OUT STD_LOGIC_VECTOR (12 downto 0);
        wt_mem_V_2_ce1 : OUT STD_LOGIC;
        wt_mem_V_2_q1 : IN STD_LOGIC_VECTOR (63 downto 0);
        nc_V : IN STD_LOGIC_VECTOR (15 downto 0);
        dmem_V_2_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
        dmem_V_2_ce0 : OUT STD_LOGIC;
        dmem_V_2_we0 : OUT STD_LOGIC;
        dmem_V_2_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
        dmem_V_2_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
        dmem_V_2_address1 : OUT STD_LOGIC_VECTOR (11 downto 0);
        dmem_V_2_ce1 : OUT STD_LOGIC;
        dmem_V_2_q1 : IN STD_LOGIC_VECTOR (63 downto 0);
        d_i_idx_V : IN STD_LOGIC_VECTOR (0 downto 0);
        d_o_idx_V : IN STD_LOGIC_VECTOR (0 downto 0);
        o_index_V_2 : IN STD_LOGIC_VECTOR (15 downto 0);
        width_mode_V : IN STD_LOGIC_VECTOR (1 downto 0);
        norm_mode_V : IN STD_LOGIC_VECTOR (1 downto 0) );
    end component;


    component top_dmem_V IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (11 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (63 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (63 downto 0);
        address1 : IN STD_LOGIC_VECTOR (11 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component top_wt_mem_V IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (12 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (63 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (63 downto 0);
        address1 : IN STD_LOGIC_VECTOR (12 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component top_kh_mem_V IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (63 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;



begin
    dmem_V_U : component top_dmem_V
    generic map (
        DataWidth => 64,
        AddressRange => 4096,
        AddressWidth => 12)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => dmem_V_address0,
        ce0 => dmem_V_ce0,
        we0 => dmem_V_we0,
        d0 => dmem_V_d0,
        q0 => dmem_V_q0,
        address1 => grp_bin_conv_fu_373_dmem_V_2_address1,
        ce1 => dmem_V_ce1,
        q1 => dmem_V_q1);

    wt_mem_V_U : component top_wt_mem_V
    generic map (
        DataWidth => 64,
        AddressRange => 4682,
        AddressWidth => 13)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => wt_mem_V_address0,
        ce0 => wt_mem_V_ce0,
        we0 => wt_mem_V_we0,
        d0 => wt_i_V_q0,
        q0 => wt_mem_V_q0,
        address1 => grp_bin_conv_fu_373_wt_mem_V_2_address1,
        ce1 => wt_mem_V_ce1,
        q1 => wt_mem_V_q1);

    kh_mem_V_U : component top_kh_mem_V
    generic map (
        DataWidth => 64,
        AddressRange => 64,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => kh_mem_V_address0,
        ce0 => kh_mem_V_ce0,
        we0 => kh_mem_V_we0,
        d0 => kh_i_V_q0,
        q0 => kh_mem_V_q0);

    grp_bin_conv_fu_373 : component bin_conv
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_bin_conv_fu_373_ap_start,
        ap_done => grp_bin_conv_fu_373_ap_done,
        ap_idle => grp_bin_conv_fu_373_ap_idle,
        ap_ready => grp_bin_conv_fu_373_ap_ready,
        wt_mem_V_2_address0 => grp_bin_conv_fu_373_wt_mem_V_2_address0,
        wt_mem_V_2_ce0 => grp_bin_conv_fu_373_wt_mem_V_2_ce0,
        wt_mem_V_2_q0 => wt_mem_V_q0,
        wt_mem_V_2_address1 => grp_bin_conv_fu_373_wt_mem_V_2_address1,
        wt_mem_V_2_ce1 => grp_bin_conv_fu_373_wt_mem_V_2_ce1,
        wt_mem_V_2_q1 => wt_mem_V_q1,
        nc_V => nc_V_reg_965,
        dmem_V_2_address0 => grp_bin_conv_fu_373_dmem_V_2_address0,
        dmem_V_2_ce0 => grp_bin_conv_fu_373_dmem_V_2_ce0,
        dmem_V_2_we0 => grp_bin_conv_fu_373_dmem_V_2_we0,
        dmem_V_2_d0 => grp_bin_conv_fu_373_dmem_V_2_d0,
        dmem_V_2_q0 => dmem_V_q0,
        dmem_V_2_address1 => grp_bin_conv_fu_373_dmem_V_2_address1,
        dmem_V_2_ce1 => grp_bin_conv_fu_373_dmem_V_2_ce1,
        dmem_V_2_q1 => dmem_V_q1,
        d_i_idx_V => dmem_mode_V,
        d_o_idx_V => r_V_2_reg_849,
        o_index_V_2 => t_V_1_reg_843,
        width_mode_V => width_mode_V,
        norm_mode_V => norm_mode_V);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2))) then 
                    ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state2);
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp1_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp1_exit_iter0_state5) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
                    ap_enable_reg_pp1_iter0 <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    ap_enable_reg_pp1_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp1_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp1_exit_iter0_state5))) then 
                    ap_enable_reg_pp1_iter1 <= (ap_const_logic_1 xor ap_condition_pp1_exit_iter0_state5);
                elsif ((ap_const_boolean_0 = ap_block_pp1_stage0_subdone)) then 
                    ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    ap_enable_reg_pp1_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp2_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp2_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp2_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp2_exit_iter0_state8) and (ap_const_logic_1 = ap_CS_fsm_pp2_stage0))) then 
                    ap_enable_reg_pp2_iter0 <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                    ap_enable_reg_pp2_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp2_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp2_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp2_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp2_exit_iter0_state8))) then 
                    ap_enable_reg_pp2_iter1 <= (ap_const_logic_1 xor ap_condition_pp2_exit_iter0_state8);
                elsif ((ap_const_boolean_0 = ap_block_pp2_stage0_subdone)) then 
                    ap_enable_reg_pp2_iter1 <= ap_enable_reg_pp2_iter0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                    ap_enable_reg_pp2_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_bin_conv_fu_373_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_bin_conv_fu_373_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
                    grp_bin_conv_fu_373_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_bin_conv_fu_373_ap_ready = ap_const_logic_1)) then 
                    grp_bin_conv_fu_373_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    p_0214_0_reg_340_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln887_fu_479_p2 = ap_const_lv1_0))) then 
                p_0214_0_reg_340 <= i_V_2_fu_485_p2;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                p_0214_0_reg_340 <= ap_const_lv7_0;
            end if; 
        end if;
    end process;

    p_0474_0_reg_351_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                p_0474_0_reg_351 <= ap_const_lv13_0;
            elsif (((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (icmp_ln887_1_fu_648_p2 = ap_const_lv1_0))) then 
                p_0474_0_reg_351 <= i_V_fu_654_p2;
            end if; 
        end if;
    end process;

    p_0582_0_reg_362_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                p_0582_0_reg_362 <= ap_const_lv7_0;
            elsif (((ap_const_boolean_0 = ap_block_pp2_stage0_11001) and (ap_enable_reg_pp2_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp2_stage0) and (icmp_ln887_2_fu_701_p2 = ap_const_lv1_0))) then 
                p_0582_0_reg_362 <= i_V_1_fu_707_p2;
            end if; 
        end if;
    end process;

    p_0730_0_reg_318_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln887_fu_479_p2 = ap_const_lv1_0))) then 
                p_0730_0_reg_318 <= select_ln827_fu_597_p3;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                p_0730_0_reg_318 <= ap_const_lv16_0;
            end if; 
        end if;
    end process;

    p_0886_0_reg_329_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln887_fu_479_p2 = ap_const_lv1_0))) then 
                p_0886_0_reg_329 <= select_ln827_1_fu_605_p3;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                p_0886_0_reg_329 <= ap_const_lv10_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (icmp_ln887_1_fu_648_p2 = ap_const_lv1_0))) then
                add_ln180_1_reg_936 <= add_ln180_1_fu_686_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln887_fu_479_p2 = ap_const_lv1_0) and (icmp_ln879_reg_860 = ap_const_lv1_1))) then
                add_ln180_reg_907 <= add_ln180_fu_569_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                icmp_ln879_1_reg_869 <= icmp_ln879_1_fu_473_p2;
                icmp_ln879_reg_860 <= icmp_ln879_fu_463_p2;
                r_V_2_reg_849 <= r_V_2_fu_435_p2;
                t_V_1_reg_843 <= t_V_1_fu_427_p3;
                t_V_reg_837 <= t_V_fu_421_p2;
                trunc_ln792_reg_827 <= trunc_ln792_fu_399_p1;
                trunc_ln880_reg_832 <= trunc_ln880_fu_413_p1;
                    zext_ln812_reg_855(2 downto 1) <= zext_ln812_fu_449_p1(2 downto 1);
                    zext_ln879_reg_864(4 downto 0) <= zext_ln879_fu_469_p1(4 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then
                icmp_ln887_1_reg_927 <= icmp_ln887_1_fu_648_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp2_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp2_stage0))) then
                icmp_ln887_2_reg_946 <= icmp_ln887_2_fu_701_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state11)) then
                kh_index_V <= select_ln700_fu_768_p3;
                nc_V_reg_965 <= nc_V_fu_760_p3;
                o_index_V <= add_ln700_fu_775_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln887_fu_479_p2 = ap_const_lv1_0))) then
                ret_V_3_reg_887 <= ret_V_3_fu_499_p1;
                ret_V_5_reg_882 <= ret_V_5_fu_495_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln887_fu_479_p2 = ap_const_lv1_0) and (icmp_ln879_1_reg_869 = ap_const_lv1_0) and (icmp_ln879_reg_860 = ap_const_lv1_0))) then
                ret_V_6_reg_892 <= p_0214_0_reg_340(6 downto 1);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp2_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp2_stage0) and (icmp_ln887_2_fu_701_p2 = ap_const_lv1_0))) then
                    zext_ln544_4_reg_955(6 downto 0) <= zext_ln544_4_fu_713_p1(6 downto 0);
            end if;
        end if;
    end process;
    zext_ln812_reg_855(0) <= '0';
    zext_ln812_reg_855(15 downto 3) <= "0000000000000";
    zext_ln879_reg_864(9 downto 5) <= "00000";
    zext_ln544_4_reg_955(63 downto 7) <= "000000000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, icmp_ln887_fu_479_p2, ap_enable_reg_pp0_iter0, icmp_ln887_1_fu_648_p2, ap_enable_reg_pp1_iter0, icmp_ln887_2_fu_701_p2, ap_enable_reg_pp2_iter0, ap_block_pp0_stage0_subdone, ap_block_pp1_stage0_subdone, ap_block_pp2_stage0_subdone, grp_bin_conv_fu_373_ap_done, ap_CS_fsm_state12)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if (not(((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln887_fu_479_p2 = ap_const_lv1_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln887_fu_479_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_pp1_stage0;
            when ap_ST_fsm_pp1_stage0 => 
                if (not(((ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (icmp_ln887_1_fu_648_p2 = ap_const_lv1_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_pp1_stage0;
                elsif (((ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (icmp_ln887_1_fu_648_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp1_stage0;
                end if;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_pp2_stage0;
            when ap_ST_fsm_pp2_stage0 => 
                if (not(((ap_const_boolean_0 = ap_block_pp2_stage0_subdone) and (ap_enable_reg_pp2_iter0 = ap_const_logic_1) and (icmp_ln887_2_fu_701_p2 = ap_const_lv1_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_pp2_stage0;
                elsif (((ap_const_boolean_0 = ap_block_pp2_stage0_subdone) and (ap_enable_reg_pp2_iter0 = ap_const_logic_1) and (icmp_ln887_2_fu_701_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state10;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp2_stage0;
                end if;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                if (((grp_bin_conv_fu_373_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state12))) then
                    ap_NS_fsm <= ap_ST_fsm_state13;
                else
                    ap_NS_fsm <= ap_ST_fsm_state12;
                end if;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXX";
        end case;
    end process;
    add_ln180_1_fu_686_p2 <= std_logic_vector(unsigned(select_ln180_fu_678_p3) + unsigned(zext_ln1372_fu_674_p1));
    add_ln180_2_fu_550_p2 <= std_logic_vector(unsigned(trunc_ln180_fu_542_p1) + unsigned(zext_ln180_fu_546_p1));
    add_ln180_fu_569_p2 <= std_logic_vector(unsigned(add_ln180_2_fu_550_p2) + unsigned(zext_ln180_4_fu_565_p1));
    add_ln700_fu_775_p2 <= std_logic_vector(unsigned(ap_const_lv16_1) + unsigned(t_V_1_reg_843));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(1);
    ap_CS_fsm_pp1_stage0 <= ap_CS_fsm(3);
    ap_CS_fsm_pp2_stage0 <= ap_CS_fsm(5);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(6);
    ap_CS_fsm_state11 <= ap_CS_fsm(7);
    ap_CS_fsm_state12 <= ap_CS_fsm(8);
    ap_CS_fsm_state13 <= ap_CS_fsm(9);
    ap_CS_fsm_state14 <= ap_CS_fsm(10);
    ap_CS_fsm_state4 <= ap_CS_fsm(2);
    ap_CS_fsm_state7 <= ap_CS_fsm(4);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp1_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp1_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp1_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp2_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp2_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp2_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp1_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp1_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp2_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp2_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_745_assign_proc : process(icmp_ln887_fu_479_p2, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0)
    begin
                ap_condition_745 <= ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln887_fu_479_p2 = ap_const_lv1_0));
    end process;


    ap_condition_pp0_exit_iter0_state2_assign_proc : process(icmp_ln887_fu_479_p2)
    begin
        if ((icmp_ln887_fu_479_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_pp1_exit_iter0_state5_assign_proc : process(icmp_ln887_1_fu_648_p2)
    begin
        if ((icmp_ln887_1_fu_648_p2 = ap_const_lv1_1)) then 
            ap_condition_pp1_exit_iter0_state5 <= ap_const_logic_1;
        else 
            ap_condition_pp1_exit_iter0_state5 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_pp2_exit_iter0_state8_assign_proc : process(icmp_ln887_2_fu_701_p2)
    begin
        if ((icmp_ln887_2_fu_701_p2 = ap_const_lv1_1)) then 
            ap_condition_pp2_exit_iter0_state8 <= ap_const_logic_1;
        else 
            ap_condition_pp2_exit_iter0_state8 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state14)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_pp1 <= (ap_idle_pp1 xor ap_const_logic_1);
    ap_enable_pp2 <= (ap_idle_pp2 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp1_assign_proc : process(ap_enable_reg_pp1_iter0, ap_enable_reg_pp1_iter1)
    begin
        if (((ap_enable_reg_pp1_iter1 = ap_const_logic_0) and (ap_enable_reg_pp1_iter0 = ap_const_logic_0))) then 
            ap_idle_pp1 <= ap_const_logic_1;
        else 
            ap_idle_pp1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp2_assign_proc : process(ap_enable_reg_pp2_iter0, ap_enable_reg_pp2_iter1)
    begin
        if (((ap_enable_reg_pp2_iter1 = ap_const_logic_0) and (ap_enable_reg_pp2_iter0 = ap_const_logic_0))) then 
            ap_idle_pp2 <= ap_const_logic_1;
        else 
            ap_idle_pp2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state14)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    dmem_V_address0_assign_proc : process(icmp_ln879_reg_860, icmp_ln879_1_reg_869, ap_CS_fsm_pp0_stage0, ap_CS_fsm_state13, ap_enable_reg_pp0_iter1, grp_bin_conv_fu_373_dmem_V_2_address0, ap_CS_fsm_state12, ap_block_pp0_stage0, zext_ln180_2_fu_626_p1, zext_ln180_1_fu_639_p1, zext_ln180_5_fu_644_p1, zext_ln180_3_fu_799_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            dmem_V_address0 <= zext_ln180_3_fu_799_p1(12 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln879_reg_860 = ap_const_lv1_1))) then 
            dmem_V_address0 <= zext_ln180_5_fu_644_p1(12 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln879_1_reg_869 = ap_const_lv1_1) and (icmp_ln879_reg_860 = ap_const_lv1_0))) then 
            dmem_V_address0 <= zext_ln180_1_fu_639_p1(12 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln879_1_reg_869 = ap_const_lv1_0) and (icmp_ln879_reg_860 = ap_const_lv1_0))) then 
            dmem_V_address0 <= zext_ln180_2_fu_626_p1(12 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            dmem_V_address0 <= grp_bin_conv_fu_373_dmem_V_2_address0;
        else 
            dmem_V_address0 <= "XXXXXXXXXXXX";
        end if; 
    end process;


    dmem_V_ce0_assign_proc : process(icmp_ln879_reg_860, icmp_ln879_1_reg_869, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_CS_fsm_state13, ap_enable_reg_pp0_iter1, grp_bin_conv_fu_373_dmem_V_2_ce0, ap_CS_fsm_state12)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln879_reg_860 = ap_const_lv1_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln879_1_reg_869 = ap_const_lv1_1) and (icmp_ln879_reg_860 = ap_const_lv1_0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln879_1_reg_869 = ap_const_lv1_0) and (icmp_ln879_reg_860 = ap_const_lv1_0)))) then 
            dmem_V_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            dmem_V_ce0 <= grp_bin_conv_fu_373_dmem_V_2_ce0;
        else 
            dmem_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    dmem_V_ce1_assign_proc : process(grp_bin_conv_fu_373_dmem_V_2_ce1, ap_CS_fsm_state12)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            dmem_V_ce1 <= grp_bin_conv_fu_373_dmem_V_2_ce1;
        else 
            dmem_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    dmem_V_d0_assign_proc : process(dmem_i_V_q0, icmp_ln879_reg_860, icmp_ln879_1_reg_869, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, grp_bin_conv_fu_373_dmem_V_2_d0, ap_CS_fsm_state12, ap_block_pp0_stage0)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln879_reg_860 = ap_const_lv1_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln879_1_reg_869 = ap_const_lv1_1) and (icmp_ln879_reg_860 = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln879_1_reg_869 = ap_const_lv1_0) and (icmp_ln879_reg_860 = ap_const_lv1_0)))) then 
            dmem_V_d0 <= dmem_i_V_q0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            dmem_V_d0 <= grp_bin_conv_fu_373_dmem_V_2_d0;
        else 
            dmem_V_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    dmem_V_we0_assign_proc : process(icmp_ln879_reg_860, icmp_ln879_1_reg_869, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter1, grp_bin_conv_fu_373_dmem_V_2_we0, ap_CS_fsm_state12)
    begin
        if ((((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln879_reg_860 = ap_const_lv1_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln879_1_reg_869 = ap_const_lv1_1) and (icmp_ln879_reg_860 = ap_const_lv1_0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln879_1_reg_869 = ap_const_lv1_0) and (icmp_ln879_reg_860 = ap_const_lv1_0)))) then 
            dmem_V_we0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            dmem_V_we0 <= grp_bin_conv_fu_373_dmem_V_2_we0;
        else 
            dmem_V_we0 <= ap_const_logic_0;
        end if; 
    end process;


    dmem_i_V_address0_assign_proc : process(icmp_ln879_reg_860, icmp_ln879_1_reg_869, zext_ln544_3_fu_513_p1, zext_ln544_2_fu_518_p1, zext_ln544_fu_575_p1, ap_condition_745)
    begin
        if ((ap_const_boolean_1 = ap_condition_745)) then
            if ((icmp_ln879_reg_860 = ap_const_lv1_1)) then 
                dmem_i_V_address0 <= zext_ln544_fu_575_p1(11 - 1 downto 0);
            elsif (((icmp_ln879_1_reg_869 = ap_const_lv1_1) and (icmp_ln879_reg_860 = ap_const_lv1_0))) then 
                dmem_i_V_address0 <= zext_ln544_2_fu_518_p1(11 - 1 downto 0);
            elsif (((icmp_ln879_1_reg_869 = ap_const_lv1_0) and (icmp_ln879_reg_860 = ap_const_lv1_0))) then 
                dmem_i_V_address0 <= zext_ln544_3_fu_513_p1(11 - 1 downto 0);
            else 
                dmem_i_V_address0 <= "XXXXXXXXXXX";
            end if;
        else 
            dmem_i_V_address0 <= "XXXXXXXXXXX";
        end if; 
    end process;


    dmem_i_V_ce0_assign_proc : process(icmp_ln879_reg_860, icmp_ln879_1_reg_869, icmp_ln887_fu_479_p2, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter0)
    begin
        if ((((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln887_fu_479_p2 = ap_const_lv1_0) and (icmp_ln879_reg_860 = ap_const_lv1_1)) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln887_fu_479_p2 = ap_const_lv1_0) and (icmp_ln879_1_reg_869 = ap_const_lv1_1) and (icmp_ln879_reg_860 = ap_const_lv1_0)) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln887_fu_479_p2 = ap_const_lv1_0) and (icmp_ln879_1_reg_869 = ap_const_lv1_0) and (icmp_ln879_reg_860 = ap_const_lv1_0)))) then 
            dmem_i_V_ce0 <= ap_const_logic_1;
        else 
            dmem_i_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    dmem_o_V_address0 <= ap_const_lv64_0(7 - 1 downto 0);

    dmem_o_V_ce0_assign_proc : process(ap_CS_fsm_state14)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            dmem_o_V_ce0 <= ap_const_logic_1;
        else 
            dmem_o_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    dmem_o_V_d0 <= dmem_V_q0;

    dmem_o_V_we0_assign_proc : process(ap_CS_fsm_state14)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            dmem_o_V_we0 <= ap_const_logic_1;
        else 
            dmem_o_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    grp_bin_conv_fu_373_ap_start <= grp_bin_conv_fu_373_ap_start_reg;
    i_V_1_fu_707_p2 <= std_logic_vector(unsigned(p_0582_0_reg_362) + unsigned(ap_const_lv7_1));
    i_V_2_fu_485_p2 <= std_logic_vector(unsigned(p_0214_0_reg_340) + unsigned(ap_const_lv7_1));
    i_V_fu_654_p2 <= std_logic_vector(unsigned(p_0474_0_reg_351) + unsigned(ap_const_lv13_1));
    icmp_ln879_1_fu_473_p2 <= "1" when (layer_type_V_fu_389_p4 = ap_const_lv2_0) else "0";
    icmp_ln879_2_fu_586_p2 <= "1" when (img_off_V_fu_580_p2 = zext_ln879_reg_864) else "0";
    icmp_ln879_fu_463_p2 <= "1" when (layer_type_V_fu_389_p4 = ap_const_lv2_1) else "0";
    icmp_ln887_1_fu_648_p2 <= "1" when (p_0474_0_reg_351 = ap_const_lv13_124A) else "0";
    icmp_ln887_2_fu_701_p2 <= "1" when (p_0582_0_reg_362 = ap_const_lv7_40) else "0";
    icmp_ln887_fu_479_p2 <= "1" when (p_0214_0_reg_340 = ap_const_lv7_40) else "0";
    img_idx_V_fu_591_p2 <= std_logic_vector(unsigned(p_0730_0_reg_318) + unsigned(ap_const_lv16_1));
    img_off_V_fu_580_p2 <= std_logic_vector(unsigned(p_0886_0_reg_329) + unsigned(ap_const_lv10_1));
    kh_i_V_address0 <= zext_ln544_4_fu_713_p1(6 - 1 downto 0);

    kh_i_V_ce0_assign_proc : process(ap_CS_fsm_pp2_stage0, ap_block_pp2_stage0_11001, ap_enable_reg_pp2_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp2_stage0_11001) and (ap_enable_reg_pp2_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp2_stage0))) then 
            kh_i_V_ce0 <= ap_const_logic_1;
        else 
            kh_i_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    kh_mem_V_address0_assign_proc : process(ap_CS_fsm_pp2_stage0, zext_ln544_4_reg_955, ap_enable_reg_pp2_iter1, ap_block_pp2_stage0, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            kh_mem_V_address0 <= ap_const_lv6_0;
        elsif (((ap_const_boolean_0 = ap_block_pp2_stage0) and (ap_enable_reg_pp2_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp2_stage0))) then 
            kh_mem_V_address0 <= zext_ln544_4_reg_955(6 - 1 downto 0);
        else 
            kh_mem_V_address0 <= "XXXXXX";
        end if; 
    end process;


    kh_mem_V_ce0_assign_proc : process(ap_CS_fsm_pp2_stage0, ap_block_pp2_stage0_11001, ap_enable_reg_pp2_iter1, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or ((ap_const_boolean_0 = ap_block_pp2_stage0_11001) and (ap_enable_reg_pp2_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp2_stage0)))) then 
            kh_mem_V_ce0 <= ap_const_logic_1;
        else 
            kh_mem_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    kh_mem_V_we0_assign_proc : process(icmp_ln887_2_reg_946, ap_CS_fsm_pp2_stage0, ap_block_pp2_stage0_11001, ap_enable_reg_pp2_iter1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp2_stage0_11001) and (ap_enable_reg_pp2_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp2_stage0) and (icmp_ln887_2_reg_946 = ap_const_lv1_0))) then 
            kh_mem_V_we0 <= ap_const_logic_1;
        else 
            kh_mem_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    layer_type_V_fu_389_p4 <= layer_mode_V(2 downto 1);
    nc_V_fu_760_p3 <= 
        tmp_V_1_fu_732_p4 when (t_V_reg_837(0) = '1') else 
        select_ln879_fu_752_p3;
    or_ln879_fu_723_p2 <= (xor_ln879_fu_718_p2 or trunc_ln792_reg_827);
    p_Result_s_fu_403_p2 <= (trunc_ln792_fu_399_p1 xor ap_const_lv1_1);
    r_V_2_fu_435_p2 <= (dmem_mode_V xor ap_const_lv1_1);
    r_V_fu_537_p2 <= std_logic_vector(shift_left(unsigned(ret_V_8_fu_533_p1),to_integer(unsigned('0' & zext_ln812_reg_855(16-1 downto 0)))));
    ret_V_3_fu_499_p1 <= p_0214_0_reg_340(6 - 1 downto 0);
    ret_V_4_fu_613_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ret_V_6_reg_892),7));
    ret_V_5_fu_495_p1 <= p_0214_0_reg_340(1 - 1 downto 0);
    ret_V_7_fu_491_p1 <= p_0730_0_reg_318(1 - 1 downto 0);
    ret_V_8_fu_533_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ret_V_9_fu_523_p4),16));
    ret_V_9_fu_523_p4 <= p_0730_0_reg_318(15 downto 1);
    ret_V_fu_660_p1 <= p_0474_0_reg_351(1 - 1 downto 0);
    select_ln180_fu_678_p3 <= 
        ap_const_lv13_925 when (ret_V_fu_660_p1(0) = '1') else 
        ap_const_lv13_0;
    select_ln700_fu_768_p3 <= 
        ap_const_lv2_2 when (t_V_reg_837(0) = '1') else 
        ap_const_lv2_1;
    select_ln827_1_fu_605_p3 <= 
        ap_const_lv10_0 when (icmp_ln879_2_fu_586_p2(0) = '1') else 
        img_off_V_fu_580_p2;
    select_ln827_fu_597_p3 <= 
        img_idx_V_fu_591_p2 when (icmp_ln879_2_fu_586_p2(0) = '1') else 
        p_0730_0_reg_318;
    select_ln879_fu_752_p3 <= 
        tmp_V_fu_728_p1 when (or_ln879_fu_723_p2(0) = '1') else 
        tmp_V_2_fu_742_p4;
    shl_ln_fu_441_p3 <= (width_mode_V & ap_const_lv1_0);
    t_V_1_fu_427_p3 <= 
        ap_const_lv16_0 when (trunc_ln792_fu_399_p1(0) = '1') else 
        o_index_V;
    t_V_fu_421_p2 <= (trunc_ln880_fu_413_p1 and p_Result_s_fu_403_p2);
    tmp_3_fu_556_p4 <= ((dmem_mode_V & ret_V_7_fu_491_p1) & ap_const_lv10_0);
    tmp_4_fu_631_p4 <= ((dmem_mode_V & ap_const_lv5_0) & ret_V_3_reg_887);
    tmp_5_fu_616_p5 <= (((dmem_mode_V & ret_V_5_reg_882) & ap_const_lv3_0) & ret_V_4_fu_613_p1);
    tmp_6_fu_792_p3 <= (r_V_2_reg_849 & ap_const_lv11_0);
    tmp_7_fu_664_p4 <= p_0474_0_reg_351(12 downto 1);
    tmp_V_1_fu_732_p4 <= kh_mem_V_q0(31 downto 16);
    tmp_V_2_fu_742_p4 <= kh_mem_V_q0(63 downto 48);
    tmp_V_fu_728_p1 <= kh_mem_V_q0(16 - 1 downto 0);
    trunc_ln180_fu_542_p1 <= r_V_fu_537_p2(14 - 1 downto 0);
    trunc_ln792_fu_399_p1 <= layer_mode_V(1 - 1 downto 0);
    trunc_ln880_fu_413_p1 <= kh_index_V(1 - 1 downto 0);
    words_per_image_V_fu_457_p2 <= std_logic_vector(shift_left(unsigned(ap_const_lv5_1),to_integer(unsigned('0' & zext_ln812_1_fu_453_p1(5-1 downto 0)))));
    wt_i_V_address0 <= zext_ln544_1_fu_692_p1(13 - 1 downto 0);

    wt_i_V_ce0_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_block_pp1_stage0_11001, ap_enable_reg_pp1_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
            wt_i_V_ce0 <= ap_const_logic_1;
        else 
            wt_i_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    wt_mem_V_address0_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, grp_bin_conv_fu_373_wt_mem_V_2_address0, ap_CS_fsm_state12, ap_block_pp1_stage0, zext_ln180_6_fu_697_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
            wt_mem_V_address0 <= zext_ln180_6_fu_697_p1(13 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            wt_mem_V_address0 <= grp_bin_conv_fu_373_wt_mem_V_2_address0;
        else 
            wt_mem_V_address0 <= "XXXXXXXXXXXXX";
        end if; 
    end process;


    wt_mem_V_ce0_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_block_pp1_stage0_11001, ap_enable_reg_pp1_iter1, grp_bin_conv_fu_373_wt_mem_V_2_ce0, ap_CS_fsm_state12)
    begin
        if (((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
            wt_mem_V_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            wt_mem_V_ce0 <= grp_bin_conv_fu_373_wt_mem_V_2_ce0;
        else 
            wt_mem_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    wt_mem_V_ce1_assign_proc : process(grp_bin_conv_fu_373_wt_mem_V_2_ce1, ap_CS_fsm_state12)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            wt_mem_V_ce1 <= grp_bin_conv_fu_373_wt_mem_V_2_ce1;
        else 
            wt_mem_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    wt_mem_V_we0_assign_proc : process(icmp_ln887_1_reg_927, ap_CS_fsm_pp1_stage0, ap_block_pp1_stage0_11001, ap_enable_reg_pp1_iter1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (icmp_ln887_1_reg_927 = ap_const_lv1_0))) then 
            wt_mem_V_we0 <= ap_const_logic_1;
        else 
            wt_mem_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    xor_ln879_fu_718_p2 <= (trunc_ln880_reg_832 xor ap_const_lv1_1);
    zext_ln1372_fu_674_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_7_fu_664_p4),13));
    zext_ln180_1_fu_639_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_4_fu_631_p4),64));
    zext_ln180_2_fu_626_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_5_fu_616_p5),64));
    zext_ln180_3_fu_799_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_6_fu_792_p3),64));
    zext_ln180_4_fu_565_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_3_fu_556_p4),14));
    zext_ln180_5_fu_644_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln180_reg_907),64));
    zext_ln180_6_fu_697_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln180_1_reg_936),64));
    zext_ln180_fu_546_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_0886_0_reg_329),14));
    zext_ln544_1_fu_692_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_0474_0_reg_351),64));
    zext_ln544_2_fu_518_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_0214_0_reg_340),64));
    zext_ln544_3_fu_513_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_0214_0_reg_340),64));
    zext_ln544_4_fu_713_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_0582_0_reg_362),64));
    zext_ln544_fu_575_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_0214_0_reg_340),64));
    zext_ln812_1_fu_453_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_441_p3),5));
    zext_ln812_fu_449_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_441_p3),16));
    zext_ln879_fu_469_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(words_per_image_V_fu_457_p2),10));
end behav;
