// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "conv3x3b.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic conv3x3b::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic conv3x3b::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<5> conv3x3b::ap_ST_fsm_pp0_stage0 = "1";
const sc_lv<5> conv3x3b::ap_ST_fsm_pp0_stage1 = "10";
const sc_lv<5> conv3x3b::ap_ST_fsm_pp0_stage2 = "100";
const sc_lv<5> conv3x3b::ap_ST_fsm_pp0_stage3 = "1000";
const sc_lv<5> conv3x3b::ap_ST_fsm_pp0_stage4 = "10000";
const bool conv3x3b::ap_const_boolean_1 = true;
const sc_lv<32> conv3x3b::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool conv3x3b::ap_const_boolean_0 = false;
const sc_lv<32> conv3x3b::ap_const_lv32_4 = "100";
const sc_lv<32> conv3x3b::ap_const_lv32_1 = "1";
const sc_lv<32> conv3x3b::ap_const_lv32_2 = "10";
const sc_lv<32> conv3x3b::ap_const_lv32_3 = "11";
const sc_lv<3> conv3x3b::ap_const_lv3_0 = "000";
const sc_lv<5> conv3x3b::ap_const_lv5_0 = "00000";
const sc_lv<1> conv3x3b::ap_const_lv1_0 = "0";
const sc_lv<4> conv3x3b::ap_const_lv4_1 = "1";
const sc_lv<10> conv3x3b::ap_const_lv10_A = "1010";
const sc_lv<4> conv3x3b::ap_const_lv4_2 = "10";
const sc_lv<10> conv3x3b::ap_const_lv10_14 = "10100";

conv3x3b::conv3x3b(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln1353_14_fu_488_p2);
    sensitive << ( cc_V_read_reg_937 );

    SC_METHOD(thread_add_ln1353_fu_360_p2);
    sensitive << ( cc_V );

    SC_METHOD(thread_add_ln700_3_fu_644_p2);
    sensitive << ( sext_ln74_fu_592_p1 );
    sensitive << ( sext_ln74_1_fu_637_p1 );

    SC_METHOD(thread_add_ln700_4_fu_654_p2);
    sensitive << ( sext_ln700_2_fu_650_p1 );
    sensitive << ( sext_ln700_1_fu_641_p1 );

    SC_METHOD(thread_add_ln700_5_fu_758_p2);
    sensitive << ( sext_ln74_2_fu_709_p1 );
    sensitive << ( sext_ln74_3_fu_754_p1 );

    SC_METHOD(thread_add_ln700_6_fu_905_p2);
    sensitive << ( sext_ln74_5_fu_853_p1 );
    sensitive << ( sext_ln700_fu_895_p1 );

    SC_METHOD(thread_add_ln700_7_fu_915_p2);
    sensitive << ( sext_ln700_5_fu_911_p1 );
    sensitive << ( sext_ln74_4_fu_850_p1 );

    SC_METHOD(thread_add_ln700_8_fu_925_p2);
    sensitive << ( sext_ln700_6_fu_921_p1 );
    sensitive << ( sext_ln700_4_fu_902_p1 );

    SC_METHOD(thread_add_ln700_fu_507_p2);
    sensitive << ( sext_ln1353_fu_438_p1 );
    sensitive << ( sext_ln1353_1_fu_484_p1 );

    SC_METHOD(thread_add_ln74_10_fu_537_p2);
    sensitive << ( add_ln74_1_reg_982 );
    sensitive << ( zext_ln74_10_reg_993 );

    SC_METHOD(thread_add_ln74_11_fu_546_p2);
    sensitive << ( zext_ln74_10_reg_993 );
    sensitive << ( add_ln74_2_fu_513_p2 );

    SC_METHOD(thread_add_ln74_1_fu_381_p2);
    sensitive << ( sub_ln74_reg_942 );

    SC_METHOD(thread_add_ln74_2_fu_513_p2);
    sensitive << ( sub_ln74_reg_942 );

    SC_METHOD(thread_add_ln74_3_fu_349_p2);
    sensitive << ( sub_ln74_fu_339_p2 );
    sensitive << ( zext_ln74_2_fu_345_p1 );

    SC_METHOD(thread_add_ln74_4_fu_386_p2);
    sensitive << ( zext_ln74_2_reg_949 );
    sensitive << ( add_ln74_1_fu_381_p2 );

    SC_METHOD(thread_add_ln74_5_fu_518_p2);
    sensitive << ( zext_ln74_2_reg_949 );
    sensitive << ( add_ln74_2_fu_513_p2 );

    SC_METHOD(thread_add_ln74_6_fu_370_p2);
    sensitive << ( sub_ln74_fu_339_p2 );
    sensitive << ( zext_ln74_6_fu_366_p1 );

    SC_METHOD(thread_add_ln74_7_fu_523_p2);
    sensitive << ( zext_ln74_6_reg_960 );
    sensitive << ( add_ln74_1_reg_982 );

    SC_METHOD(thread_add_ln74_8_fu_532_p2);
    sensitive << ( zext_ln74_6_reg_960 );
    sensitive << ( add_ln74_2_fu_513_p2 );

    SC_METHOD(thread_add_ln74_9_fu_497_p2);
    sensitive << ( sub_ln74_reg_942 );
    sensitive << ( zext_ln74_10_fu_493_p1 );

    SC_METHOD(thread_add_ln74_fu_313_p2);
    sensitive << ( zext_ln74_fu_309_p1 );
    sensitive << ( zext_ln74_cast_fu_305_p1 );

    SC_METHOD(thread_and_ln1355_1_fu_454_p2);
    sensitive << ( trunc_ln215_1_fu_442_p1 );
    sensitive << ( select_ln215_1_fu_446_p3 );

    SC_METHOD(thread_and_ln1355_2_fu_562_p2);
    sensitive << ( trunc_ln215_2_fu_551_p1 );
    sensitive << ( select_ln215_2_fu_555_p3 );

    SC_METHOD(thread_and_ln1355_3_fu_607_p2);
    sensitive << ( trunc_ln215_3_fu_596_p1 );
    sensitive << ( select_ln215_3_fu_600_p3 );

    SC_METHOD(thread_and_ln1355_4_fu_679_p2);
    sensitive << ( trunc_ln215_4_fu_668_p1 );
    sensitive << ( select_ln215_4_fu_672_p3 );

    SC_METHOD(thread_and_ln1355_5_fu_724_p2);
    sensitive << ( trunc_ln215_5_fu_713_p1 );
    sensitive << ( select_ln215_5_fu_717_p3 );

    SC_METHOD(thread_and_ln1355_6_fu_779_p2);
    sensitive << ( trunc_ln215_6_fu_768_p1 );
    sensitive << ( select_ln215_6_fu_772_p3 );

    SC_METHOD(thread_and_ln1355_7_fu_820_p2);
    sensitive << ( trunc_ln215_7_fu_809_p1 );
    sensitive << ( select_ln215_7_fu_813_p3 );

    SC_METHOD(thread_and_ln1355_8_fu_865_p2);
    sensitive << ( trunc_ln215_8_fu_856_p1 );
    sensitive << ( select_ln215_8_fu_860_p3 );

    SC_METHOD(thread_and_ln1355_fu_408_p2);
    sensitive << ( trunc_ln215_fu_396_p1 );
    sensitive << ( select_ln215_fu_400_p3 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( ap_start );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( ap_start );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_ce );

    SC_METHOD(thread_ap_block_pp0_stage1);

    SC_METHOD(thread_ap_block_pp0_stage1_11001);

    SC_METHOD(thread_ap_block_pp0_stage1_subdone);
    sensitive << ( ap_ce );

    SC_METHOD(thread_ap_block_pp0_stage2);

    SC_METHOD(thread_ap_block_pp0_stage2_11001);

    SC_METHOD(thread_ap_block_pp0_stage2_subdone);
    sensitive << ( ap_ce );

    SC_METHOD(thread_ap_block_pp0_stage3);

    SC_METHOD(thread_ap_block_pp0_stage3_11001);

    SC_METHOD(thread_ap_block_pp0_stage3_subdone);
    sensitive << ( ap_ce );

    SC_METHOD(thread_ap_block_pp0_stage4);

    SC_METHOD(thread_ap_block_pp0_stage4_11001);

    SC_METHOD(thread_ap_block_pp0_stage4_subdone);
    sensitive << ( ap_ce );

    SC_METHOD(thread_ap_block_state1_pp0_stage0_iter0);
    sensitive << ( ap_start );

    SC_METHOD(thread_ap_block_state2_pp0_stage1_iter0);

    SC_METHOD(thread_ap_block_state3_pp0_stage2_iter0);

    SC_METHOD(thread_ap_block_state4_pp0_stage3_iter0);

    SC_METHOD(thread_ap_block_state5_pp0_stage4_iter0);

    SC_METHOD(thread_ap_block_state6_pp0_stage0_iter1);

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_ce );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_enable_reg_pp0_iter0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0_reg );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_ap_idle_pp0_0to0);
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_ap_idle_pp0_1to1);
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage4 );
    sensitive << ( ap_block_pp0_stage4_11001 );
    sensitive << ( ap_ce );

    SC_METHOD(thread_ap_reset_idle_pp0);
    sensitive << ( ap_start );
    sensitive << ( ap_idle_pp0_0to0 );

    SC_METHOD(thread_ap_return);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_ce );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( add_ln700_8_fu_925_p2 );
    sensitive << ( sext_ln700_3_fu_899_p1 );

    SC_METHOD(thread_line_buffer_m_V_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_CS_fsm_pp0_stage4 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( zext_ln74_3_fu_355_p1 );
    sensitive << ( ap_block_pp0_stage1 );
    sensitive << ( zext_ln74_11_fu_502_p1 );
    sensitive << ( zext_ln74_8_fu_527_p1 );
    sensitive << ( ap_block_pp0_stage2 );
    sensitive << ( zext_ln74_5_fu_660_p1 );
    sensitive << ( ap_block_pp0_stage3 );
    sensitive << ( zext_ln74_13_fu_764_p1 );
    sensitive << ( ap_block_pp0_stage4 );

    SC_METHOD(thread_line_buffer_m_V_address1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( zext_ln74_7_fu_376_p1 );
    sensitive << ( zext_ln74_4_fu_391_p1 );
    sensitive << ( ap_block_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage2 );
    sensitive << ( zext_ln74_12_fu_541_p1 );
    sensitive << ( ap_block_pp0_stage3 );
    sensitive << ( zext_ln74_9_fu_664_p1 );

    SC_METHOD(thread_line_buffer_m_V_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage4 );
    sensitive << ( ap_block_pp0_stage4_11001 );
    sensitive << ( ap_ce );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage1_11001 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage2_11001 );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_block_pp0_stage3_11001 );

    SC_METHOD(thread_line_buffer_m_V_ce1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_ce );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage1_11001 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage2_11001 );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_block_pp0_stage3_11001 );

    SC_METHOD(thread_p_shl_cast_fu_319_p3);
    sensitive << ( add_ln74_fu_313_p2 );

    SC_METHOD(thread_select_ln215_1_fu_446_p3);
    sensitive << ( ap_port_reg_conv_params_m_2_1_s );
    sensitive << ( ap_port_reg_conv_params_m_2_1_10 );
    sensitive << ( ap_port_reg_conv_params_m_V_offset );

    SC_METHOD(thread_select_ln215_2_fu_555_p3);
    sensitive << ( conv_params_m_V_offs_reg_971 );
    sensitive << ( ap_port_reg_conv_params_m_2_0_s );
    sensitive << ( ap_port_reg_conv_params_m_2_0_10 );

    SC_METHOD(thread_select_ln215_3_fu_600_p3);
    sensitive << ( conv_params_m_V_offs_reg_971 );
    sensitive << ( ap_port_reg_conv_params_m_1_2_s );
    sensitive << ( ap_port_reg_conv_params_m_1_2_10 );

    SC_METHOD(thread_select_ln215_4_fu_672_p3);
    sensitive << ( conv_params_m_V_offs_reg_971 );
    sensitive << ( ap_port_reg_conv_params_m_1_1_s );
    sensitive << ( ap_port_reg_conv_params_m_1_1_10 );

    SC_METHOD(thread_select_ln215_5_fu_717_p3);
    sensitive << ( conv_params_m_V_offs_reg_971 );
    sensitive << ( ap_port_reg_conv_params_m_1_0_s );
    sensitive << ( ap_port_reg_conv_params_m_1_0_10 );

    SC_METHOD(thread_select_ln215_6_fu_772_p3);
    sensitive << ( conv_params_m_V_offs_reg_971 );
    sensitive << ( ap_port_reg_conv_params_m_0_2_s );
    sensitive << ( ap_port_reg_conv_params_m_0_2_10 );

    SC_METHOD(thread_select_ln215_7_fu_813_p3);
    sensitive << ( conv_params_m_V_offs_reg_971 );
    sensitive << ( ap_port_reg_conv_params_m_0_1_s );
    sensitive << ( ap_port_reg_conv_params_m_0_1_10 );

    SC_METHOD(thread_select_ln215_8_fu_860_p3);
    sensitive << ( conv_params_m_V_offs_reg_971 );
    sensitive << ( conv_params_m_0_0_11_reg_1054 );
    sensitive << ( conv_params_m_0_0_12_reg_1059 );

    SC_METHOD(thread_select_ln215_fu_400_p3);
    sensitive << ( ap_port_reg_conv_params_m_2_2_s );
    sensitive << ( ap_port_reg_conv_params_m_2_2_10 );
    sensitive << ( ap_port_reg_conv_params_m_V_offset );

    SC_METHOD(thread_sext_ln1353_1_fu_484_p1);
    sensitive << ( tmp_58_fu_474_p4 );

    SC_METHOD(thread_sext_ln1353_fu_438_p1);
    sensitive << ( tmp_56_fu_428_p4 );

    SC_METHOD(thread_sext_ln700_1_fu_641_p1);
    sensitive << ( add_ln700_reg_1004 );

    SC_METHOD(thread_sext_ln700_2_fu_650_p1);
    sensitive << ( add_ln700_3_fu_644_p2 );

    SC_METHOD(thread_sext_ln700_3_fu_899_p1);
    sensitive << ( add_ln700_4_reg_1034 );

    SC_METHOD(thread_sext_ln700_4_fu_902_p1);
    sensitive << ( add_ln700_5_reg_1049 );

    SC_METHOD(thread_sext_ln700_5_fu_911_p1);
    sensitive << ( add_ln700_6_fu_905_p2 );

    SC_METHOD(thread_sext_ln700_6_fu_921_p1);
    sensitive << ( add_ln700_7_fu_915_p2 );

    SC_METHOD(thread_sext_ln700_fu_895_p1);
    sensitive << ( tmp_72_fu_885_p4 );

    SC_METHOD(thread_sext_ln74_1_fu_637_p1);
    sensitive << ( tmp_62_fu_627_p4 );

    SC_METHOD(thread_sext_ln74_2_fu_709_p1);
    sensitive << ( tmp_64_fu_699_p4 );

    SC_METHOD(thread_sext_ln74_3_fu_754_p1);
    sensitive << ( tmp_66_fu_744_p4 );

    SC_METHOD(thread_sext_ln74_4_fu_850_p1);
    sensitive << ( tmp_68_reg_1069 );

    SC_METHOD(thread_sext_ln74_5_fu_853_p1);
    sensitive << ( tmp_70_reg_1074 );

    SC_METHOD(thread_sext_ln74_fu_592_p1);
    sensitive << ( tmp_60_fu_582_p4 );

    SC_METHOD(thread_sub_ln74_fu_339_p2);
    sensitive << ( p_shl_cast_fu_319_p3 );
    sensitive << ( zext_ln74_1_fu_335_p1 );

    SC_METHOD(thread_tmp_54_fu_327_p3);
    sensitive << ( add_ln74_fu_313_p2 );

    SC_METHOD(thread_tmp_55_fu_414_p3);
    sensitive << ( line_buffer_m_V_q0 );

    SC_METHOD(thread_tmp_56_fu_428_p4);
    sensitive << ( line_buffer_m_V_q0 );
    sensitive << ( xor_ln841_fu_422_p2 );

    SC_METHOD(thread_tmp_57_fu_460_p3);
    sensitive << ( line_buffer_m_V_q1 );

    SC_METHOD(thread_tmp_58_fu_474_p4);
    sensitive << ( line_buffer_m_V_q1 );
    sensitive << ( xor_ln841_1_fu_468_p2 );

    SC_METHOD(thread_tmp_59_fu_568_p3);
    sensitive << ( line_buffer_m_V_q0 );

    SC_METHOD(thread_tmp_60_fu_582_p4);
    sensitive << ( line_buffer_m_V_q0 );
    sensitive << ( xor_ln841_2_fu_576_p2 );

    SC_METHOD(thread_tmp_61_fu_613_p3);
    sensitive << ( line_buffer_m_V_q1 );

    SC_METHOD(thread_tmp_62_fu_627_p4);
    sensitive << ( line_buffer_m_V_q1 );
    sensitive << ( xor_ln841_3_fu_621_p2 );

    SC_METHOD(thread_tmp_63_fu_685_p3);
    sensitive << ( line_buffer_m_V_q0 );

    SC_METHOD(thread_tmp_64_fu_699_p4);
    sensitive << ( line_buffer_m_V_q0 );
    sensitive << ( xor_ln841_4_fu_693_p2 );

    SC_METHOD(thread_tmp_65_fu_730_p3);
    sensitive << ( line_buffer_m_V_q1 );

    SC_METHOD(thread_tmp_66_fu_744_p4);
    sensitive << ( line_buffer_m_V_q1 );
    sensitive << ( xor_ln841_5_fu_738_p2 );

    SC_METHOD(thread_tmp_67_fu_785_p3);
    sensitive << ( line_buffer_m_V_q0 );

    SC_METHOD(thread_tmp_68_fu_799_p4);
    sensitive << ( line_buffer_m_V_q0 );
    sensitive << ( xor_ln841_6_fu_793_p2 );

    SC_METHOD(thread_tmp_69_fu_826_p3);
    sensitive << ( line_buffer_m_V_q1 );

    SC_METHOD(thread_tmp_70_fu_840_p4);
    sensitive << ( line_buffer_m_V_q1 );
    sensitive << ( xor_ln841_7_fu_834_p2 );

    SC_METHOD(thread_tmp_71_fu_871_p3);
    sensitive << ( line_buffer_m_V_q0 );

    SC_METHOD(thread_tmp_72_fu_885_p4);
    sensitive << ( line_buffer_m_V_q0 );
    sensitive << ( xor_ln841_8_fu_879_p2 );

    SC_METHOD(thread_tmp_fu_297_p3);
    sensitive << ( line_buffer_m_V_offset );

    SC_METHOD(thread_trunc_ln215_1_fu_442_p1);
    sensitive << ( line_buffer_m_V_q1 );

    SC_METHOD(thread_trunc_ln215_2_fu_551_p1);
    sensitive << ( line_buffer_m_V_q0 );

    SC_METHOD(thread_trunc_ln215_3_fu_596_p1);
    sensitive << ( line_buffer_m_V_q1 );

    SC_METHOD(thread_trunc_ln215_4_fu_668_p1);
    sensitive << ( line_buffer_m_V_q0 );

    SC_METHOD(thread_trunc_ln215_5_fu_713_p1);
    sensitive << ( line_buffer_m_V_q1 );

    SC_METHOD(thread_trunc_ln215_6_fu_768_p1);
    sensitive << ( line_buffer_m_V_q0 );

    SC_METHOD(thread_trunc_ln215_7_fu_809_p1);
    sensitive << ( line_buffer_m_V_q1 );

    SC_METHOD(thread_trunc_ln215_8_fu_856_p1);
    sensitive << ( line_buffer_m_V_q0 );

    SC_METHOD(thread_trunc_ln215_fu_396_p1);
    sensitive << ( line_buffer_m_V_q0 );

    SC_METHOD(thread_xor_ln841_1_fu_468_p2);
    sensitive << ( and_ln1355_1_fu_454_p2 );
    sensitive << ( tmp_57_fu_460_p3 );

    SC_METHOD(thread_xor_ln841_2_fu_576_p2);
    sensitive << ( and_ln1355_2_fu_562_p2 );
    sensitive << ( tmp_59_fu_568_p3 );

    SC_METHOD(thread_xor_ln841_3_fu_621_p2);
    sensitive << ( and_ln1355_3_fu_607_p2 );
    sensitive << ( tmp_61_fu_613_p3 );

    SC_METHOD(thread_xor_ln841_4_fu_693_p2);
    sensitive << ( and_ln1355_4_fu_679_p2 );
    sensitive << ( tmp_63_fu_685_p3 );

    SC_METHOD(thread_xor_ln841_5_fu_738_p2);
    sensitive << ( and_ln1355_5_fu_724_p2 );
    sensitive << ( tmp_65_fu_730_p3 );

    SC_METHOD(thread_xor_ln841_6_fu_793_p2);
    sensitive << ( and_ln1355_6_fu_779_p2 );
    sensitive << ( tmp_67_fu_785_p3 );

    SC_METHOD(thread_xor_ln841_7_fu_834_p2);
    sensitive << ( and_ln1355_7_fu_820_p2 );
    sensitive << ( tmp_69_fu_826_p3 );

    SC_METHOD(thread_xor_ln841_8_fu_879_p2);
    sensitive << ( and_ln1355_8_fu_865_p2 );
    sensitive << ( tmp_71_fu_871_p3 );

    SC_METHOD(thread_xor_ln841_fu_422_p2);
    sensitive << ( and_ln1355_fu_408_p2 );
    sensitive << ( tmp_55_fu_414_p3 );

    SC_METHOD(thread_zext_ln74_10_fu_493_p1);
    sensitive << ( add_ln1353_14_fu_488_p2 );

    SC_METHOD(thread_zext_ln74_11_fu_502_p1);
    sensitive << ( add_ln74_9_fu_497_p2 );

    SC_METHOD(thread_zext_ln74_12_fu_541_p1);
    sensitive << ( add_ln74_10_fu_537_p2 );

    SC_METHOD(thread_zext_ln74_13_fu_764_p1);
    sensitive << ( add_ln74_11_reg_1029 );

    SC_METHOD(thread_zext_ln74_1_fu_335_p1);
    sensitive << ( tmp_54_fu_327_p3 );

    SC_METHOD(thread_zext_ln74_2_fu_345_p1);
    sensitive << ( cc_V );

    SC_METHOD(thread_zext_ln74_3_fu_355_p1);
    sensitive << ( add_ln74_3_fu_349_p2 );

    SC_METHOD(thread_zext_ln74_4_fu_391_p1);
    sensitive << ( add_ln74_4_fu_386_p2 );

    SC_METHOD(thread_zext_ln74_5_fu_660_p1);
    sensitive << ( add_ln74_5_reg_1009 );

    SC_METHOD(thread_zext_ln74_6_fu_366_p1);
    sensitive << ( add_ln1353_fu_360_p2 );

    SC_METHOD(thread_zext_ln74_7_fu_376_p1);
    sensitive << ( add_ln74_6_fu_370_p2 );

    SC_METHOD(thread_zext_ln74_8_fu_527_p1);
    sensitive << ( add_ln74_7_fu_523_p2 );

    SC_METHOD(thread_zext_ln74_9_fu_664_p1);
    sensitive << ( add_ln74_8_reg_1019 );

    SC_METHOD(thread_zext_ln74_cast_fu_305_p1);
    sensitive << ( tmp_fu_297_p3 );

    SC_METHOD(thread_zext_ln74_fu_309_p1);
    sensitive << ( bank_V );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_block_pp0_stage4_subdone );
    sensitive << ( ap_reset_idle_pp0 );
    sensitive << ( ap_idle_pp0_1to1 );
    sensitive << ( ap_block_pp0_stage1_subdone );
    sensitive << ( ap_block_pp0_stage2_subdone );
    sensitive << ( ap_block_pp0_stage3_subdone );

    ap_CS_fsm = "00001";
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter0_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "conv3x3b_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, ap_ce, "(port)ap_ce");
    sc_trace(mVcdFile, line_buffer_m_V_address0, "(port)line_buffer_m_V_address0");
    sc_trace(mVcdFile, line_buffer_m_V_ce0, "(port)line_buffer_m_V_ce0");
    sc_trace(mVcdFile, line_buffer_m_V_q0, "(port)line_buffer_m_V_q0");
    sc_trace(mVcdFile, line_buffer_m_V_address1, "(port)line_buffer_m_V_address1");
    sc_trace(mVcdFile, line_buffer_m_V_ce1, "(port)line_buffer_m_V_ce1");
    sc_trace(mVcdFile, line_buffer_m_V_q1, "(port)line_buffer_m_V_q1");
    sc_trace(mVcdFile, line_buffer_m_V_offset, "(port)line_buffer_m_V_offset");
    sc_trace(mVcdFile, conv_params_m_0_0_s, "(port)conv_params_m_0_0_s");
    sc_trace(mVcdFile, conv_params_m_0_0_10, "(port)conv_params_m_0_0_10");
    sc_trace(mVcdFile, conv_params_m_0_1_s, "(port)conv_params_m_0_1_s");
    sc_trace(mVcdFile, conv_params_m_0_1_10, "(port)conv_params_m_0_1_10");
    sc_trace(mVcdFile, conv_params_m_0_2_s, "(port)conv_params_m_0_2_s");
    sc_trace(mVcdFile, conv_params_m_0_2_10, "(port)conv_params_m_0_2_10");
    sc_trace(mVcdFile, conv_params_m_1_0_s, "(port)conv_params_m_1_0_s");
    sc_trace(mVcdFile, conv_params_m_1_0_10, "(port)conv_params_m_1_0_10");
    sc_trace(mVcdFile, conv_params_m_1_1_s, "(port)conv_params_m_1_1_s");
    sc_trace(mVcdFile, conv_params_m_1_1_10, "(port)conv_params_m_1_1_10");
    sc_trace(mVcdFile, conv_params_m_1_2_s, "(port)conv_params_m_1_2_s");
    sc_trace(mVcdFile, conv_params_m_1_2_10, "(port)conv_params_m_1_2_10");
    sc_trace(mVcdFile, conv_params_m_2_0_s, "(port)conv_params_m_2_0_s");
    sc_trace(mVcdFile, conv_params_m_2_0_10, "(port)conv_params_m_2_0_10");
    sc_trace(mVcdFile, conv_params_m_2_1_s, "(port)conv_params_m_2_1_s");
    sc_trace(mVcdFile, conv_params_m_2_1_10, "(port)conv_params_m_2_1_10");
    sc_trace(mVcdFile, conv_params_m_2_2_s, "(port)conv_params_m_2_2_s");
    sc_trace(mVcdFile, conv_params_m_2_2_10, "(port)conv_params_m_2_2_10");
    sc_trace(mVcdFile, conv_params_m_V_offset, "(port)conv_params_m_V_offset");
    sc_trace(mVcdFile, bank_V, "(port)bank_V");
    sc_trace(mVcdFile, cc_V, "(port)cc_V");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage4, "ap_CS_fsm_pp0_stage4");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage4_iter0, "ap_block_state5_pp0_stage4_iter0");
    sc_trace(mVcdFile, ap_block_pp0_stage4_11001, "ap_block_pp0_stage4_11001");
    sc_trace(mVcdFile, cc_V_read_reg_937, "cc_V_read_reg_937");
    sc_trace(mVcdFile, ap_block_state1_pp0_stage0_iter0, "ap_block_state1_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state6_pp0_stage0_iter1, "ap_block_state6_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, sub_ln74_fu_339_p2, "sub_ln74_fu_339_p2");
    sc_trace(mVcdFile, sub_ln74_reg_942, "sub_ln74_reg_942");
    sc_trace(mVcdFile, zext_ln74_2_fu_345_p1, "zext_ln74_2_fu_345_p1");
    sc_trace(mVcdFile, zext_ln74_2_reg_949, "zext_ln74_2_reg_949");
    sc_trace(mVcdFile, zext_ln74_6_fu_366_p1, "zext_ln74_6_fu_366_p1");
    sc_trace(mVcdFile, zext_ln74_6_reg_960, "zext_ln74_6_reg_960");
    sc_trace(mVcdFile, conv_params_m_V_offs_reg_971, "conv_params_m_V_offs_reg_971");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage1, "ap_CS_fsm_pp0_stage1");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage1_iter0, "ap_block_state2_pp0_stage1_iter0");
    sc_trace(mVcdFile, ap_block_pp0_stage1_11001, "ap_block_pp0_stage1_11001");
    sc_trace(mVcdFile, add_ln74_1_fu_381_p2, "add_ln74_1_fu_381_p2");
    sc_trace(mVcdFile, add_ln74_1_reg_982, "add_ln74_1_reg_982");
    sc_trace(mVcdFile, zext_ln74_10_fu_493_p1, "zext_ln74_10_fu_493_p1");
    sc_trace(mVcdFile, zext_ln74_10_reg_993, "zext_ln74_10_reg_993");
    sc_trace(mVcdFile, add_ln700_fu_507_p2, "add_ln700_fu_507_p2");
    sc_trace(mVcdFile, add_ln700_reg_1004, "add_ln700_reg_1004");
    sc_trace(mVcdFile, add_ln74_5_fu_518_p2, "add_ln74_5_fu_518_p2");
    sc_trace(mVcdFile, add_ln74_5_reg_1009, "add_ln74_5_reg_1009");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage2, "ap_CS_fsm_pp0_stage2");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage2_iter0, "ap_block_state3_pp0_stage2_iter0");
    sc_trace(mVcdFile, ap_block_pp0_stage2_11001, "ap_block_pp0_stage2_11001");
    sc_trace(mVcdFile, add_ln74_8_fu_532_p2, "add_ln74_8_fu_532_p2");
    sc_trace(mVcdFile, add_ln74_8_reg_1019, "add_ln74_8_reg_1019");
    sc_trace(mVcdFile, add_ln74_11_fu_546_p2, "add_ln74_11_fu_546_p2");
    sc_trace(mVcdFile, add_ln74_11_reg_1029, "add_ln74_11_reg_1029");
    sc_trace(mVcdFile, add_ln700_4_fu_654_p2, "add_ln700_4_fu_654_p2");
    sc_trace(mVcdFile, add_ln700_4_reg_1034, "add_ln700_4_reg_1034");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage3, "ap_CS_fsm_pp0_stage3");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage3_iter0, "ap_block_state4_pp0_stage3_iter0");
    sc_trace(mVcdFile, ap_block_pp0_stage3_11001, "ap_block_pp0_stage3_11001");
    sc_trace(mVcdFile, add_ln700_5_fu_758_p2, "add_ln700_5_fu_758_p2");
    sc_trace(mVcdFile, add_ln700_5_reg_1049, "add_ln700_5_reg_1049");
    sc_trace(mVcdFile, conv_params_m_0_0_11_reg_1054, "conv_params_m_0_0_11_reg_1054");
    sc_trace(mVcdFile, conv_params_m_0_0_12_reg_1059, "conv_params_m_0_0_12_reg_1059");
    sc_trace(mVcdFile, tmp_68_fu_799_p4, "tmp_68_fu_799_p4");
    sc_trace(mVcdFile, tmp_68_reg_1069, "tmp_68_reg_1069");
    sc_trace(mVcdFile, tmp_70_fu_840_p4, "tmp_70_fu_840_p4");
    sc_trace(mVcdFile, tmp_70_reg_1074, "tmp_70_reg_1074");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0_reg, "ap_enable_reg_pp0_iter0_reg");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_block_pp0_stage4_subdone, "ap_block_pp0_stage4_subdone");
    sc_trace(mVcdFile, ap_port_reg_conv_params_m_0_0_s, "ap_port_reg_conv_params_m_0_0_s");
    sc_trace(mVcdFile, ap_port_reg_conv_params_m_0_0_10, "ap_port_reg_conv_params_m_0_0_10");
    sc_trace(mVcdFile, ap_port_reg_conv_params_m_0_1_s, "ap_port_reg_conv_params_m_0_1_s");
    sc_trace(mVcdFile, ap_port_reg_conv_params_m_0_1_10, "ap_port_reg_conv_params_m_0_1_10");
    sc_trace(mVcdFile, ap_port_reg_conv_params_m_0_2_s, "ap_port_reg_conv_params_m_0_2_s");
    sc_trace(mVcdFile, ap_port_reg_conv_params_m_0_2_10, "ap_port_reg_conv_params_m_0_2_10");
    sc_trace(mVcdFile, ap_port_reg_conv_params_m_1_0_s, "ap_port_reg_conv_params_m_1_0_s");
    sc_trace(mVcdFile, ap_port_reg_conv_params_m_1_0_10, "ap_port_reg_conv_params_m_1_0_10");
    sc_trace(mVcdFile, ap_port_reg_conv_params_m_1_1_s, "ap_port_reg_conv_params_m_1_1_s");
    sc_trace(mVcdFile, ap_port_reg_conv_params_m_1_1_10, "ap_port_reg_conv_params_m_1_1_10");
    sc_trace(mVcdFile, ap_port_reg_conv_params_m_1_2_s, "ap_port_reg_conv_params_m_1_2_s");
    sc_trace(mVcdFile, ap_port_reg_conv_params_m_1_2_10, "ap_port_reg_conv_params_m_1_2_10");
    sc_trace(mVcdFile, ap_port_reg_conv_params_m_2_0_s, "ap_port_reg_conv_params_m_2_0_s");
    sc_trace(mVcdFile, ap_port_reg_conv_params_m_2_0_10, "ap_port_reg_conv_params_m_2_0_10");
    sc_trace(mVcdFile, ap_port_reg_conv_params_m_2_1_s, "ap_port_reg_conv_params_m_2_1_s");
    sc_trace(mVcdFile, ap_port_reg_conv_params_m_2_1_10, "ap_port_reg_conv_params_m_2_1_10");
    sc_trace(mVcdFile, ap_port_reg_conv_params_m_2_2_s, "ap_port_reg_conv_params_m_2_2_s");
    sc_trace(mVcdFile, ap_port_reg_conv_params_m_2_2_10, "ap_port_reg_conv_params_m_2_2_10");
    sc_trace(mVcdFile, ap_port_reg_conv_params_m_V_offset, "ap_port_reg_conv_params_m_V_offset");
    sc_trace(mVcdFile, zext_ln74_3_fu_355_p1, "zext_ln74_3_fu_355_p1");
    sc_trace(mVcdFile, zext_ln74_7_fu_376_p1, "zext_ln74_7_fu_376_p1");
    sc_trace(mVcdFile, zext_ln74_4_fu_391_p1, "zext_ln74_4_fu_391_p1");
    sc_trace(mVcdFile, ap_block_pp0_stage1, "ap_block_pp0_stage1");
    sc_trace(mVcdFile, zext_ln74_11_fu_502_p1, "zext_ln74_11_fu_502_p1");
    sc_trace(mVcdFile, zext_ln74_8_fu_527_p1, "zext_ln74_8_fu_527_p1");
    sc_trace(mVcdFile, ap_block_pp0_stage2, "ap_block_pp0_stage2");
    sc_trace(mVcdFile, zext_ln74_12_fu_541_p1, "zext_ln74_12_fu_541_p1");
    sc_trace(mVcdFile, zext_ln74_5_fu_660_p1, "zext_ln74_5_fu_660_p1");
    sc_trace(mVcdFile, ap_block_pp0_stage3, "ap_block_pp0_stage3");
    sc_trace(mVcdFile, zext_ln74_9_fu_664_p1, "zext_ln74_9_fu_664_p1");
    sc_trace(mVcdFile, zext_ln74_13_fu_764_p1, "zext_ln74_13_fu_764_p1");
    sc_trace(mVcdFile, ap_block_pp0_stage4, "ap_block_pp0_stage4");
    sc_trace(mVcdFile, tmp_fu_297_p3, "tmp_fu_297_p3");
    sc_trace(mVcdFile, zext_ln74_fu_309_p1, "zext_ln74_fu_309_p1");
    sc_trace(mVcdFile, zext_ln74_cast_fu_305_p1, "zext_ln74_cast_fu_305_p1");
    sc_trace(mVcdFile, add_ln74_fu_313_p2, "add_ln74_fu_313_p2");
    sc_trace(mVcdFile, tmp_54_fu_327_p3, "tmp_54_fu_327_p3");
    sc_trace(mVcdFile, p_shl_cast_fu_319_p3, "p_shl_cast_fu_319_p3");
    sc_trace(mVcdFile, zext_ln74_1_fu_335_p1, "zext_ln74_1_fu_335_p1");
    sc_trace(mVcdFile, add_ln74_3_fu_349_p2, "add_ln74_3_fu_349_p2");
    sc_trace(mVcdFile, add_ln1353_fu_360_p2, "add_ln1353_fu_360_p2");
    sc_trace(mVcdFile, add_ln74_6_fu_370_p2, "add_ln74_6_fu_370_p2");
    sc_trace(mVcdFile, add_ln74_4_fu_386_p2, "add_ln74_4_fu_386_p2");
    sc_trace(mVcdFile, trunc_ln215_fu_396_p1, "trunc_ln215_fu_396_p1");
    sc_trace(mVcdFile, select_ln215_fu_400_p3, "select_ln215_fu_400_p3");
    sc_trace(mVcdFile, and_ln1355_fu_408_p2, "and_ln1355_fu_408_p2");
    sc_trace(mVcdFile, tmp_55_fu_414_p3, "tmp_55_fu_414_p3");
    sc_trace(mVcdFile, xor_ln841_fu_422_p2, "xor_ln841_fu_422_p2");
    sc_trace(mVcdFile, tmp_56_fu_428_p4, "tmp_56_fu_428_p4");
    sc_trace(mVcdFile, trunc_ln215_1_fu_442_p1, "trunc_ln215_1_fu_442_p1");
    sc_trace(mVcdFile, select_ln215_1_fu_446_p3, "select_ln215_1_fu_446_p3");
    sc_trace(mVcdFile, and_ln1355_1_fu_454_p2, "and_ln1355_1_fu_454_p2");
    sc_trace(mVcdFile, tmp_57_fu_460_p3, "tmp_57_fu_460_p3");
    sc_trace(mVcdFile, xor_ln841_1_fu_468_p2, "xor_ln841_1_fu_468_p2");
    sc_trace(mVcdFile, tmp_58_fu_474_p4, "tmp_58_fu_474_p4");
    sc_trace(mVcdFile, add_ln1353_14_fu_488_p2, "add_ln1353_14_fu_488_p2");
    sc_trace(mVcdFile, add_ln74_9_fu_497_p2, "add_ln74_9_fu_497_p2");
    sc_trace(mVcdFile, sext_ln1353_fu_438_p1, "sext_ln1353_fu_438_p1");
    sc_trace(mVcdFile, sext_ln1353_1_fu_484_p1, "sext_ln1353_1_fu_484_p1");
    sc_trace(mVcdFile, add_ln74_2_fu_513_p2, "add_ln74_2_fu_513_p2");
    sc_trace(mVcdFile, add_ln74_7_fu_523_p2, "add_ln74_7_fu_523_p2");
    sc_trace(mVcdFile, add_ln74_10_fu_537_p2, "add_ln74_10_fu_537_p2");
    sc_trace(mVcdFile, trunc_ln215_2_fu_551_p1, "trunc_ln215_2_fu_551_p1");
    sc_trace(mVcdFile, select_ln215_2_fu_555_p3, "select_ln215_2_fu_555_p3");
    sc_trace(mVcdFile, and_ln1355_2_fu_562_p2, "and_ln1355_2_fu_562_p2");
    sc_trace(mVcdFile, tmp_59_fu_568_p3, "tmp_59_fu_568_p3");
    sc_trace(mVcdFile, xor_ln841_2_fu_576_p2, "xor_ln841_2_fu_576_p2");
    sc_trace(mVcdFile, tmp_60_fu_582_p4, "tmp_60_fu_582_p4");
    sc_trace(mVcdFile, trunc_ln215_3_fu_596_p1, "trunc_ln215_3_fu_596_p1");
    sc_trace(mVcdFile, select_ln215_3_fu_600_p3, "select_ln215_3_fu_600_p3");
    sc_trace(mVcdFile, and_ln1355_3_fu_607_p2, "and_ln1355_3_fu_607_p2");
    sc_trace(mVcdFile, tmp_61_fu_613_p3, "tmp_61_fu_613_p3");
    sc_trace(mVcdFile, xor_ln841_3_fu_621_p2, "xor_ln841_3_fu_621_p2");
    sc_trace(mVcdFile, tmp_62_fu_627_p4, "tmp_62_fu_627_p4");
    sc_trace(mVcdFile, sext_ln74_fu_592_p1, "sext_ln74_fu_592_p1");
    sc_trace(mVcdFile, sext_ln74_1_fu_637_p1, "sext_ln74_1_fu_637_p1");
    sc_trace(mVcdFile, add_ln700_3_fu_644_p2, "add_ln700_3_fu_644_p2");
    sc_trace(mVcdFile, sext_ln700_2_fu_650_p1, "sext_ln700_2_fu_650_p1");
    sc_trace(mVcdFile, sext_ln700_1_fu_641_p1, "sext_ln700_1_fu_641_p1");
    sc_trace(mVcdFile, trunc_ln215_4_fu_668_p1, "trunc_ln215_4_fu_668_p1");
    sc_trace(mVcdFile, select_ln215_4_fu_672_p3, "select_ln215_4_fu_672_p3");
    sc_trace(mVcdFile, and_ln1355_4_fu_679_p2, "and_ln1355_4_fu_679_p2");
    sc_trace(mVcdFile, tmp_63_fu_685_p3, "tmp_63_fu_685_p3");
    sc_trace(mVcdFile, xor_ln841_4_fu_693_p2, "xor_ln841_4_fu_693_p2");
    sc_trace(mVcdFile, tmp_64_fu_699_p4, "tmp_64_fu_699_p4");
    sc_trace(mVcdFile, trunc_ln215_5_fu_713_p1, "trunc_ln215_5_fu_713_p1");
    sc_trace(mVcdFile, select_ln215_5_fu_717_p3, "select_ln215_5_fu_717_p3");
    sc_trace(mVcdFile, and_ln1355_5_fu_724_p2, "and_ln1355_5_fu_724_p2");
    sc_trace(mVcdFile, tmp_65_fu_730_p3, "tmp_65_fu_730_p3");
    sc_trace(mVcdFile, xor_ln841_5_fu_738_p2, "xor_ln841_5_fu_738_p2");
    sc_trace(mVcdFile, tmp_66_fu_744_p4, "tmp_66_fu_744_p4");
    sc_trace(mVcdFile, sext_ln74_2_fu_709_p1, "sext_ln74_2_fu_709_p1");
    sc_trace(mVcdFile, sext_ln74_3_fu_754_p1, "sext_ln74_3_fu_754_p1");
    sc_trace(mVcdFile, trunc_ln215_6_fu_768_p1, "trunc_ln215_6_fu_768_p1");
    sc_trace(mVcdFile, select_ln215_6_fu_772_p3, "select_ln215_6_fu_772_p3");
    sc_trace(mVcdFile, and_ln1355_6_fu_779_p2, "and_ln1355_6_fu_779_p2");
    sc_trace(mVcdFile, tmp_67_fu_785_p3, "tmp_67_fu_785_p3");
    sc_trace(mVcdFile, xor_ln841_6_fu_793_p2, "xor_ln841_6_fu_793_p2");
    sc_trace(mVcdFile, trunc_ln215_7_fu_809_p1, "trunc_ln215_7_fu_809_p1");
    sc_trace(mVcdFile, select_ln215_7_fu_813_p3, "select_ln215_7_fu_813_p3");
    sc_trace(mVcdFile, and_ln1355_7_fu_820_p2, "and_ln1355_7_fu_820_p2");
    sc_trace(mVcdFile, tmp_69_fu_826_p3, "tmp_69_fu_826_p3");
    sc_trace(mVcdFile, xor_ln841_7_fu_834_p2, "xor_ln841_7_fu_834_p2");
    sc_trace(mVcdFile, trunc_ln215_8_fu_856_p1, "trunc_ln215_8_fu_856_p1");
    sc_trace(mVcdFile, select_ln215_8_fu_860_p3, "select_ln215_8_fu_860_p3");
    sc_trace(mVcdFile, and_ln1355_8_fu_865_p2, "and_ln1355_8_fu_865_p2");
    sc_trace(mVcdFile, tmp_71_fu_871_p3, "tmp_71_fu_871_p3");
    sc_trace(mVcdFile, xor_ln841_8_fu_879_p2, "xor_ln841_8_fu_879_p2");
    sc_trace(mVcdFile, tmp_72_fu_885_p4, "tmp_72_fu_885_p4");
    sc_trace(mVcdFile, sext_ln74_5_fu_853_p1, "sext_ln74_5_fu_853_p1");
    sc_trace(mVcdFile, sext_ln700_fu_895_p1, "sext_ln700_fu_895_p1");
    sc_trace(mVcdFile, add_ln700_6_fu_905_p2, "add_ln700_6_fu_905_p2");
    sc_trace(mVcdFile, sext_ln700_5_fu_911_p1, "sext_ln700_5_fu_911_p1");
    sc_trace(mVcdFile, sext_ln74_4_fu_850_p1, "sext_ln74_4_fu_850_p1");
    sc_trace(mVcdFile, add_ln700_7_fu_915_p2, "add_ln700_7_fu_915_p2");
    sc_trace(mVcdFile, sext_ln700_6_fu_921_p1, "sext_ln700_6_fu_921_p1");
    sc_trace(mVcdFile, sext_ln700_4_fu_902_p1, "sext_ln700_4_fu_902_p1");
    sc_trace(mVcdFile, add_ln700_8_fu_925_p2, "add_ln700_8_fu_925_p2");
    sc_trace(mVcdFile, sext_ln700_3_fu_899_p1, "sext_ln700_3_fu_899_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0_0to0, "ap_idle_pp0_0to0");
    sc_trace(mVcdFile, ap_reset_idle_pp0, "ap_reset_idle_pp0");
    sc_trace(mVcdFile, ap_idle_pp0_1to1, "ap_idle_pp0_1to1");
    sc_trace(mVcdFile, ap_block_pp0_stage1_subdone, "ap_block_pp0_stage1_subdone");
    sc_trace(mVcdFile, ap_block_pp0_stage2_subdone, "ap_block_pp0_stage2_subdone");
    sc_trace(mVcdFile, ap_block_pp0_stage3_subdone, "ap_block_pp0_stage3_subdone");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
#endif

    }
}

conv3x3b::~conv3x3b() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void conv3x3b::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_pp0_stage0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read())) {
            ap_enable_reg_pp0_iter0_reg = ap_start.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage4.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage4_subdone.read(), ap_const_boolean_0))) {
            ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
                    esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_0))) {
            ap_enable_reg_pp0_iter1 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage2_11001.read(), ap_const_boolean_0))) {
        add_ln700_4_reg_1034 = add_ln700_4_fu_654_p2.read();
        add_ln74_11_reg_1029 = add_ln74_11_fu_546_p2.read();
        add_ln74_5_reg_1009 = add_ln74_5_fu_518_p2.read();
        add_ln74_8_reg_1019 = add_ln74_8_fu_532_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage3_11001.read(), ap_const_boolean_0))) {
        add_ln700_5_reg_1049 = add_ln700_5_fu_758_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0))) {
        add_ln700_reg_1004 = add_ln700_fu_507_p2.read();
        add_ln74_1_reg_982 = add_ln74_1_fu_381_p2.read();
        conv_params_m_V_offs_reg_971 = ap_port_reg_conv_params_m_V_offset.read();
        zext_ln74_10_reg_993 = zext_ln74_10_fu_493_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        ap_port_reg_conv_params_m_0_0_10 = conv_params_m_0_0_10.read();
        ap_port_reg_conv_params_m_0_0_s = conv_params_m_0_0_s.read();
        ap_port_reg_conv_params_m_0_1_10 = conv_params_m_0_1_10.read();
        ap_port_reg_conv_params_m_0_1_s = conv_params_m_0_1_s.read();
        ap_port_reg_conv_params_m_0_2_10 = conv_params_m_0_2_10.read();
        ap_port_reg_conv_params_m_0_2_s = conv_params_m_0_2_s.read();
        ap_port_reg_conv_params_m_1_0_10 = conv_params_m_1_0_10.read();
        ap_port_reg_conv_params_m_1_0_s = conv_params_m_1_0_s.read();
        ap_port_reg_conv_params_m_1_1_10 = conv_params_m_1_1_10.read();
        ap_port_reg_conv_params_m_1_1_s = conv_params_m_1_1_s.read();
        ap_port_reg_conv_params_m_1_2_10 = conv_params_m_1_2_10.read();
        ap_port_reg_conv_params_m_1_2_s = conv_params_m_1_2_s.read();
        ap_port_reg_conv_params_m_2_0_10 = conv_params_m_2_0_10.read();
        ap_port_reg_conv_params_m_2_0_s = conv_params_m_2_0_s.read();
        ap_port_reg_conv_params_m_2_1_10 = conv_params_m_2_1_10.read();
        ap_port_reg_conv_params_m_2_1_s = conv_params_m_2_1_s.read();
        ap_port_reg_conv_params_m_2_2_10 = conv_params_m_2_2_10.read();
        ap_port_reg_conv_params_m_2_2_s = conv_params_m_2_2_s.read();
        ap_port_reg_conv_params_m_V_offset = conv_params_m_V_offset.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        cc_V_read_reg_937 = cc_V.read();
        sub_ln74_reg_942 = sub_ln74_fu_339_p2.read();
        zext_ln74_2_reg_949 = zext_ln74_2_fu_345_p1.read();
        zext_ln74_6_reg_960 = zext_ln74_6_fu_366_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage4.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage4_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1))) {
        conv_params_m_0_0_11_reg_1054 = ap_port_reg_conv_params_m_0_0_10.read();
        conv_params_m_0_0_12_reg_1059 = ap_port_reg_conv_params_m_0_0_s.read();
        tmp_68_reg_1069 = tmp_68_fu_799_p4.read();
        tmp_70_reg_1074 = tmp_70_fu_840_p4.read();
    }
}

void conv3x3b::thread_add_ln1353_14_fu_488_p2() {
    add_ln1353_14_fu_488_p2 = (!ap_const_lv4_2.is_01() || !cc_V_read_reg_937.read().is_01())? sc_lv<4>(): (sc_biguint<4>(ap_const_lv4_2) + sc_biguint<4>(cc_V_read_reg_937.read()));
}

void conv3x3b::thread_add_ln1353_fu_360_p2() {
    add_ln1353_fu_360_p2 = (!ap_const_lv4_1.is_01() || !cc_V.read().is_01())? sc_lv<4>(): (sc_biguint<4>(ap_const_lv4_1) + sc_biguint<4>(cc_V.read()));
}

void conv3x3b::thread_add_ln700_3_fu_644_p2() {
    add_ln700_3_fu_644_p2 = (!sext_ln74_fu_592_p1.read().is_01() || !sext_ln74_1_fu_637_p1.read().is_01())? sc_lv<3>(): (sc_bigint<3>(sext_ln74_fu_592_p1.read()) + sc_bigint<3>(sext_ln74_1_fu_637_p1.read()));
}

void conv3x3b::thread_add_ln700_4_fu_654_p2() {
    add_ln700_4_fu_654_p2 = (!sext_ln700_2_fu_650_p1.read().is_01() || !sext_ln700_1_fu_641_p1.read().is_01())? sc_lv<4>(): (sc_bigint<4>(sext_ln700_2_fu_650_p1.read()) + sc_bigint<4>(sext_ln700_1_fu_641_p1.read()));
}

void conv3x3b::thread_add_ln700_5_fu_758_p2() {
    add_ln700_5_fu_758_p2 = (!sext_ln74_2_fu_709_p1.read().is_01() || !sext_ln74_3_fu_754_p1.read().is_01())? sc_lv<3>(): (sc_bigint<3>(sext_ln74_2_fu_709_p1.read()) + sc_bigint<3>(sext_ln74_3_fu_754_p1.read()));
}

void conv3x3b::thread_add_ln700_6_fu_905_p2() {
    add_ln700_6_fu_905_p2 = (!sext_ln74_5_fu_853_p1.read().is_01() || !sext_ln700_fu_895_p1.read().is_01())? sc_lv<3>(): (sc_bigint<3>(sext_ln74_5_fu_853_p1.read()) + sc_bigint<3>(sext_ln700_fu_895_p1.read()));
}

void conv3x3b::thread_add_ln700_7_fu_915_p2() {
    add_ln700_7_fu_915_p2 = (!sext_ln700_5_fu_911_p1.read().is_01() || !sext_ln74_4_fu_850_p1.read().is_01())? sc_lv<4>(): (sc_bigint<4>(sext_ln700_5_fu_911_p1.read()) + sc_bigint<4>(sext_ln74_4_fu_850_p1.read()));
}

void conv3x3b::thread_add_ln700_8_fu_925_p2() {
    add_ln700_8_fu_925_p2 = (!sext_ln700_6_fu_921_p1.read().is_01() || !sext_ln700_4_fu_902_p1.read().is_01())? sc_lv<5>(): (sc_bigint<5>(sext_ln700_6_fu_921_p1.read()) + sc_bigint<5>(sext_ln700_4_fu_902_p1.read()));
}

void conv3x3b::thread_add_ln700_fu_507_p2() {
    add_ln700_fu_507_p2 = (!sext_ln1353_fu_438_p1.read().is_01() || !sext_ln1353_1_fu_484_p1.read().is_01())? sc_lv<3>(): (sc_bigint<3>(sext_ln1353_fu_438_p1.read()) + sc_bigint<3>(sext_ln1353_1_fu_484_p1.read()));
}

void conv3x3b::thread_add_ln74_10_fu_537_p2() {
    add_ln74_10_fu_537_p2 = (!zext_ln74_10_reg_993.read().is_01() || !add_ln74_1_reg_982.read().is_01())? sc_lv<10>(): (sc_biguint<10>(zext_ln74_10_reg_993.read()) + sc_biguint<10>(add_ln74_1_reg_982.read()));
}

void conv3x3b::thread_add_ln74_11_fu_546_p2() {
    add_ln74_11_fu_546_p2 = (!zext_ln74_10_reg_993.read().is_01() || !add_ln74_2_fu_513_p2.read().is_01())? sc_lv<10>(): (sc_biguint<10>(zext_ln74_10_reg_993.read()) + sc_biguint<10>(add_ln74_2_fu_513_p2.read()));
}

void conv3x3b::thread_add_ln74_1_fu_381_p2() {
    add_ln74_1_fu_381_p2 = (!ap_const_lv10_A.is_01() || !sub_ln74_reg_942.read().is_01())? sc_lv<10>(): (sc_biguint<10>(ap_const_lv10_A) + sc_biguint<10>(sub_ln74_reg_942.read()));
}

void conv3x3b::thread_add_ln74_2_fu_513_p2() {
    add_ln74_2_fu_513_p2 = (!ap_const_lv10_14.is_01() || !sub_ln74_reg_942.read().is_01())? sc_lv<10>(): (sc_biguint<10>(ap_const_lv10_14) + sc_biguint<10>(sub_ln74_reg_942.read()));
}

void conv3x3b::thread_add_ln74_3_fu_349_p2() {
    add_ln74_3_fu_349_p2 = (!zext_ln74_2_fu_345_p1.read().is_01() || !sub_ln74_fu_339_p2.read().is_01())? sc_lv<10>(): (sc_biguint<10>(zext_ln74_2_fu_345_p1.read()) + sc_biguint<10>(sub_ln74_fu_339_p2.read()));
}

void conv3x3b::thread_add_ln74_4_fu_386_p2() {
    add_ln74_4_fu_386_p2 = (!zext_ln74_2_reg_949.read().is_01() || !add_ln74_1_fu_381_p2.read().is_01())? sc_lv<10>(): (sc_biguint<10>(zext_ln74_2_reg_949.read()) + sc_biguint<10>(add_ln74_1_fu_381_p2.read()));
}

void conv3x3b::thread_add_ln74_5_fu_518_p2() {
    add_ln74_5_fu_518_p2 = (!zext_ln74_2_reg_949.read().is_01() || !add_ln74_2_fu_513_p2.read().is_01())? sc_lv<10>(): (sc_biguint<10>(zext_ln74_2_reg_949.read()) + sc_biguint<10>(add_ln74_2_fu_513_p2.read()));
}

void conv3x3b::thread_add_ln74_6_fu_370_p2() {
    add_ln74_6_fu_370_p2 = (!zext_ln74_6_fu_366_p1.read().is_01() || !sub_ln74_fu_339_p2.read().is_01())? sc_lv<10>(): (sc_biguint<10>(zext_ln74_6_fu_366_p1.read()) + sc_biguint<10>(sub_ln74_fu_339_p2.read()));
}

void conv3x3b::thread_add_ln74_7_fu_523_p2() {
    add_ln74_7_fu_523_p2 = (!zext_ln74_6_reg_960.read().is_01() || !add_ln74_1_reg_982.read().is_01())? sc_lv<10>(): (sc_biguint<10>(zext_ln74_6_reg_960.read()) + sc_biguint<10>(add_ln74_1_reg_982.read()));
}

void conv3x3b::thread_add_ln74_8_fu_532_p2() {
    add_ln74_8_fu_532_p2 = (!zext_ln74_6_reg_960.read().is_01() || !add_ln74_2_fu_513_p2.read().is_01())? sc_lv<10>(): (sc_biguint<10>(zext_ln74_6_reg_960.read()) + sc_biguint<10>(add_ln74_2_fu_513_p2.read()));
}

void conv3x3b::thread_add_ln74_9_fu_497_p2() {
    add_ln74_9_fu_497_p2 = (!zext_ln74_10_fu_493_p1.read().is_01() || !sub_ln74_reg_942.read().is_01())? sc_lv<10>(): (sc_biguint<10>(zext_ln74_10_fu_493_p1.read()) + sc_biguint<10>(sub_ln74_reg_942.read()));
}

void conv3x3b::thread_add_ln74_fu_313_p2() {
    add_ln74_fu_313_p2 = (!zext_ln74_fu_309_p1.read().is_01() || !zext_ln74_cast_fu_305_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(zext_ln74_fu_309_p1.read()) + sc_biguint<5>(zext_ln74_cast_fu_305_p1.read()));
}

void conv3x3b::thread_and_ln1355_1_fu_454_p2() {
    and_ln1355_1_fu_454_p2 = (trunc_ln215_1_fu_442_p1.read() & select_ln215_1_fu_446_p3.read());
}

void conv3x3b::thread_and_ln1355_2_fu_562_p2() {
    and_ln1355_2_fu_562_p2 = (trunc_ln215_2_fu_551_p1.read() & select_ln215_2_fu_555_p3.read());
}

void conv3x3b::thread_and_ln1355_3_fu_607_p2() {
    and_ln1355_3_fu_607_p2 = (trunc_ln215_3_fu_596_p1.read() & select_ln215_3_fu_600_p3.read());
}

void conv3x3b::thread_and_ln1355_4_fu_679_p2() {
    and_ln1355_4_fu_679_p2 = (trunc_ln215_4_fu_668_p1.read() & select_ln215_4_fu_672_p3.read());
}

void conv3x3b::thread_and_ln1355_5_fu_724_p2() {
    and_ln1355_5_fu_724_p2 = (trunc_ln215_5_fu_713_p1.read() & select_ln215_5_fu_717_p3.read());
}

void conv3x3b::thread_and_ln1355_6_fu_779_p2() {
    and_ln1355_6_fu_779_p2 = (trunc_ln215_6_fu_768_p1.read() & select_ln215_6_fu_772_p3.read());
}

void conv3x3b::thread_and_ln1355_7_fu_820_p2() {
    and_ln1355_7_fu_820_p2 = (trunc_ln215_7_fu_809_p1.read() & select_ln215_7_fu_813_p3.read());
}

void conv3x3b::thread_and_ln1355_8_fu_865_p2() {
    and_ln1355_8_fu_865_p2 = (trunc_ln215_8_fu_856_p1.read() & select_ln215_8_fu_860_p3.read());
}

void conv3x3b::thread_and_ln1355_fu_408_p2() {
    and_ln1355_fu_408_p2 = (trunc_ln215_fu_396_p1.read() & select_ln215_fu_400_p3.read());
}

void conv3x3b::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[0];
}

void conv3x3b::thread_ap_CS_fsm_pp0_stage1() {
    ap_CS_fsm_pp0_stage1 = ap_CS_fsm.read()[1];
}

void conv3x3b::thread_ap_CS_fsm_pp0_stage2() {
    ap_CS_fsm_pp0_stage2 = ap_CS_fsm.read()[2];
}

void conv3x3b::thread_ap_CS_fsm_pp0_stage3() {
    ap_CS_fsm_pp0_stage3 = ap_CS_fsm.read()[3];
}

void conv3x3b::thread_ap_CS_fsm_pp0_stage4() {
    ap_CS_fsm_pp0_stage4 = ap_CS_fsm.read()[4];
}

void conv3x3b::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv3x3b::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()));
}

void conv3x3b::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = (esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_0) || (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())));
}

void conv3x3b::thread_ap_block_pp0_stage1() {
    ap_block_pp0_stage1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv3x3b::thread_ap_block_pp0_stage1_11001() {
    ap_block_pp0_stage1_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv3x3b::thread_ap_block_pp0_stage1_subdone() {
    ap_block_pp0_stage1_subdone = esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_0);
}

void conv3x3b::thread_ap_block_pp0_stage2() {
    ap_block_pp0_stage2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv3x3b::thread_ap_block_pp0_stage2_11001() {
    ap_block_pp0_stage2_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv3x3b::thread_ap_block_pp0_stage2_subdone() {
    ap_block_pp0_stage2_subdone = esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_0);
}

void conv3x3b::thread_ap_block_pp0_stage3() {
    ap_block_pp0_stage3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv3x3b::thread_ap_block_pp0_stage3_11001() {
    ap_block_pp0_stage3_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv3x3b::thread_ap_block_pp0_stage3_subdone() {
    ap_block_pp0_stage3_subdone = esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_0);
}

void conv3x3b::thread_ap_block_pp0_stage4() {
    ap_block_pp0_stage4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv3x3b::thread_ap_block_pp0_stage4_11001() {
    ap_block_pp0_stage4_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv3x3b::thread_ap_block_pp0_stage4_subdone() {
    ap_block_pp0_stage4_subdone = esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_0);
}

void conv3x3b::thread_ap_block_state1_pp0_stage0_iter0() {
    ap_block_state1_pp0_stage0_iter0 = esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read());
}

void conv3x3b::thread_ap_block_state2_pp0_stage1_iter0() {
    ap_block_state2_pp0_stage1_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv3x3b::thread_ap_block_state3_pp0_stage2_iter0() {
    ap_block_state3_pp0_stage2_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv3x3b::thread_ap_block_state4_pp0_stage3_iter0() {
    ap_block_state4_pp0_stage3_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv3x3b::thread_ap_block_state5_pp0_stage4_iter0() {
    ap_block_state5_pp0_stage4_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv3x3b::thread_ap_block_state6_pp0_stage0_iter1() {
    ap_block_state6_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv3x3b::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void conv3x3b::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void conv3x3b::thread_ap_enable_reg_pp0_iter0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read())) {
        ap_enable_reg_pp0_iter0 = ap_start.read();
    } else {
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg.read();
    }
}

void conv3x3b::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_idle_pp0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void conv3x3b::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void conv3x3b::thread_ap_idle_pp0_0to0() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read())) {
        ap_idle_pp0_0to0 = ap_const_logic_1;
    } else {
        ap_idle_pp0_0to0 = ap_const_logic_0;
    }
}

void conv3x3b::thread_ap_idle_pp0_1to1() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read())) {
        ap_idle_pp0_1to1 = ap_const_logic_1;
    } else {
        ap_idle_pp0_1to1 = ap_const_logic_0;
    }
}

void conv3x3b::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage4.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage4_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void conv3x3b::thread_ap_reset_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_idle_pp0_0to0.read()))) {
        ap_reset_idle_pp0 = ap_const_logic_1;
    } else {
        ap_reset_idle_pp0 = ap_const_logic_0;
    }
}

void conv3x3b::thread_ap_return() {
    ap_return = (!add_ln700_8_fu_925_p2.read().is_01() || !sext_ln700_3_fu_899_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(add_ln700_8_fu_925_p2.read()) + sc_bigint<5>(sext_ln700_3_fu_899_p1.read()));
}

void conv3x3b::thread_line_buffer_m_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage4.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage4.read(), ap_const_boolean_0))) {
            line_buffer_m_V_address0 =  (sc_lv<9>) (zext_ln74_13_fu_764_p1.read());
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage3.read(), ap_const_boolean_0))) {
            line_buffer_m_V_address0 =  (sc_lv<9>) (zext_ln74_5_fu_660_p1.read());
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage2.read(), ap_const_boolean_0))) {
            line_buffer_m_V_address0 =  (sc_lv<9>) (zext_ln74_8_fu_527_p1.read());
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0))) {
            line_buffer_m_V_address0 =  (sc_lv<9>) (zext_ln74_11_fu_502_p1.read());
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
            line_buffer_m_V_address0 =  (sc_lv<9>) (zext_ln74_3_fu_355_p1.read());
        } else {
            line_buffer_m_V_address0 = "XXXXXXXXX";
        }
    } else {
        line_buffer_m_V_address0 = "XXXXXXXXX";
    }
}

void conv3x3b::thread_line_buffer_m_V_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage3.read(), ap_const_boolean_0))) {
            line_buffer_m_V_address1 =  (sc_lv<9>) (zext_ln74_9_fu_664_p1.read());
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage2.read(), ap_const_boolean_0))) {
            line_buffer_m_V_address1 =  (sc_lv<9>) (zext_ln74_12_fu_541_p1.read());
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0))) {
            line_buffer_m_V_address1 =  (sc_lv<9>) (zext_ln74_4_fu_391_p1.read());
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
            line_buffer_m_V_address1 =  (sc_lv<9>) (zext_ln74_7_fu_376_p1.read());
        } else {
            line_buffer_m_V_address1 = "XXXXXXXXX";
        }
    } else {
        line_buffer_m_V_address1 = "XXXXXXXXX";
    }
}

void conv3x3b::thread_line_buffer_m_V_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage4.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage4_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage2_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage3_11001.read(), ap_const_boolean_0)))) {
        line_buffer_m_V_ce0 = ap_const_logic_1;
    } else {
        line_buffer_m_V_ce0 = ap_const_logic_0;
    }
}

void conv3x3b::thread_line_buffer_m_V_ce1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage2_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage3_11001.read(), ap_const_boolean_0)))) {
        line_buffer_m_V_ce1 = ap_const_logic_1;
    } else {
        line_buffer_m_V_ce1 = ap_const_logic_0;
    }
}

void conv3x3b::thread_p_shl_cast_fu_319_p3() {
    p_shl_cast_fu_319_p3 = esl_concat<5,5>(add_ln74_fu_313_p2.read(), ap_const_lv5_0);
}

void conv3x3b::thread_select_ln215_1_fu_446_p3() {
    select_ln215_1_fu_446_p3 = (!ap_port_reg_conv_params_m_V_offset.read()[0].is_01())? sc_lv<1>(): ((ap_port_reg_conv_params_m_V_offset.read()[0].to_bool())? ap_port_reg_conv_params_m_2_1_10.read(): ap_port_reg_conv_params_m_2_1_s.read());
}

void conv3x3b::thread_select_ln215_2_fu_555_p3() {
    select_ln215_2_fu_555_p3 = (!conv_params_m_V_offs_reg_971.read()[0].is_01())? sc_lv<1>(): ((conv_params_m_V_offs_reg_971.read()[0].to_bool())? ap_port_reg_conv_params_m_2_0_10.read(): ap_port_reg_conv_params_m_2_0_s.read());
}

void conv3x3b::thread_select_ln215_3_fu_600_p3() {
    select_ln215_3_fu_600_p3 = (!conv_params_m_V_offs_reg_971.read()[0].is_01())? sc_lv<1>(): ((conv_params_m_V_offs_reg_971.read()[0].to_bool())? ap_port_reg_conv_params_m_1_2_10.read(): ap_port_reg_conv_params_m_1_2_s.read());
}

void conv3x3b::thread_select_ln215_4_fu_672_p3() {
    select_ln215_4_fu_672_p3 = (!conv_params_m_V_offs_reg_971.read()[0].is_01())? sc_lv<1>(): ((conv_params_m_V_offs_reg_971.read()[0].to_bool())? ap_port_reg_conv_params_m_1_1_10.read(): ap_port_reg_conv_params_m_1_1_s.read());
}

void conv3x3b::thread_select_ln215_5_fu_717_p3() {
    select_ln215_5_fu_717_p3 = (!conv_params_m_V_offs_reg_971.read()[0].is_01())? sc_lv<1>(): ((conv_params_m_V_offs_reg_971.read()[0].to_bool())? ap_port_reg_conv_params_m_1_0_10.read(): ap_port_reg_conv_params_m_1_0_s.read());
}

void conv3x3b::thread_select_ln215_6_fu_772_p3() {
    select_ln215_6_fu_772_p3 = (!conv_params_m_V_offs_reg_971.read()[0].is_01())? sc_lv<1>(): ((conv_params_m_V_offs_reg_971.read()[0].to_bool())? ap_port_reg_conv_params_m_0_2_10.read(): ap_port_reg_conv_params_m_0_2_s.read());
}

void conv3x3b::thread_select_ln215_7_fu_813_p3() {
    select_ln215_7_fu_813_p3 = (!conv_params_m_V_offs_reg_971.read()[0].is_01())? sc_lv<1>(): ((conv_params_m_V_offs_reg_971.read()[0].to_bool())? ap_port_reg_conv_params_m_0_1_10.read(): ap_port_reg_conv_params_m_0_1_s.read());
}

void conv3x3b::thread_select_ln215_8_fu_860_p3() {
    select_ln215_8_fu_860_p3 = (!conv_params_m_V_offs_reg_971.read()[0].is_01())? sc_lv<1>(): ((conv_params_m_V_offs_reg_971.read()[0].to_bool())? conv_params_m_0_0_11_reg_1054.read(): conv_params_m_0_0_12_reg_1059.read());
}

void conv3x3b::thread_select_ln215_fu_400_p3() {
    select_ln215_fu_400_p3 = (!ap_port_reg_conv_params_m_V_offset.read()[0].is_01())? sc_lv<1>(): ((ap_port_reg_conv_params_m_V_offset.read()[0].to_bool())? ap_port_reg_conv_params_m_2_2_10.read(): ap_port_reg_conv_params_m_2_2_s.read());
}

void conv3x3b::thread_sext_ln1353_1_fu_484_p1() {
    sext_ln1353_1_fu_484_p1 = esl_sext<3,2>(tmp_58_fu_474_p4.read());
}

void conv3x3b::thread_sext_ln1353_fu_438_p1() {
    sext_ln1353_fu_438_p1 = esl_sext<3,2>(tmp_56_fu_428_p4.read());
}

void conv3x3b::thread_sext_ln700_1_fu_641_p1() {
    sext_ln700_1_fu_641_p1 = esl_sext<4,3>(add_ln700_reg_1004.read());
}

void conv3x3b::thread_sext_ln700_2_fu_650_p1() {
    sext_ln700_2_fu_650_p1 = esl_sext<4,3>(add_ln700_3_fu_644_p2.read());
}

void conv3x3b::thread_sext_ln700_3_fu_899_p1() {
    sext_ln700_3_fu_899_p1 = esl_sext<5,4>(add_ln700_4_reg_1034.read());
}

void conv3x3b::thread_sext_ln700_4_fu_902_p1() {
    sext_ln700_4_fu_902_p1 = esl_sext<5,3>(add_ln700_5_reg_1049.read());
}

void conv3x3b::thread_sext_ln700_5_fu_911_p1() {
    sext_ln700_5_fu_911_p1 = esl_sext<4,3>(add_ln700_6_fu_905_p2.read());
}

void conv3x3b::thread_sext_ln700_6_fu_921_p1() {
    sext_ln700_6_fu_921_p1 = esl_sext<5,4>(add_ln700_7_fu_915_p2.read());
}

void conv3x3b::thread_sext_ln700_fu_895_p1() {
    sext_ln700_fu_895_p1 = esl_sext<3,2>(tmp_72_fu_885_p4.read());
}

void conv3x3b::thread_sext_ln74_1_fu_637_p1() {
    sext_ln74_1_fu_637_p1 = esl_sext<3,2>(tmp_62_fu_627_p4.read());
}

void conv3x3b::thread_sext_ln74_2_fu_709_p1() {
    sext_ln74_2_fu_709_p1 = esl_sext<3,2>(tmp_64_fu_699_p4.read());
}

void conv3x3b::thread_sext_ln74_3_fu_754_p1() {
    sext_ln74_3_fu_754_p1 = esl_sext<3,2>(tmp_66_fu_744_p4.read());
}

void conv3x3b::thread_sext_ln74_4_fu_850_p1() {
    sext_ln74_4_fu_850_p1 = esl_sext<4,2>(tmp_68_reg_1069.read());
}

void conv3x3b::thread_sext_ln74_5_fu_853_p1() {
    sext_ln74_5_fu_853_p1 = esl_sext<3,2>(tmp_70_reg_1074.read());
}

void conv3x3b::thread_sext_ln74_fu_592_p1() {
    sext_ln74_fu_592_p1 = esl_sext<3,2>(tmp_60_fu_582_p4.read());
}

void conv3x3b::thread_sub_ln74_fu_339_p2() {
    sub_ln74_fu_339_p2 = (!p_shl_cast_fu_319_p3.read().is_01() || !zext_ln74_1_fu_335_p1.read().is_01())? sc_lv<10>(): (sc_biguint<10>(p_shl_cast_fu_319_p3.read()) - sc_biguint<10>(zext_ln74_1_fu_335_p1.read()));
}

void conv3x3b::thread_tmp_54_fu_327_p3() {
    tmp_54_fu_327_p3 = esl_concat<5,1>(add_ln74_fu_313_p2.read(), ap_const_lv1_0);
}

void conv3x3b::thread_tmp_55_fu_414_p3() {
    tmp_55_fu_414_p3 = line_buffer_m_V_q0.read().range(1, 1);
}

void conv3x3b::thread_tmp_56_fu_428_p4() {
    tmp_56_fu_428_p4 = esl_bitset<2,2,32,1>(line_buffer_m_V_q0.read(), ap_const_lv32_1, xor_ln841_fu_422_p2.read());
}

void conv3x3b::thread_tmp_57_fu_460_p3() {
    tmp_57_fu_460_p3 = line_buffer_m_V_q1.read().range(1, 1);
}

void conv3x3b::thread_tmp_58_fu_474_p4() {
    tmp_58_fu_474_p4 = esl_bitset<2,2,32,1>(line_buffer_m_V_q1.read(), ap_const_lv32_1, xor_ln841_1_fu_468_p2.read());
}

void conv3x3b::thread_tmp_59_fu_568_p3() {
    tmp_59_fu_568_p3 = line_buffer_m_V_q0.read().range(1, 1);
}

void conv3x3b::thread_tmp_60_fu_582_p4() {
    tmp_60_fu_582_p4 = esl_bitset<2,2,32,1>(line_buffer_m_V_q0.read(), ap_const_lv32_1, xor_ln841_2_fu_576_p2.read());
}

void conv3x3b::thread_tmp_61_fu_613_p3() {
    tmp_61_fu_613_p3 = line_buffer_m_V_q1.read().range(1, 1);
}

void conv3x3b::thread_tmp_62_fu_627_p4() {
    tmp_62_fu_627_p4 = esl_bitset<2,2,32,1>(line_buffer_m_V_q1.read(), ap_const_lv32_1, xor_ln841_3_fu_621_p2.read());
}

void conv3x3b::thread_tmp_63_fu_685_p3() {
    tmp_63_fu_685_p3 = line_buffer_m_V_q0.read().range(1, 1);
}

void conv3x3b::thread_tmp_64_fu_699_p4() {
    tmp_64_fu_699_p4 = esl_bitset<2,2,32,1>(line_buffer_m_V_q0.read(), ap_const_lv32_1, xor_ln841_4_fu_693_p2.read());
}

void conv3x3b::thread_tmp_65_fu_730_p3() {
    tmp_65_fu_730_p3 = line_buffer_m_V_q1.read().range(1, 1);
}

void conv3x3b::thread_tmp_66_fu_744_p4() {
    tmp_66_fu_744_p4 = esl_bitset<2,2,32,1>(line_buffer_m_V_q1.read(), ap_const_lv32_1, xor_ln841_5_fu_738_p2.read());
}

void conv3x3b::thread_tmp_67_fu_785_p3() {
    tmp_67_fu_785_p3 = line_buffer_m_V_q0.read().range(1, 1);
}

void conv3x3b::thread_tmp_68_fu_799_p4() {
    tmp_68_fu_799_p4 = esl_bitset<2,2,32,1>(line_buffer_m_V_q0.read(), ap_const_lv32_1, xor_ln841_6_fu_793_p2.read());
}

void conv3x3b::thread_tmp_69_fu_826_p3() {
    tmp_69_fu_826_p3 = line_buffer_m_V_q1.read().range(1, 1);
}

void conv3x3b::thread_tmp_70_fu_840_p4() {
    tmp_70_fu_840_p4 = esl_bitset<2,2,32,1>(line_buffer_m_V_q1.read(), ap_const_lv32_1, xor_ln841_7_fu_834_p2.read());
}

void conv3x3b::thread_tmp_71_fu_871_p3() {
    tmp_71_fu_871_p3 = line_buffer_m_V_q0.read().range(1, 1);
}

void conv3x3b::thread_tmp_72_fu_885_p4() {
    tmp_72_fu_885_p4 = esl_bitset<2,2,32,1>(line_buffer_m_V_q0.read(), ap_const_lv32_1, xor_ln841_8_fu_879_p2.read());
}

void conv3x3b::thread_tmp_fu_297_p3() {
    tmp_fu_297_p3 = esl_concat<1,3>(line_buffer_m_V_offset.read(), ap_const_lv3_0);
}

void conv3x3b::thread_trunc_ln215_1_fu_442_p1() {
    trunc_ln215_1_fu_442_p1 = line_buffer_m_V_q1.read().range(1-1, 0);
}

void conv3x3b::thread_trunc_ln215_2_fu_551_p1() {
    trunc_ln215_2_fu_551_p1 = line_buffer_m_V_q0.read().range(1-1, 0);
}

void conv3x3b::thread_trunc_ln215_3_fu_596_p1() {
    trunc_ln215_3_fu_596_p1 = line_buffer_m_V_q1.read().range(1-1, 0);
}

void conv3x3b::thread_trunc_ln215_4_fu_668_p1() {
    trunc_ln215_4_fu_668_p1 = line_buffer_m_V_q0.read().range(1-1, 0);
}

void conv3x3b::thread_trunc_ln215_5_fu_713_p1() {
    trunc_ln215_5_fu_713_p1 = line_buffer_m_V_q1.read().range(1-1, 0);
}

void conv3x3b::thread_trunc_ln215_6_fu_768_p1() {
    trunc_ln215_6_fu_768_p1 = line_buffer_m_V_q0.read().range(1-1, 0);
}

void conv3x3b::thread_trunc_ln215_7_fu_809_p1() {
    trunc_ln215_7_fu_809_p1 = line_buffer_m_V_q1.read().range(1-1, 0);
}

void conv3x3b::thread_trunc_ln215_8_fu_856_p1() {
    trunc_ln215_8_fu_856_p1 = line_buffer_m_V_q0.read().range(1-1, 0);
}

void conv3x3b::thread_trunc_ln215_fu_396_p1() {
    trunc_ln215_fu_396_p1 = line_buffer_m_V_q0.read().range(1-1, 0);
}

void conv3x3b::thread_xor_ln841_1_fu_468_p2() {
    xor_ln841_1_fu_468_p2 = (and_ln1355_1_fu_454_p2.read() ^ tmp_57_fu_460_p3.read());
}

void conv3x3b::thread_xor_ln841_2_fu_576_p2() {
    xor_ln841_2_fu_576_p2 = (and_ln1355_2_fu_562_p2.read() ^ tmp_59_fu_568_p3.read());
}

void conv3x3b::thread_xor_ln841_3_fu_621_p2() {
    xor_ln841_3_fu_621_p2 = (and_ln1355_3_fu_607_p2.read() ^ tmp_61_fu_613_p3.read());
}

void conv3x3b::thread_xor_ln841_4_fu_693_p2() {
    xor_ln841_4_fu_693_p2 = (and_ln1355_4_fu_679_p2.read() ^ tmp_63_fu_685_p3.read());
}

void conv3x3b::thread_xor_ln841_5_fu_738_p2() {
    xor_ln841_5_fu_738_p2 = (and_ln1355_5_fu_724_p2.read() ^ tmp_65_fu_730_p3.read());
}

void conv3x3b::thread_xor_ln841_6_fu_793_p2() {
    xor_ln841_6_fu_793_p2 = (and_ln1355_6_fu_779_p2.read() ^ tmp_67_fu_785_p3.read());
}

void conv3x3b::thread_xor_ln841_7_fu_834_p2() {
    xor_ln841_7_fu_834_p2 = (and_ln1355_7_fu_820_p2.read() ^ tmp_69_fu_826_p3.read());
}

void conv3x3b::thread_xor_ln841_8_fu_879_p2() {
    xor_ln841_8_fu_879_p2 = (and_ln1355_8_fu_865_p2.read() ^ tmp_71_fu_871_p3.read());
}

void conv3x3b::thread_xor_ln841_fu_422_p2() {
    xor_ln841_fu_422_p2 = (and_ln1355_fu_408_p2.read() ^ tmp_55_fu_414_p3.read());
}

void conv3x3b::thread_zext_ln74_10_fu_493_p1() {
    zext_ln74_10_fu_493_p1 = esl_zext<10,4>(add_ln1353_14_fu_488_p2.read());
}

void conv3x3b::thread_zext_ln74_11_fu_502_p1() {
    zext_ln74_11_fu_502_p1 = esl_zext<64,10>(add_ln74_9_fu_497_p2.read());
}

void conv3x3b::thread_zext_ln74_12_fu_541_p1() {
    zext_ln74_12_fu_541_p1 = esl_zext<64,10>(add_ln74_10_fu_537_p2.read());
}

void conv3x3b::thread_zext_ln74_13_fu_764_p1() {
    zext_ln74_13_fu_764_p1 = esl_zext<64,10>(add_ln74_11_reg_1029.read());
}

void conv3x3b::thread_zext_ln74_1_fu_335_p1() {
    zext_ln74_1_fu_335_p1 = esl_zext<10,6>(tmp_54_fu_327_p3.read());
}

void conv3x3b::thread_zext_ln74_2_fu_345_p1() {
    zext_ln74_2_fu_345_p1 = esl_zext<10,4>(cc_V.read());
}

void conv3x3b::thread_zext_ln74_3_fu_355_p1() {
    zext_ln74_3_fu_355_p1 = esl_zext<64,10>(add_ln74_3_fu_349_p2.read());
}

void conv3x3b::thread_zext_ln74_4_fu_391_p1() {
    zext_ln74_4_fu_391_p1 = esl_zext<64,10>(add_ln74_4_fu_386_p2.read());
}

void conv3x3b::thread_zext_ln74_5_fu_660_p1() {
    zext_ln74_5_fu_660_p1 = esl_zext<64,10>(add_ln74_5_reg_1009.read());
}

void conv3x3b::thread_zext_ln74_6_fu_366_p1() {
    zext_ln74_6_fu_366_p1 = esl_zext<10,4>(add_ln1353_fu_360_p2.read());
}

void conv3x3b::thread_zext_ln74_7_fu_376_p1() {
    zext_ln74_7_fu_376_p1 = esl_zext<64,10>(add_ln74_6_fu_370_p2.read());
}

void conv3x3b::thread_zext_ln74_8_fu_527_p1() {
    zext_ln74_8_fu_527_p1 = esl_zext<64,10>(add_ln74_7_fu_523_p2.read());
}

void conv3x3b::thread_zext_ln74_9_fu_664_p1() {
    zext_ln74_9_fu_664_p1 = esl_zext<64,10>(add_ln74_8_reg_1019.read());
}

void conv3x3b::thread_zext_ln74_cast_fu_305_p1() {
    zext_ln74_cast_fu_305_p1 = esl_zext<5,4>(tmp_fu_297_p3.read());
}

void conv3x3b::thread_zext_ln74_fu_309_p1() {
    zext_ln74_fu_309_p1 = esl_zext<5,4>(bank_V.read());
}

void conv3x3b::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_reset_idle_pp0.read(), ap_const_logic_0) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_idle_pp0_1to1.read())))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            } else if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reset_idle_pp0.read()))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 2 : 
            if (esl_seteq<1,1,1>(ap_block_pp0_stage1_subdone.read(), ap_const_boolean_0)) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            }
            break;
        case 4 : 
            if (esl_seteq<1,1,1>(ap_block_pp0_stage2_subdone.read(), ap_const_boolean_0)) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            }
            break;
        case 8 : 
            if (esl_seteq<1,1,1>(ap_block_pp0_stage3_subdone.read(), ap_const_boolean_0)) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            }
            break;
        case 16 : 
            if (esl_seteq<1,1,1>(ap_block_pp0_stage4_subdone.read(), ap_const_boolean_0)) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            }
            break;
        default : 
            ap_NS_fsm =  (sc_lv<5>) ("XXXXX");
            break;
    }
}

}

