// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "top.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic top::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic top::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<12> top::ap_ST_fsm_state1 = "1";
const sc_lv<12> top::ap_ST_fsm_pp0_stage0 = "10";
const sc_lv<12> top::ap_ST_fsm_state4 = "100";
const sc_lv<12> top::ap_ST_fsm_pp1_stage0 = "1000";
const sc_lv<12> top::ap_ST_fsm_state7 = "10000";
const sc_lv<12> top::ap_ST_fsm_pp2_stage0 = "100000";
const sc_lv<12> top::ap_ST_fsm_state10 = "1000000";
const sc_lv<12> top::ap_ST_fsm_state11 = "10000000";
const sc_lv<12> top::ap_ST_fsm_state12 = "100000000";
const sc_lv<12> top::ap_ST_fsm_state13 = "1000000000";
const sc_lv<12> top::ap_ST_fsm_state14 = "10000000000";
const sc_lv<12> top::ap_ST_fsm_state15 = "100000000000";
const sc_lv<32> top::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool top::ap_const_boolean_1 = true;
const sc_lv<16> top::ap_const_lv16_0 = "0000000000000000";
const sc_lv<32> top::ap_const_lv32_1 = "1";
const bool top::ap_const_boolean_0 = false;
const sc_lv<1> top::ap_const_lv1_0 = "0";
const sc_lv<1> top::ap_const_lv1_1 = "1";
const sc_lv<32> top::ap_const_lv32_3 = "11";
const sc_lv<32> top::ap_const_lv32_5 = "101";
const sc_lv<32> top::ap_const_lv32_6 = "110";
const sc_lv<32> top::ap_const_lv32_8 = "1000";
const sc_lv<32> top::ap_const_lv32_9 = "1001";
const sc_lv<32> top::ap_const_lv32_A = "1010";
const sc_lv<32> top::ap_const_lv32_2 = "10";
const sc_lv<32> top::ap_const_lv32_4 = "100";
const sc_lv<10> top::ap_const_lv10_0 = "0000000000";
const sc_lv<7> top::ap_const_lv7_0 = "0000000";
const sc_lv<13> top::ap_const_lv13_0 = "0000000000000";
const sc_lv<32> top::ap_const_lv32_7 = "111";
const sc_lv<16> top::ap_const_lv16_1 = "1";
const sc_lv<64> top::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<6> top::ap_const_lv6_0 = "000000";
const sc_lv<32> top::ap_const_lv32_B = "1011";
const sc_lv<5> top::ap_const_lv5_1 = "1";
const sc_lv<2> top::ap_const_lv2_1 = "1";
const sc_lv<2> top::ap_const_lv2_0 = "00";
const sc_lv<7> top::ap_const_lv7_40 = "1000000";
const sc_lv<7> top::ap_const_lv7_1 = "1";
const sc_lv<32> top::ap_const_lv32_F = "1111";
const sc_lv<10> top::ap_const_lv10_1 = "1";
const sc_lv<3> top::ap_const_lv3_0 = "000";
const sc_lv<5> top::ap_const_lv5_0 = "00000";
const sc_lv<13> top::ap_const_lv13_124A = "1001001001010";
const sc_lv<13> top::ap_const_lv13_1 = "1";
const sc_lv<32> top::ap_const_lv32_C = "1100";
const sc_lv<13> top::ap_const_lv13_925 = "100100100101";
const sc_lv<32> top::ap_const_lv32_10 = "10000";
const sc_lv<32> top::ap_const_lv32_1F = "11111";
const sc_lv<32> top::ap_const_lv32_30 = "110000";
const sc_lv<32> top::ap_const_lv32_3F = "111111";
const sc_lv<16> top::ap_const_lv16_2 = "10";
const sc_lv<11> top::ap_const_lv11_0 = "00000000000";

top::top(sc_module_name name) : sc_module(name), mVcdFile(0) {
    dmem_V_U = new top_dmem_V("dmem_V_U");
    dmem_V_U->clk(ap_clk);
    dmem_V_U->reset(ap_rst);
    dmem_V_U->address0(dmem_V_address0);
    dmem_V_U->ce0(dmem_V_ce0);
    dmem_V_U->we0(dmem_V_we0);
    dmem_V_U->d0(dmem_V_d0);
    dmem_V_U->q0(dmem_V_q0);
    wt_mem_V_U = new top_wt_mem_V("wt_mem_V_U");
    wt_mem_V_U->clk(ap_clk);
    wt_mem_V_U->reset(ap_rst);
    wt_mem_V_U->address0(wt_mem_V_address0);
    wt_mem_V_U->ce0(wt_mem_V_ce0);
    wt_mem_V_U->we0(wt_mem_V_we0);
    wt_mem_V_U->d0(wt_i_V_q0);
    wt_mem_V_U->q0(wt_mem_V_q0);
    kh_mem_V_U = new top_kh_mem_V("kh_mem_V_U");
    kh_mem_V_U->clk(ap_clk);
    kh_mem_V_U->reset(ap_rst);
    kh_mem_V_U->address0(kh_mem_V_address0);
    kh_mem_V_U->ce0(kh_mem_V_ce0);
    kh_mem_V_U->we0(kh_mem_V_we0);
    kh_mem_V_U->d0(kh_i_V_q0);
    kh_mem_V_U->q0(kh_mem_V_q0);
    grp_bin_conv_fu_407 = new bin_conv("grp_bin_conv_fu_407");
    grp_bin_conv_fu_407->ap_clk(ap_clk);
    grp_bin_conv_fu_407->ap_rst(ap_rst);
    grp_bin_conv_fu_407->ap_start(grp_bin_conv_fu_407_ap_start);
    grp_bin_conv_fu_407->ap_done(grp_bin_conv_fu_407_ap_done);
    grp_bin_conv_fu_407->ap_idle(grp_bin_conv_fu_407_ap_idle);
    grp_bin_conv_fu_407->ap_ready(grp_bin_conv_fu_407_ap_ready);
    grp_bin_conv_fu_407->wt_mem_V_4_address0(grp_bin_conv_fu_407_wt_mem_V_4_address0);
    grp_bin_conv_fu_407->wt_mem_V_4_ce0(grp_bin_conv_fu_407_wt_mem_V_4_ce0);
    grp_bin_conv_fu_407->wt_mem_V_4_q0(wt_mem_V_q0);
    grp_bin_conv_fu_407->nc_V(nc_V_reg_1047);
    grp_bin_conv_fu_407->dmem_V_4_address0(grp_bin_conv_fu_407_dmem_V_4_address0);
    grp_bin_conv_fu_407->dmem_V_4_ce0(grp_bin_conv_fu_407_dmem_V_4_ce0);
    grp_bin_conv_fu_407->dmem_V_4_we0(grp_bin_conv_fu_407_dmem_V_4_we0);
    grp_bin_conv_fu_407->dmem_V_4_d0(grp_bin_conv_fu_407_dmem_V_4_d0);
    grp_bin_conv_fu_407->dmem_V_4_q0(dmem_V_q0);
    grp_bin_conv_fu_407->d_i_idx_V(dmem_mode_V);
    grp_bin_conv_fu_407->d_o_idx_V(r_V_2_reg_925);
    grp_bin_conv_fu_407->o_index_V_4(t_V_1_reg_918);
    grp_bin_conv_fu_407->width_mode_V(width_mode_V);
    grp_bin_conv_fu_407->norm_mode_V(norm_mode_V);
    grp_bin_dense_fu_423 = new bin_dense("grp_bin_dense_fu_423");
    grp_bin_dense_fu_423->ap_clk(ap_clk);
    grp_bin_dense_fu_423->ap_rst(ap_rst);
    grp_bin_dense_fu_423->ap_start(grp_bin_dense_fu_423_ap_start);
    grp_bin_dense_fu_423->ap_done(grp_bin_dense_fu_423_ap_done);
    grp_bin_dense_fu_423->ap_idle(grp_bin_dense_fu_423_ap_idle);
    grp_bin_dense_fu_423->ap_ready(grp_bin_dense_fu_423_ap_ready);
    grp_bin_dense_fu_423->wt_mem_V_2_address0(grp_bin_dense_fu_423_wt_mem_V_2_address0);
    grp_bin_dense_fu_423->wt_mem_V_2_ce0(grp_bin_dense_fu_423_wt_mem_V_2_ce0);
    grp_bin_dense_fu_423->wt_mem_V_2_q0(wt_mem_V_q0);
    grp_bin_dense_fu_423->kh_mem_V_2_address0(grp_bin_dense_fu_423_kh_mem_V_2_address0);
    grp_bin_dense_fu_423->kh_mem_V_2_ce0(grp_bin_dense_fu_423_kh_mem_V_2_ce0);
    grp_bin_dense_fu_423->kh_mem_V_2_q0(kh_mem_V_q0);
    grp_bin_dense_fu_423->dmem_V_2_address0(grp_bin_dense_fu_423_dmem_V_2_address0);
    grp_bin_dense_fu_423->dmem_V_2_ce0(grp_bin_dense_fu_423_dmem_V_2_ce0);
    grp_bin_dense_fu_423->dmem_V_2_we0(grp_bin_dense_fu_423_dmem_V_2_we0);
    grp_bin_dense_fu_423->dmem_V_2_d0(grp_bin_dense_fu_423_dmem_V_2_d0);
    grp_bin_dense_fu_423->dmem_V_2_q0(dmem_V_q0);
    grp_bin_dense_fu_423->layer_type_V(layer_type_V_reg_891);
    grp_bin_dense_fu_423->d_i_idx_V(dmem_mode_V);
    grp_bin_dense_fu_423->d_o_idx_V(r_V_2_reg_925);
    grp_bin_dense_fu_423->o_index_V_2(t_V_1_reg_918);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln180_1_fu_738_p2);
    sensitive << ( select_ln180_fu_730_p3 );
    sensitive << ( zext_ln1372_fu_726_p1 );

    SC_METHOD(thread_add_ln180_2_fu_602_p2);
    sensitive << ( trunc_ln180_fu_594_p1 );
    sensitive << ( zext_ln180_fu_598_p1 );

    SC_METHOD(thread_add_ln180_fu_621_p2);
    sensitive << ( add_ln180_2_fu_602_p2 );
    sensitive << ( zext_ln180_4_fu_617_p1 );

    SC_METHOD(thread_add_ln700_6_fu_831_p2);
    sensitive << ( t_V_1_reg_918 );
    sensitive << ( n_outputs_V_pn_reg_394 );

    SC_METHOD(thread_add_ln700_fu_770_p2);
    sensitive << ( n_outputs_V );
    sensitive << ( zext_ln758_reg_912 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp1_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp2_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state15);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);

    SC_METHOD(thread_ap_block_pp1_stage0);

    SC_METHOD(thread_ap_block_pp1_stage0_11001);

    SC_METHOD(thread_ap_block_pp1_stage0_subdone);

    SC_METHOD(thread_ap_block_pp2_stage0);

    SC_METHOD(thread_ap_block_pp2_stage0_11001);

    SC_METHOD(thread_ap_block_pp2_stage0_subdone);

    SC_METHOD(thread_ap_block_state13_on_subcall_done);
    sensitive << ( grp_bin_conv_fu_407_ap_done );
    sensitive << ( ap_predicate_op171_call_state13 );

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state5_pp1_stage0_iter0);

    SC_METHOD(thread_ap_block_state6_pp1_stage0_iter1);

    SC_METHOD(thread_ap_block_state8_pp2_stage0_iter0);

    SC_METHOD(thread_ap_block_state9_pp2_stage0_iter1);

    SC_METHOD(thread_ap_condition_796);
    sensitive << ( icmp_ln887_fu_531_p2 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state2);
    sensitive << ( icmp_ln887_fu_531_p2 );

    SC_METHOD(thread_ap_condition_pp1_exit_iter0_state5);
    sensitive << ( icmp_ln887_1_fu_700_p2 );

    SC_METHOD(thread_ap_condition_pp2_exit_iter0_state8);
    sensitive << ( icmp_ln887_2_fu_753_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state15 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_enable_pp1);
    sensitive << ( ap_idle_pp1 );

    SC_METHOD(thread_ap_enable_pp2);
    sensitive << ( ap_idle_pp2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_ap_idle_pp1);
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );

    SC_METHOD(thread_ap_idle_pp2);
    sensitive << ( ap_enable_reg_pp2_iter0 );
    sensitive << ( ap_enable_reg_pp2_iter1 );

    SC_METHOD(thread_ap_predicate_op171_call_state13);
    sensitive << ( icmp_ln879_reg_937 );
    sensitive << ( icmp_ln879_1_reg_946 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state15 );

    SC_METHOD(thread_dmem_V_address0);
    sensitive << ( icmp_ln879_reg_937 );
    sensitive << ( icmp_ln879_1_reg_946 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_predicate_op171_call_state13 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( grp_bin_conv_fu_407_dmem_V_4_address0 );
    sensitive << ( grp_bin_dense_fu_423_dmem_V_2_address0 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln180_2_fu_678_p1 );
    sensitive << ( zext_ln180_1_fu_691_p1 );
    sensitive << ( zext_ln180_5_fu_696_p1 );
    sensitive << ( zext_ln180_3_fu_843_p1 );

    SC_METHOD(thread_dmem_V_ce0);
    sensitive << ( icmp_ln879_reg_937 );
    sensitive << ( icmp_ln879_1_reg_946 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_predicate_op171_call_state13 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( grp_bin_conv_fu_407_dmem_V_4_ce0 );
    sensitive << ( grp_bin_dense_fu_423_dmem_V_2_ce0 );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_dmem_V_d0);
    sensitive << ( dmem_i_V_q0 );
    sensitive << ( icmp_ln879_reg_937 );
    sensitive << ( icmp_ln879_1_reg_946 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_predicate_op171_call_state13 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( grp_bin_conv_fu_407_dmem_V_4_d0 );
    sensitive << ( grp_bin_dense_fu_423_dmem_V_2_d0 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_dmem_V_we0);
    sensitive << ( icmp_ln879_reg_937 );
    sensitive << ( icmp_ln879_1_reg_946 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_predicate_op171_call_state13 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( grp_bin_conv_fu_407_dmem_V_4_we0 );
    sensitive << ( grp_bin_dense_fu_423_dmem_V_2_we0 );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_dmem_i_V_address0);
    sensitive << ( icmp_ln879_reg_937 );
    sensitive << ( icmp_ln879_1_reg_946 );
    sensitive << ( zext_ln544_3_fu_565_p1 );
    sensitive << ( zext_ln544_2_fu_570_p1 );
    sensitive << ( zext_ln544_fu_627_p1 );
    sensitive << ( ap_condition_796 );

    SC_METHOD(thread_dmem_i_V_ce0);
    sensitive << ( icmp_ln879_reg_937 );
    sensitive << ( icmp_ln879_1_reg_946 );
    sensitive << ( icmp_ln887_fu_531_p2 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_dmem_o_V_address0);
    sensitive << ( ap_CS_fsm_state15 );

    SC_METHOD(thread_dmem_o_V_ce0);
    sensitive << ( ap_CS_fsm_state15 );

    SC_METHOD(thread_dmem_o_V_d0);
    sensitive << ( dmem_V_q0 );
    sensitive << ( ap_CS_fsm_state15 );

    SC_METHOD(thread_dmem_o_V_we0);
    sensitive << ( ap_CS_fsm_state15 );

    SC_METHOD(thread_grp_bin_conv_fu_407_ap_start);
    sensitive << ( grp_bin_conv_fu_407_ap_start_reg );

    SC_METHOD(thread_grp_bin_dense_fu_423_ap_start);
    sensitive << ( grp_bin_dense_fu_423_ap_start_reg );

    SC_METHOD(thread_i_V_1_fu_759_p2);
    sensitive << ( p_0584_0_reg_372 );

    SC_METHOD(thread_i_V_2_fu_537_p2);
    sensitive << ( p_0218_0_reg_350 );

    SC_METHOD(thread_i_V_fu_706_p2);
    sensitive << ( p_0481_0_reg_361 );

    SC_METHOD(thread_icmp_ln879_1_fu_525_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( layer_type_V_fu_437_p4 );

    SC_METHOD(thread_icmp_ln879_2_fu_638_p2);
    sensitive << ( zext_ln879_reg_941 );
    sensitive << ( icmp_ln887_fu_531_p2 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( img_off_V_fu_632_p2 );

    SC_METHOD(thread_icmp_ln879_fu_515_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( layer_type_V_fu_437_p4 );

    SC_METHOD(thread_icmp_ln887_1_fu_700_p2);
    sensitive << ( p_0481_0_reg_361 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );

    SC_METHOD(thread_icmp_ln887_2_fu_753_p2);
    sensitive << ( p_0584_0_reg_372 );
    sensitive << ( ap_CS_fsm_pp2_stage0 );
    sensitive << ( ap_block_pp2_stage0_11001 );
    sensitive << ( ap_enable_reg_pp2_iter0 );

    SC_METHOD(thread_icmp_ln887_fu_531_p2);
    sensitive << ( p_0218_0_reg_350 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_img_idx_V_fu_643_p2);
    sensitive << ( p_0700_0_reg_328 );

    SC_METHOD(thread_img_off_V_fu_632_p2);
    sensitive << ( p_0868_0_reg_339 );

    SC_METHOD(thread_kh_i_V_address0);
    sensitive << ( ap_CS_fsm_pp2_stage0 );
    sensitive << ( ap_enable_reg_pp2_iter0 );
    sensitive << ( zext_ln544_4_fu_765_p1 );
    sensitive << ( ap_block_pp2_stage0 );

    SC_METHOD(thread_kh_i_V_ce0);
    sensitive << ( ap_CS_fsm_pp2_stage0 );
    sensitive << ( ap_block_pp2_stage0_11001 );
    sensitive << ( ap_enable_reg_pp2_iter0 );

    SC_METHOD(thread_kh_mem_V_address0);
    sensitive << ( icmp_ln879_reg_937 );
    sensitive << ( icmp_ln879_1_reg_946 );
    sensitive << ( ap_CS_fsm_pp2_stage0 );
    sensitive << ( zext_ln544_4_reg_1032 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_enable_reg_pp2_iter1 );
    sensitive << ( grp_bin_dense_fu_423_kh_mem_V_2_address0 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_block_pp2_stage0 );

    SC_METHOD(thread_kh_mem_V_ce0);
    sensitive << ( icmp_ln879_reg_937 );
    sensitive << ( icmp_ln879_1_reg_946 );
    sensitive << ( ap_CS_fsm_pp2_stage0 );
    sensitive << ( ap_block_pp2_stage0_11001 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_enable_reg_pp2_iter1 );
    sensitive << ( grp_bin_dense_fu_423_kh_mem_V_2_ce0 );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_kh_mem_V_we0);
    sensitive << ( icmp_ln887_2_reg_1023 );
    sensitive << ( ap_CS_fsm_pp2_stage0 );
    sensitive << ( ap_block_pp2_stage0_11001 );
    sensitive << ( ap_enable_reg_pp2_iter1 );

    SC_METHOD(thread_layer_type_V_fu_437_p4);
    sensitive << ( layer_mode_V );

    SC_METHOD(thread_nc_V_fu_816_p3);
    sensitive << ( t_V_reg_906 );
    sensitive << ( tmp_V_1_fu_788_p4 );
    sensitive << ( select_ln879_fu_808_p3 );

    SC_METHOD(thread_or_ln879_fu_779_p2);
    sensitive << ( trunc_ln792_reg_896 );
    sensitive << ( xor_ln879_fu_774_p2 );

    SC_METHOD(thread_p_Result_s_fu_451_p2);
    sensitive << ( trunc_ln792_fu_447_p1 );

    SC_METHOD(thread_r_V_2_fu_487_p2);
    sensitive << ( dmem_mode_V );

    SC_METHOD(thread_r_V_fu_589_p2);
    sensitive << ( zext_ln769_reg_932 );
    sensitive << ( ret_V_8_fu_585_p1 );

    SC_METHOD(thread_ret_V_3_fu_551_p1);
    sensitive << ( p_0218_0_reg_350 );

    SC_METHOD(thread_ret_V_4_fu_665_p1);
    sensitive << ( ret_V_6_reg_969 );

    SC_METHOD(thread_ret_V_5_fu_547_p1);
    sensitive << ( p_0218_0_reg_350 );

    SC_METHOD(thread_ret_V_7_fu_543_p1);
    sensitive << ( p_0700_0_reg_328 );

    SC_METHOD(thread_ret_V_8_fu_585_p1);
    sensitive << ( ret_V_9_fu_575_p4 );

    SC_METHOD(thread_ret_V_9_fu_575_p4);
    sensitive << ( p_0700_0_reg_328 );

    SC_METHOD(thread_ret_V_fu_712_p1);
    sensitive << ( p_0481_0_reg_361 );

    SC_METHOD(thread_select_ln180_fu_730_p3);
    sensitive << ( ret_V_fu_712_p1 );

    SC_METHOD(thread_select_ln700_fu_824_p3);
    sensitive << ( t_V_reg_906 );

    SC_METHOD(thread_select_ln784_1_fu_657_p3);
    sensitive << ( img_off_V_fu_632_p2 );
    sensitive << ( icmp_ln879_2_fu_638_p2 );

    SC_METHOD(thread_select_ln784_fu_649_p3);
    sensitive << ( p_0700_0_reg_328 );
    sensitive << ( icmp_ln879_2_fu_638_p2 );
    sensitive << ( img_idx_V_fu_643_p2 );

    SC_METHOD(thread_select_ln879_fu_808_p3);
    sensitive << ( or_ln879_fu_779_p2 );
    sensitive << ( tmp_V_fu_784_p1 );
    sensitive << ( tmp_V_2_fu_798_p4 );

    SC_METHOD(thread_shl_ln_fu_493_p3);
    sensitive << ( width_mode_V );

    SC_METHOD(thread_t_V_1_fu_479_p3);
    sensitive << ( o_index_V );
    sensitive << ( trunc_ln792_fu_447_p1 );

    SC_METHOD(thread_t_V_fu_469_p2);
    sensitive << ( trunc_ln700_fu_461_p1 );
    sensitive << ( p_Result_s_fu_451_p2 );

    SC_METHOD(thread_tmp_3_fu_608_p4);
    sensitive << ( dmem_mode_V );
    sensitive << ( ret_V_7_fu_543_p1 );

    SC_METHOD(thread_tmp_4_fu_683_p4);
    sensitive << ( dmem_mode_V );
    sensitive << ( ret_V_3_reg_964 );

    SC_METHOD(thread_tmp_5_fu_668_p5);
    sensitive << ( dmem_mode_V );
    sensitive << ( ret_V_5_reg_959 );
    sensitive << ( ret_V_4_fu_665_p1 );

    SC_METHOD(thread_tmp_6_fu_836_p3);
    sensitive << ( r_V_2_reg_925 );

    SC_METHOD(thread_tmp_7_fu_716_p4);
    sensitive << ( p_0481_0_reg_361 );

    SC_METHOD(thread_tmp_V_1_fu_788_p4);
    sensitive << ( kh_mem_V_q0 );

    SC_METHOD(thread_tmp_V_2_fu_798_p4);
    sensitive << ( kh_mem_V_q0 );

    SC_METHOD(thread_tmp_V_fu_784_p1);
    sensitive << ( kh_mem_V_q0 );

    SC_METHOD(thread_trunc_ln180_fu_594_p1);
    sensitive << ( r_V_fu_589_p2 );

    SC_METHOD(thread_trunc_ln700_fu_461_p1);
    sensitive << ( kh_index_V );

    SC_METHOD(thread_trunc_ln792_fu_447_p1);
    sensitive << ( layer_mode_V );

    SC_METHOD(thread_words_per_image_V_fu_509_p2);
    sensitive << ( zext_ln769_1_fu_505_p1 );

    SC_METHOD(thread_wt_i_V_address0);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( zext_ln544_1_fu_744_p1 );
    sensitive << ( ap_block_pp1_stage0 );

    SC_METHOD(thread_wt_i_V_ce0);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );

    SC_METHOD(thread_wt_mem_V_address0);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_predicate_op171_call_state13 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( grp_bin_conv_fu_407_wt_mem_V_4_address0 );
    sensitive << ( grp_bin_dense_fu_423_wt_mem_V_2_address0 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( zext_ln180_6_fu_749_p1 );

    SC_METHOD(thread_wt_mem_V_ce0);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_predicate_op171_call_state13 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( grp_bin_conv_fu_407_wt_mem_V_4_ce0 );
    sensitive << ( grp_bin_dense_fu_423_wt_mem_V_2_ce0 );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_wt_mem_V_we0);
    sensitive << ( icmp_ln887_1_reg_1004 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter1 );

    SC_METHOD(thread_xor_ln879_fu_774_p2);
    sensitive << ( trunc_ln700_reg_901 );

    SC_METHOD(thread_zext_ln1372_fu_726_p1);
    sensitive << ( tmp_7_fu_716_p4 );

    SC_METHOD(thread_zext_ln180_1_fu_691_p1);
    sensitive << ( tmp_4_fu_683_p4 );

    SC_METHOD(thread_zext_ln180_2_fu_678_p1);
    sensitive << ( tmp_5_fu_668_p5 );

    SC_METHOD(thread_zext_ln180_3_fu_843_p1);
    sensitive << ( tmp_6_fu_836_p3 );

    SC_METHOD(thread_zext_ln180_4_fu_617_p1);
    sensitive << ( tmp_3_fu_608_p4 );

    SC_METHOD(thread_zext_ln180_5_fu_696_p1);
    sensitive << ( add_ln180_reg_984 );

    SC_METHOD(thread_zext_ln180_6_fu_749_p1);
    sensitive << ( add_ln180_1_reg_1013 );

    SC_METHOD(thread_zext_ln180_fu_598_p1);
    sensitive << ( p_0868_0_reg_339 );

    SC_METHOD(thread_zext_ln544_1_fu_744_p1);
    sensitive << ( p_0481_0_reg_361 );

    SC_METHOD(thread_zext_ln544_2_fu_570_p1);
    sensitive << ( p_0218_0_reg_350 );

    SC_METHOD(thread_zext_ln544_3_fu_565_p1);
    sensitive << ( p_0218_0_reg_350 );

    SC_METHOD(thread_zext_ln544_4_fu_765_p1);
    sensitive << ( p_0584_0_reg_372 );

    SC_METHOD(thread_zext_ln544_fu_627_p1);
    sensitive << ( p_0218_0_reg_350 );

    SC_METHOD(thread_zext_ln758_fu_475_p1);
    sensitive << ( t_V_fu_469_p2 );

    SC_METHOD(thread_zext_ln769_1_fu_505_p1);
    sensitive << ( shl_ln_fu_493_p3 );

    SC_METHOD(thread_zext_ln769_fu_501_p1);
    sensitive << ( shl_ln_fu_493_p3 );

    SC_METHOD(thread_zext_ln879_fu_521_p1);
    sensitive << ( words_per_image_V_fu_509_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( icmp_ln879_reg_937 );
    sensitive << ( icmp_ln879_1_reg_946 );
    sensitive << ( icmp_ln887_fu_531_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( icmp_ln887_1_fu_700_p2 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( icmp_ln887_2_fu_753_p2 );
    sensitive << ( ap_enable_reg_pp2_iter0 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_block_state13_on_subcall_done );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_block_pp1_stage0_subdone );
    sensitive << ( ap_block_pp2_stage0_subdone );
    sensitive << ( grp_bin_dense_fu_423_ap_done );
    sensitive << ( ap_CS_fsm_state11 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "000000000001";
    kh_index_V = "0000000000000000";
    o_index_V = "0000000000000000";
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp1_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp2_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp1_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp2_iter1 = SC_LOGIC_0;
    grp_bin_conv_fu_407_ap_start_reg = SC_LOGIC_0;
    grp_bin_dense_fu_423_ap_start_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "top_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, wt_i_V_address0, "(port)wt_i_V_address0");
    sc_trace(mVcdFile, wt_i_V_ce0, "(port)wt_i_V_ce0");
    sc_trace(mVcdFile, wt_i_V_q0, "(port)wt_i_V_q0");
    sc_trace(mVcdFile, kh_i_V_address0, "(port)kh_i_V_address0");
    sc_trace(mVcdFile, kh_i_V_ce0, "(port)kh_i_V_ce0");
    sc_trace(mVcdFile, kh_i_V_q0, "(port)kh_i_V_q0");
    sc_trace(mVcdFile, dmem_i_V_address0, "(port)dmem_i_V_address0");
    sc_trace(mVcdFile, dmem_i_V_ce0, "(port)dmem_i_V_ce0");
    sc_trace(mVcdFile, dmem_i_V_q0, "(port)dmem_i_V_q0");
    sc_trace(mVcdFile, dmem_o_V_address0, "(port)dmem_o_V_address0");
    sc_trace(mVcdFile, dmem_o_V_ce0, "(port)dmem_o_V_ce0");
    sc_trace(mVcdFile, dmem_o_V_we0, "(port)dmem_o_V_we0");
    sc_trace(mVcdFile, dmem_o_V_d0, "(port)dmem_o_V_d0");
    sc_trace(mVcdFile, n_inputs_V, "(port)n_inputs_V");
    sc_trace(mVcdFile, n_outputs_V, "(port)n_outputs_V");
    sc_trace(mVcdFile, input_words_V, "(port)input_words_V");
    sc_trace(mVcdFile, output_words_V, "(port)output_words_V");
    sc_trace(mVcdFile, layer_mode_V, "(port)layer_mode_V");
    sc_trace(mVcdFile, dmem_mode_V, "(port)dmem_mode_V");
    sc_trace(mVcdFile, width_mode_V, "(port)width_mode_V");
    sc_trace(mVcdFile, norm_mode_V, "(port)norm_mode_V");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, kh_index_V, "kh_index_V");
    sc_trace(mVcdFile, o_index_V, "o_index_V");
    sc_trace(mVcdFile, dmem_V_address0, "dmem_V_address0");
    sc_trace(mVcdFile, dmem_V_ce0, "dmem_V_ce0");
    sc_trace(mVcdFile, dmem_V_we0, "dmem_V_we0");
    sc_trace(mVcdFile, dmem_V_d0, "dmem_V_d0");
    sc_trace(mVcdFile, dmem_V_q0, "dmem_V_q0");
    sc_trace(mVcdFile, wt_mem_V_address0, "wt_mem_V_address0");
    sc_trace(mVcdFile, wt_mem_V_ce0, "wt_mem_V_ce0");
    sc_trace(mVcdFile, wt_mem_V_we0, "wt_mem_V_we0");
    sc_trace(mVcdFile, wt_mem_V_q0, "wt_mem_V_q0");
    sc_trace(mVcdFile, kh_mem_V_address0, "kh_mem_V_address0");
    sc_trace(mVcdFile, kh_mem_V_ce0, "kh_mem_V_ce0");
    sc_trace(mVcdFile, kh_mem_V_we0, "kh_mem_V_we0");
    sc_trace(mVcdFile, kh_mem_V_q0, "kh_mem_V_q0");
    sc_trace(mVcdFile, p_0700_0_reg_328, "p_0700_0_reg_328");
    sc_trace(mVcdFile, p_0868_0_reg_339, "p_0868_0_reg_339");
    sc_trace(mVcdFile, p_0218_0_reg_350, "p_0218_0_reg_350");
    sc_trace(mVcdFile, p_0481_0_reg_361, "p_0481_0_reg_361");
    sc_trace(mVcdFile, p_0584_0_reg_372, "p_0584_0_reg_372");
    sc_trace(mVcdFile, layer_type_V_fu_437_p4, "layer_type_V_fu_437_p4");
    sc_trace(mVcdFile, layer_type_V_reg_891, "layer_type_V_reg_891");
    sc_trace(mVcdFile, trunc_ln792_fu_447_p1, "trunc_ln792_fu_447_p1");
    sc_trace(mVcdFile, trunc_ln792_reg_896, "trunc_ln792_reg_896");
    sc_trace(mVcdFile, trunc_ln700_fu_461_p1, "trunc_ln700_fu_461_p1");
    sc_trace(mVcdFile, trunc_ln700_reg_901, "trunc_ln700_reg_901");
    sc_trace(mVcdFile, t_V_fu_469_p2, "t_V_fu_469_p2");
    sc_trace(mVcdFile, t_V_reg_906, "t_V_reg_906");
    sc_trace(mVcdFile, zext_ln758_fu_475_p1, "zext_ln758_fu_475_p1");
    sc_trace(mVcdFile, zext_ln758_reg_912, "zext_ln758_reg_912");
    sc_trace(mVcdFile, t_V_1_fu_479_p3, "t_V_1_fu_479_p3");
    sc_trace(mVcdFile, t_V_1_reg_918, "t_V_1_reg_918");
    sc_trace(mVcdFile, r_V_2_fu_487_p2, "r_V_2_fu_487_p2");
    sc_trace(mVcdFile, r_V_2_reg_925, "r_V_2_reg_925");
    sc_trace(mVcdFile, zext_ln769_fu_501_p1, "zext_ln769_fu_501_p1");
    sc_trace(mVcdFile, zext_ln769_reg_932, "zext_ln769_reg_932");
    sc_trace(mVcdFile, icmp_ln879_fu_515_p2, "icmp_ln879_fu_515_p2");
    sc_trace(mVcdFile, icmp_ln879_reg_937, "icmp_ln879_reg_937");
    sc_trace(mVcdFile, zext_ln879_fu_521_p1, "zext_ln879_fu_521_p1");
    sc_trace(mVcdFile, zext_ln879_reg_941, "zext_ln879_reg_941");
    sc_trace(mVcdFile, icmp_ln879_1_fu_525_p2, "icmp_ln879_1_fu_525_p2");
    sc_trace(mVcdFile, icmp_ln879_1_reg_946, "icmp_ln879_1_reg_946");
    sc_trace(mVcdFile, icmp_ln887_fu_531_p2, "icmp_ln887_fu_531_p2");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter0, "ap_block_state2_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter1, "ap_block_state3_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, i_V_2_fu_537_p2, "i_V_2_fu_537_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, ret_V_5_fu_547_p1, "ret_V_5_fu_547_p1");
    sc_trace(mVcdFile, ret_V_5_reg_959, "ret_V_5_reg_959");
    sc_trace(mVcdFile, ret_V_3_fu_551_p1, "ret_V_3_fu_551_p1");
    sc_trace(mVcdFile, ret_V_3_reg_964, "ret_V_3_reg_964");
    sc_trace(mVcdFile, ret_V_6_reg_969, "ret_V_6_reg_969");
    sc_trace(mVcdFile, add_ln180_fu_621_p2, "add_ln180_fu_621_p2");
    sc_trace(mVcdFile, add_ln180_reg_984, "add_ln180_reg_984");
    sc_trace(mVcdFile, select_ln784_fu_649_p3, "select_ln784_fu_649_p3");
    sc_trace(mVcdFile, select_ln784_1_fu_657_p3, "select_ln784_1_fu_657_p3");
    sc_trace(mVcdFile, icmp_ln887_1_fu_700_p2, "icmp_ln887_1_fu_700_p2");
    sc_trace(mVcdFile, icmp_ln887_1_reg_1004, "icmp_ln887_1_reg_1004");
    sc_trace(mVcdFile, ap_CS_fsm_pp1_stage0, "ap_CS_fsm_pp1_stage0");
    sc_trace(mVcdFile, ap_block_state5_pp1_stage0_iter0, "ap_block_state5_pp1_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state6_pp1_stage0_iter1, "ap_block_state6_pp1_stage0_iter1");
    sc_trace(mVcdFile, ap_block_pp1_stage0_11001, "ap_block_pp1_stage0_11001");
    sc_trace(mVcdFile, i_V_fu_706_p2, "i_V_fu_706_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp1_iter0, "ap_enable_reg_pp1_iter0");
    sc_trace(mVcdFile, add_ln180_1_fu_738_p2, "add_ln180_1_fu_738_p2");
    sc_trace(mVcdFile, add_ln180_1_reg_1013, "add_ln180_1_reg_1013");
    sc_trace(mVcdFile, icmp_ln887_2_fu_753_p2, "icmp_ln887_2_fu_753_p2");
    sc_trace(mVcdFile, icmp_ln887_2_reg_1023, "icmp_ln887_2_reg_1023");
    sc_trace(mVcdFile, ap_CS_fsm_pp2_stage0, "ap_CS_fsm_pp2_stage0");
    sc_trace(mVcdFile, ap_block_state8_pp2_stage0_iter0, "ap_block_state8_pp2_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state9_pp2_stage0_iter1, "ap_block_state9_pp2_stage0_iter1");
    sc_trace(mVcdFile, ap_block_pp2_stage0_11001, "ap_block_pp2_stage0_11001");
    sc_trace(mVcdFile, i_V_1_fu_759_p2, "i_V_1_fu_759_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp2_iter0, "ap_enable_reg_pp2_iter0");
    sc_trace(mVcdFile, zext_ln544_4_fu_765_p1, "zext_ln544_4_fu_765_p1");
    sc_trace(mVcdFile, zext_ln544_4_reg_1032, "zext_ln544_4_reg_1032");
    sc_trace(mVcdFile, add_ln700_fu_770_p2, "add_ln700_fu_770_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, nc_V_fu_816_p3, "nc_V_fu_816_p3");
    sc_trace(mVcdFile, nc_V_reg_1047, "nc_V_reg_1047");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, select_ln700_fu_824_p3, "select_ln700_fu_824_p3");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, grp_bin_conv_fu_407_ap_ready, "grp_bin_conv_fu_407_ap_ready");
    sc_trace(mVcdFile, grp_bin_conv_fu_407_ap_done, "grp_bin_conv_fu_407_ap_done");
    sc_trace(mVcdFile, ap_predicate_op171_call_state13, "ap_predicate_op171_call_state13");
    sc_trace(mVcdFile, ap_block_state13_on_subcall_done, "ap_block_state13_on_subcall_done");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state2, "ap_condition_pp0_exit_iter0_state2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, ap_block_pp1_stage0_subdone, "ap_block_pp1_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp1_exit_iter0_state5, "ap_condition_pp1_exit_iter0_state5");
    sc_trace(mVcdFile, ap_enable_reg_pp1_iter1, "ap_enable_reg_pp1_iter1");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, ap_block_pp2_stage0_subdone, "ap_block_pp2_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp2_exit_iter0_state8, "ap_condition_pp2_exit_iter0_state8");
    sc_trace(mVcdFile, ap_enable_reg_pp2_iter1, "ap_enable_reg_pp2_iter1");
    sc_trace(mVcdFile, grp_bin_conv_fu_407_ap_start, "grp_bin_conv_fu_407_ap_start");
    sc_trace(mVcdFile, grp_bin_conv_fu_407_ap_idle, "grp_bin_conv_fu_407_ap_idle");
    sc_trace(mVcdFile, grp_bin_conv_fu_407_wt_mem_V_4_address0, "grp_bin_conv_fu_407_wt_mem_V_4_address0");
    sc_trace(mVcdFile, grp_bin_conv_fu_407_wt_mem_V_4_ce0, "grp_bin_conv_fu_407_wt_mem_V_4_ce0");
    sc_trace(mVcdFile, grp_bin_conv_fu_407_dmem_V_4_address0, "grp_bin_conv_fu_407_dmem_V_4_address0");
    sc_trace(mVcdFile, grp_bin_conv_fu_407_dmem_V_4_ce0, "grp_bin_conv_fu_407_dmem_V_4_ce0");
    sc_trace(mVcdFile, grp_bin_conv_fu_407_dmem_V_4_we0, "grp_bin_conv_fu_407_dmem_V_4_we0");
    sc_trace(mVcdFile, grp_bin_conv_fu_407_dmem_V_4_d0, "grp_bin_conv_fu_407_dmem_V_4_d0");
    sc_trace(mVcdFile, grp_bin_dense_fu_423_ap_start, "grp_bin_dense_fu_423_ap_start");
    sc_trace(mVcdFile, grp_bin_dense_fu_423_ap_done, "grp_bin_dense_fu_423_ap_done");
    sc_trace(mVcdFile, grp_bin_dense_fu_423_ap_idle, "grp_bin_dense_fu_423_ap_idle");
    sc_trace(mVcdFile, grp_bin_dense_fu_423_ap_ready, "grp_bin_dense_fu_423_ap_ready");
    sc_trace(mVcdFile, grp_bin_dense_fu_423_wt_mem_V_2_address0, "grp_bin_dense_fu_423_wt_mem_V_2_address0");
    sc_trace(mVcdFile, grp_bin_dense_fu_423_wt_mem_V_2_ce0, "grp_bin_dense_fu_423_wt_mem_V_2_ce0");
    sc_trace(mVcdFile, grp_bin_dense_fu_423_kh_mem_V_2_address0, "grp_bin_dense_fu_423_kh_mem_V_2_address0");
    sc_trace(mVcdFile, grp_bin_dense_fu_423_kh_mem_V_2_ce0, "grp_bin_dense_fu_423_kh_mem_V_2_ce0");
    sc_trace(mVcdFile, grp_bin_dense_fu_423_dmem_V_2_address0, "grp_bin_dense_fu_423_dmem_V_2_address0");
    sc_trace(mVcdFile, grp_bin_dense_fu_423_dmem_V_2_ce0, "grp_bin_dense_fu_423_dmem_V_2_ce0");
    sc_trace(mVcdFile, grp_bin_dense_fu_423_dmem_V_2_we0, "grp_bin_dense_fu_423_dmem_V_2_we0");
    sc_trace(mVcdFile, grp_bin_dense_fu_423_dmem_V_2_d0, "grp_bin_dense_fu_423_dmem_V_2_d0");
    sc_trace(mVcdFile, kh_index_V_new_1_reg_383, "kh_index_V_new_1_reg_383");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, n_outputs_V_pn_reg_394, "n_outputs_V_pn_reg_394");
    sc_trace(mVcdFile, grp_bin_conv_fu_407_ap_start_reg, "grp_bin_conv_fu_407_ap_start_reg");
    sc_trace(mVcdFile, grp_bin_dense_fu_423_ap_start_reg, "grp_bin_dense_fu_423_ap_start_reg");
    sc_trace(mVcdFile, zext_ln544_3_fu_565_p1, "zext_ln544_3_fu_565_p1");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, zext_ln544_2_fu_570_p1, "zext_ln544_2_fu_570_p1");
    sc_trace(mVcdFile, zext_ln544_fu_627_p1, "zext_ln544_fu_627_p1");
    sc_trace(mVcdFile, zext_ln180_2_fu_678_p1, "zext_ln180_2_fu_678_p1");
    sc_trace(mVcdFile, zext_ln180_1_fu_691_p1, "zext_ln180_1_fu_691_p1");
    sc_trace(mVcdFile, zext_ln180_5_fu_696_p1, "zext_ln180_5_fu_696_p1");
    sc_trace(mVcdFile, zext_ln544_1_fu_744_p1, "zext_ln544_1_fu_744_p1");
    sc_trace(mVcdFile, ap_block_pp1_stage0, "ap_block_pp1_stage0");
    sc_trace(mVcdFile, zext_ln180_6_fu_749_p1, "zext_ln180_6_fu_749_p1");
    sc_trace(mVcdFile, ap_block_pp2_stage0, "ap_block_pp2_stage0");
    sc_trace(mVcdFile, zext_ln180_3_fu_843_p1, "zext_ln180_3_fu_843_p1");
    sc_trace(mVcdFile, add_ln700_6_fu_831_p2, "add_ln700_6_fu_831_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state15, "ap_CS_fsm_state15");
    sc_trace(mVcdFile, p_Result_s_fu_451_p2, "p_Result_s_fu_451_p2");
    sc_trace(mVcdFile, shl_ln_fu_493_p3, "shl_ln_fu_493_p3");
    sc_trace(mVcdFile, zext_ln769_1_fu_505_p1, "zext_ln769_1_fu_505_p1");
    sc_trace(mVcdFile, words_per_image_V_fu_509_p2, "words_per_image_V_fu_509_p2");
    sc_trace(mVcdFile, ret_V_9_fu_575_p4, "ret_V_9_fu_575_p4");
    sc_trace(mVcdFile, ret_V_8_fu_585_p1, "ret_V_8_fu_585_p1");
    sc_trace(mVcdFile, r_V_fu_589_p2, "r_V_fu_589_p2");
    sc_trace(mVcdFile, trunc_ln180_fu_594_p1, "trunc_ln180_fu_594_p1");
    sc_trace(mVcdFile, zext_ln180_fu_598_p1, "zext_ln180_fu_598_p1");
    sc_trace(mVcdFile, ret_V_7_fu_543_p1, "ret_V_7_fu_543_p1");
    sc_trace(mVcdFile, tmp_3_fu_608_p4, "tmp_3_fu_608_p4");
    sc_trace(mVcdFile, add_ln180_2_fu_602_p2, "add_ln180_2_fu_602_p2");
    sc_trace(mVcdFile, zext_ln180_4_fu_617_p1, "zext_ln180_4_fu_617_p1");
    sc_trace(mVcdFile, img_off_V_fu_632_p2, "img_off_V_fu_632_p2");
    sc_trace(mVcdFile, icmp_ln879_2_fu_638_p2, "icmp_ln879_2_fu_638_p2");
    sc_trace(mVcdFile, img_idx_V_fu_643_p2, "img_idx_V_fu_643_p2");
    sc_trace(mVcdFile, ret_V_4_fu_665_p1, "ret_V_4_fu_665_p1");
    sc_trace(mVcdFile, tmp_5_fu_668_p5, "tmp_5_fu_668_p5");
    sc_trace(mVcdFile, tmp_4_fu_683_p4, "tmp_4_fu_683_p4");
    sc_trace(mVcdFile, tmp_7_fu_716_p4, "tmp_7_fu_716_p4");
    sc_trace(mVcdFile, ret_V_fu_712_p1, "ret_V_fu_712_p1");
    sc_trace(mVcdFile, select_ln180_fu_730_p3, "select_ln180_fu_730_p3");
    sc_trace(mVcdFile, zext_ln1372_fu_726_p1, "zext_ln1372_fu_726_p1");
    sc_trace(mVcdFile, xor_ln879_fu_774_p2, "xor_ln879_fu_774_p2");
    sc_trace(mVcdFile, or_ln879_fu_779_p2, "or_ln879_fu_779_p2");
    sc_trace(mVcdFile, tmp_V_fu_784_p1, "tmp_V_fu_784_p1");
    sc_trace(mVcdFile, tmp_V_2_fu_798_p4, "tmp_V_2_fu_798_p4");
    sc_trace(mVcdFile, tmp_V_1_fu_788_p4, "tmp_V_1_fu_788_p4");
    sc_trace(mVcdFile, select_ln879_fu_808_p3, "select_ln879_fu_808_p3");
    sc_trace(mVcdFile, tmp_6_fu_836_p3, "tmp_6_fu_836_p3");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
    sc_trace(mVcdFile, ap_idle_pp1, "ap_idle_pp1");
    sc_trace(mVcdFile, ap_enable_pp1, "ap_enable_pp1");
    sc_trace(mVcdFile, ap_idle_pp2, "ap_idle_pp2");
    sc_trace(mVcdFile, ap_enable_pp2, "ap_enable_pp2");
    sc_trace(mVcdFile, ap_condition_796, "ap_condition_796");
#endif

    }
    mHdltvinHandle.open("top.hdltvin.dat");
    mHdltvoutHandle.open("top.hdltvout.dat");
}

top::~top() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete dmem_V_U;
    delete wt_mem_V_U;
    delete kh_mem_V_U;
    delete grp_bin_conv_fu_407;
    delete grp_bin_dense_fu_423;
}

void top::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read()))) {
            ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state2.read() ^ ap_const_logic_1);
        } else if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            ap_enable_reg_pp0_iter1 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp1_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp1_exit_iter0_state5.read()))) {
            ap_enable_reg_pp1_iter0 = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
            ap_enable_reg_pp1_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp1_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp1_exit_iter0_state5.read()))) {
            ap_enable_reg_pp1_iter1 = (ap_condition_pp1_exit_iter0_state5.read() ^ ap_const_logic_1);
        } else if (esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp1_iter1 = ap_enable_reg_pp1_iter0.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
            ap_enable_reg_pp1_iter1 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp2_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp2_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp2_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp2_exit_iter0_state8.read()))) {
            ap_enable_reg_pp2_iter0 = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
            ap_enable_reg_pp2_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp2_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_block_pp2_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp2_exit_iter0_state8.read()))) {
            ap_enable_reg_pp2_iter1 = (ap_condition_pp2_exit_iter0_state8.read() ^ ap_const_logic_1);
        } else if (esl_seteq<1,1,1>(ap_block_pp2_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp2_iter1 = ap_enable_reg_pp2_iter0.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
            ap_enable_reg_pp2_iter1 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_bin_conv_fu_407_ap_start_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
            grp_bin_conv_fu_407_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_bin_conv_fu_407_ap_ready.read())) {
            grp_bin_conv_fu_407_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_bin_dense_fu_423_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(icmp_ln879_reg_937.read(), ap_const_lv1_0) && 
             esl_seteq<1,1,1>(icmp_ln879_1_reg_946.read(), ap_const_lv1_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()))) {
            grp_bin_dense_fu_423_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_bin_dense_fu_423_ap_ready.read())) {
            grp_bin_dense_fu_423_ap_start_reg = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
         esl_seteq<1,1,1>(grp_bin_dense_fu_423_ap_done.read(), ap_const_logic_1))) {
        kh_index_V_new_1_reg_383 = zext_ln758_reg_912.read();
    } else if ((esl_seteq<1,1,1>(icmp_ln879_1_reg_946.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(icmp_ln879_reg_937.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) && 
                esl_seteq<1,1,1>(ap_block_state13_on_subcall_done.read(), ap_const_boolean_0))) {
        kh_index_V_new_1_reg_383 = select_ln700_fu_824_p3.read();
    } else if ((esl_seteq<1,1,1>(icmp_ln879_1_reg_946.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()))) {
        kh_index_V_new_1_reg_383 = add_ln700_fu_770_p2.read();
    }
    if ((esl_seteq<1,1,1>(icmp_ln879_1_reg_946.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(icmp_ln879_reg_937.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) && 
         esl_seteq<1,1,1>(ap_block_state13_on_subcall_done.read(), ap_const_boolean_0))) {
        n_outputs_V_pn_reg_394 = ap_const_lv16_1;
    } else if (((esl_seteq<1,1,1>(icmp_ln879_1_reg_946.read(), ap_const_lv1_1) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
                 esl_seteq<1,1,1>(grp_bin_dense_fu_423_ap_done.read(), ap_const_logic_1)))) {
        n_outputs_V_pn_reg_394 = n_outputs_V.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(icmp_ln887_fu_531_p2.read(), ap_const_lv1_0))) {
        p_0218_0_reg_350 = i_V_2_fu_537_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        p_0218_0_reg_350 = ap_const_lv7_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        p_0481_0_reg_361 = ap_const_lv13_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
                esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln887_1_fu_700_p2.read()))) {
        p_0481_0_reg_361 = i_V_fu_706_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        p_0584_0_reg_372 = ap_const_lv7_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp2_stage0.read()) && 
                esl_seteq<1,1,1>(ap_block_pp2_stage0_11001.read(), ap_const_boolean_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter0.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln887_2_fu_753_p2.read()))) {
        p_0584_0_reg_372 = i_V_1_fu_759_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(icmp_ln887_fu_531_p2.read(), ap_const_lv1_0))) {
        p_0700_0_reg_328 = select_ln784_fu_649_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        p_0700_0_reg_328 = ap_const_lv16_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(icmp_ln887_fu_531_p2.read(), ap_const_lv1_0))) {
        p_0868_0_reg_339 = select_ln784_1_fu_657_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        p_0868_0_reg_339 = ap_const_lv10_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln887_1_fu_700_p2.read()))) {
        add_ln180_1_reg_1013 = add_ln180_1_fu_738_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln887_fu_531_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(icmp_ln879_reg_937.read(), ap_const_lv1_1))) {
        add_ln180_reg_984 = add_ln180_fu_621_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        icmp_ln879_1_reg_946 = icmp_ln879_1_fu_525_p2.read();
        icmp_ln879_reg_937 = icmp_ln879_fu_515_p2.read();
        layer_type_V_reg_891 = layer_mode_V.read().range(2, 1);
        r_V_2_reg_925 = r_V_2_fu_487_p2.read();
        t_V_1_reg_918 = t_V_1_fu_479_p3.read();
        t_V_reg_906 = t_V_fu_469_p2.read();
        trunc_ln700_reg_901 = trunc_ln700_fu_461_p1.read();
        trunc_ln792_reg_896 = trunc_ln792_fu_447_p1.read();
        zext_ln758_reg_912 = zext_ln758_fu_475_p1.read();
        zext_ln769_reg_932 = zext_ln769_fu_501_p1.read();
        zext_ln879_reg_941 = zext_ln879_fu_521_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0))) {
        icmp_ln887_1_reg_1004 = icmp_ln887_1_fu_700_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp2_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp2_stage0_11001.read(), ap_const_boolean_0))) {
        icmp_ln887_2_reg_1023 = icmp_ln887_2_fu_753_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        kh_index_V = kh_index_V_new_1_reg_383.read();
        o_index_V = add_ln700_6_fu_831_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        nc_V_reg_1047 = nc_V_fu_816_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln887_fu_531_p2.read(), ap_const_lv1_0))) {
        ret_V_3_reg_964 = ret_V_3_fu_551_p1.read();
        ret_V_5_reg_959 = ret_V_5_fu_547_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln887_fu_531_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(icmp_ln879_reg_937.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(icmp_ln879_1_reg_946.read(), ap_const_lv1_0))) {
        ret_V_6_reg_969 = p_0218_0_reg_350.read().range(6, 1);
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp2_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp2_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln887_2_fu_753_p2.read()))) {
        zext_ln544_4_reg_1032 = zext_ln544_4_fu_765_p1.read();
    }
}

void top::thread_add_ln180_1_fu_738_p2() {
    add_ln180_1_fu_738_p2 = (!select_ln180_fu_730_p3.read().is_01() || !zext_ln1372_fu_726_p1.read().is_01())? sc_lv<13>(): (sc_biguint<13>(select_ln180_fu_730_p3.read()) + sc_biguint<13>(zext_ln1372_fu_726_p1.read()));
}

void top::thread_add_ln180_2_fu_602_p2() {
    add_ln180_2_fu_602_p2 = (!trunc_ln180_fu_594_p1.read().is_01() || !zext_ln180_fu_598_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(trunc_ln180_fu_594_p1.read()) + sc_biguint<14>(zext_ln180_fu_598_p1.read()));
}

void top::thread_add_ln180_fu_621_p2() {
    add_ln180_fu_621_p2 = (!add_ln180_2_fu_602_p2.read().is_01() || !zext_ln180_4_fu_617_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(add_ln180_2_fu_602_p2.read()) + sc_biguint<14>(zext_ln180_4_fu_617_p1.read()));
}

void top::thread_add_ln700_6_fu_831_p2() {
    add_ln700_6_fu_831_p2 = (!t_V_1_reg_918.read().is_01() || !n_outputs_V_pn_reg_394.read().is_01())? sc_lv<16>(): (sc_biguint<16>(t_V_1_reg_918.read()) + sc_biguint<16>(n_outputs_V_pn_reg_394.read()));
}

void top::thread_add_ln700_fu_770_p2() {
    add_ln700_fu_770_p2 = (!zext_ln758_reg_912.read().is_01() || !n_outputs_V.read().is_01())? sc_lv<16>(): (sc_biguint<16>(zext_ln758_reg_912.read()) + sc_biguint<16>(n_outputs_V.read()));
}

void top::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[1];
}

void top::thread_ap_CS_fsm_pp1_stage0() {
    ap_CS_fsm_pp1_stage0 = ap_CS_fsm.read()[3];
}

void top::thread_ap_CS_fsm_pp2_stage0() {
    ap_CS_fsm_pp2_stage0 = ap_CS_fsm.read()[5];
}

void top::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void top::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[6];
}

void top::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[7];
}

void top::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[8];
}

void top::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[9];
}

void top::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read()[10];
}

void top::thread_ap_CS_fsm_state15() {
    ap_CS_fsm_state15 = ap_CS_fsm.read()[11];
}

void top::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[2];
}

void top::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[4];
}

void top::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void top::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void top::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void top::thread_ap_block_pp1_stage0() {
    ap_block_pp1_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void top::thread_ap_block_pp1_stage0_11001() {
    ap_block_pp1_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void top::thread_ap_block_pp1_stage0_subdone() {
    ap_block_pp1_stage0_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void top::thread_ap_block_pp2_stage0() {
    ap_block_pp2_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void top::thread_ap_block_pp2_stage0_11001() {
    ap_block_pp2_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void top::thread_ap_block_pp2_stage0_subdone() {
    ap_block_pp2_stage0_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void top::thread_ap_block_state13_on_subcall_done() {
    ap_block_state13_on_subcall_done = (esl_seteq<1,1,1>(ap_const_logic_0, grp_bin_conv_fu_407_ap_done.read()) && esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op171_call_state13.read()));
}

void top::thread_ap_block_state2_pp0_stage0_iter0() {
    ap_block_state2_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void top::thread_ap_block_state3_pp0_stage0_iter1() {
    ap_block_state3_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void top::thread_ap_block_state5_pp1_stage0_iter0() {
    ap_block_state5_pp1_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void top::thread_ap_block_state6_pp1_stage0_iter1() {
    ap_block_state6_pp1_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void top::thread_ap_block_state8_pp2_stage0_iter0() {
    ap_block_state8_pp2_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void top::thread_ap_block_state9_pp2_stage0_iter1() {
    ap_block_state9_pp2_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void top::thread_ap_condition_796() {
    ap_condition_796 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(icmp_ln887_fu_531_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0));
}

void top::thread_ap_condition_pp0_exit_iter0_state2() {
    if (esl_seteq<1,1,1>(icmp_ln887_fu_531_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_0;
    }
}

void top::thread_ap_condition_pp1_exit_iter0_state5() {
    if (esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln887_1_fu_700_p2.read())) {
        ap_condition_pp1_exit_iter0_state5 = ap_const_logic_1;
    } else {
        ap_condition_pp1_exit_iter0_state5 = ap_const_logic_0;
    }
}

void top::thread_ap_condition_pp2_exit_iter0_state8() {
    if (esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln887_2_fu_753_p2.read())) {
        ap_condition_pp2_exit_iter0_state8 = ap_const_logic_1;
    } else {
        ap_condition_pp2_exit_iter0_state8 = ap_const_logic_0;
    }
}

void top::thread_ap_done() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void top::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void top::thread_ap_enable_pp1() {
    ap_enable_pp1 = (ap_idle_pp1.read() ^ ap_const_logic_1);
}

void top::thread_ap_enable_pp2() {
    ap_enable_pp2 = (ap_idle_pp2.read() ^ ap_const_logic_1);
}

void top::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void top::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void top::thread_ap_idle_pp1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp1_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp1_iter1.read()))) {
        ap_idle_pp1 = ap_const_logic_1;
    } else {
        ap_idle_pp1 = ap_const_logic_0;
    }
}

void top::thread_ap_idle_pp2() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp2_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp2_iter1.read()))) {
        ap_idle_pp2 = ap_const_logic_1;
    } else {
        ap_idle_pp2 = ap_const_logic_0;
    }
}

void top::thread_ap_predicate_op171_call_state13() {
    ap_predicate_op171_call_state13 = (esl_seteq<1,1,1>(icmp_ln879_1_reg_946.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(icmp_ln879_reg_937.read(), ap_const_lv1_1));
}

void top::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void top::thread_dmem_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        dmem_V_address0 =  (sc_lv<12>) (zext_ln180_3_fu_843_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                esl_seteq<1,1,1>(icmp_ln879_reg_937.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        dmem_V_address0 =  (sc_lv<12>) (zext_ln180_5_fu_696_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                esl_seteq<1,1,1>(icmp_ln879_reg_937.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(icmp_ln879_1_reg_946.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        dmem_V_address0 =  (sc_lv<12>) (zext_ln180_1_fu_691_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                esl_seteq<1,1,1>(icmp_ln879_reg_937.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(icmp_ln879_1_reg_946.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        dmem_V_address0 =  (sc_lv<12>) (zext_ln180_2_fu_678_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        dmem_V_address0 = grp_bin_dense_fu_423_dmem_V_2_address0.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) && 
                esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op171_call_state13.read()))) {
        dmem_V_address0 = grp_bin_conv_fu_407_dmem_V_4_address0.read();
    } else {
        dmem_V_address0 = "XXXXXXXXXXXX";
    }
}

void top::thread_dmem_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(icmp_ln879_reg_937.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(icmp_ln879_1_reg_946.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(icmp_ln879_reg_937.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(icmp_ln879_1_reg_946.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(icmp_ln879_reg_937.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read())))) {
        dmem_V_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        dmem_V_ce0 = grp_bin_dense_fu_423_dmem_V_2_ce0.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) && 
                esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op171_call_state13.read()))) {
        dmem_V_ce0 = grp_bin_conv_fu_407_dmem_V_4_ce0.read();
    } else {
        dmem_V_ce0 = ap_const_logic_0;
    }
}

void top::thread_dmem_V_d0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(icmp_ln879_reg_937.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(icmp_ln879_1_reg_946.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(icmp_ln879_reg_937.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(icmp_ln879_1_reg_946.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(icmp_ln879_reg_937.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read())))) {
        dmem_V_d0 = dmem_i_V_q0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        dmem_V_d0 = grp_bin_dense_fu_423_dmem_V_2_d0.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) && 
                esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op171_call_state13.read()))) {
        dmem_V_d0 = grp_bin_conv_fu_407_dmem_V_4_d0.read();
    } else {
        dmem_V_d0 =  (sc_lv<64>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void top::thread_dmem_V_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(icmp_ln879_reg_937.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(icmp_ln879_1_reg_946.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(icmp_ln879_reg_937.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(icmp_ln879_1_reg_946.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(icmp_ln879_reg_937.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read())))) {
        dmem_V_we0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        dmem_V_we0 = grp_bin_dense_fu_423_dmem_V_2_we0.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) && 
                esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op171_call_state13.read()))) {
        dmem_V_we0 = grp_bin_conv_fu_407_dmem_V_4_we0.read();
    } else {
        dmem_V_we0 = ap_const_logic_0;
    }
}

void top::thread_dmem_i_V_address0() {
    if (esl_seteq<1,1,1>(ap_condition_796.read(), ap_const_boolean_1)) {
        if (esl_seteq<1,1,1>(icmp_ln879_reg_937.read(), ap_const_lv1_1)) {
            dmem_i_V_address0 =  (sc_lv<11>) (zext_ln544_fu_627_p1.read());
        } else if ((esl_seteq<1,1,1>(icmp_ln879_reg_937.read(), ap_const_lv1_0) && 
                    esl_seteq<1,1,1>(icmp_ln879_1_reg_946.read(), ap_const_lv1_1))) {
            dmem_i_V_address0 =  (sc_lv<11>) (zext_ln544_2_fu_570_p1.read());
        } else if ((esl_seteq<1,1,1>(icmp_ln879_reg_937.read(), ap_const_lv1_0) && 
                    esl_seteq<1,1,1>(icmp_ln879_1_reg_946.read(), ap_const_lv1_0))) {
            dmem_i_V_address0 =  (sc_lv<11>) (zext_ln544_3_fu_565_p1.read());
        } else {
            dmem_i_V_address0 =  (sc_lv<11>) ("XXXXXXXXXXX");
        }
    } else {
        dmem_i_V_address0 =  (sc_lv<11>) ("XXXXXXXXXXX");
    }
}

void top::thread_dmem_i_V_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(icmp_ln887_fu_531_p2.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(icmp_ln879_reg_937.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(icmp_ln879_1_reg_946.read(), ap_const_lv1_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(icmp_ln887_fu_531_p2.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(icmp_ln879_reg_937.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(icmp_ln879_1_reg_946.read(), ap_const_lv1_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(icmp_ln887_fu_531_p2.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(icmp_ln879_reg_937.read(), ap_const_lv1_1)))) {
        dmem_i_V_ce0 = ap_const_logic_1;
    } else {
        dmem_i_V_ce0 = ap_const_logic_0;
    }
}

void top::thread_dmem_o_V_address0() {
    dmem_o_V_address0 =  (sc_lv<7>) (ap_const_lv64_0);
}

void top::thread_dmem_o_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        dmem_o_V_ce0 = ap_const_logic_1;
    } else {
        dmem_o_V_ce0 = ap_const_logic_0;
    }
}

void top::thread_dmem_o_V_d0() {
    dmem_o_V_d0 = dmem_V_q0.read();
}

void top::thread_dmem_o_V_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        dmem_o_V_we0 = ap_const_logic_1;
    } else {
        dmem_o_V_we0 = ap_const_logic_0;
    }
}

void top::thread_grp_bin_conv_fu_407_ap_start() {
    grp_bin_conv_fu_407_ap_start = grp_bin_conv_fu_407_ap_start_reg.read();
}

void top::thread_grp_bin_dense_fu_423_ap_start() {
    grp_bin_dense_fu_423_ap_start = grp_bin_dense_fu_423_ap_start_reg.read();
}

void top::thread_i_V_1_fu_759_p2() {
    i_V_1_fu_759_p2 = (!p_0584_0_reg_372.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(p_0584_0_reg_372.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void top::thread_i_V_2_fu_537_p2() {
    i_V_2_fu_537_p2 = (!p_0218_0_reg_350.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(p_0218_0_reg_350.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void top::thread_i_V_fu_706_p2() {
    i_V_fu_706_p2 = (!p_0481_0_reg_361.read().is_01() || !ap_const_lv13_1.is_01())? sc_lv<13>(): (sc_biguint<13>(p_0481_0_reg_361.read()) + sc_biguint<13>(ap_const_lv13_1));
}

void top::thread_icmp_ln879_1_fu_525_p2() {
    icmp_ln879_1_fu_525_p2 = (!layer_type_V_fu_437_p4.read().is_01() || !ap_const_lv2_0.is_01())? sc_lv<1>(): sc_lv<1>(layer_type_V_fu_437_p4.read() == ap_const_lv2_0);
}

void top::thread_icmp_ln879_2_fu_638_p2() {
    icmp_ln879_2_fu_638_p2 = (!img_off_V_fu_632_p2.read().is_01() || !zext_ln879_reg_941.read().is_01())? sc_lv<1>(): sc_lv<1>(img_off_V_fu_632_p2.read() == zext_ln879_reg_941.read());
}

void top::thread_icmp_ln879_fu_515_p2() {
    icmp_ln879_fu_515_p2 = (!layer_type_V_fu_437_p4.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(layer_type_V_fu_437_p4.read() == ap_const_lv2_1);
}

void top::thread_icmp_ln887_1_fu_700_p2() {
    icmp_ln887_1_fu_700_p2 = (!p_0481_0_reg_361.read().is_01() || !ap_const_lv13_124A.is_01())? sc_lv<1>(): sc_lv<1>(p_0481_0_reg_361.read() == ap_const_lv13_124A);
}

void top::thread_icmp_ln887_2_fu_753_p2() {
    icmp_ln887_2_fu_753_p2 = (!p_0584_0_reg_372.read().is_01() || !ap_const_lv7_40.is_01())? sc_lv<1>(): sc_lv<1>(p_0584_0_reg_372.read() == ap_const_lv7_40);
}

void top::thread_icmp_ln887_fu_531_p2() {
    icmp_ln887_fu_531_p2 = (!p_0218_0_reg_350.read().is_01() || !ap_const_lv7_40.is_01())? sc_lv<1>(): sc_lv<1>(p_0218_0_reg_350.read() == ap_const_lv7_40);
}

void top::thread_img_idx_V_fu_643_p2() {
    img_idx_V_fu_643_p2 = (!p_0700_0_reg_328.read().is_01() || !ap_const_lv16_1.is_01())? sc_lv<16>(): (sc_biguint<16>(p_0700_0_reg_328.read()) + sc_biguint<16>(ap_const_lv16_1));
}

void top::thread_img_off_V_fu_632_p2() {
    img_off_V_fu_632_p2 = (!p_0868_0_reg_339.read().is_01() || !ap_const_lv10_1.is_01())? sc_lv<10>(): (sc_biguint<10>(p_0868_0_reg_339.read()) + sc_biguint<10>(ap_const_lv10_1));
}

void top::thread_kh_i_V_address0() {
    kh_i_V_address0 =  (sc_lv<6>) (zext_ln544_4_fu_765_p1.read());
}

void top::thread_kh_i_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp2_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp2_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter0.read()))) {
        kh_i_V_ce0 = ap_const_logic_1;
    } else {
        kh_i_V_ce0 = ap_const_logic_0;
    }
}

void top::thread_kh_mem_V_address0() {
    if ((esl_seteq<1,1,1>(icmp_ln879_1_reg_946.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(icmp_ln879_reg_937.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()))) {
        kh_mem_V_address0 = ap_const_lv6_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp2_stage0.read()) && 
                esl_seteq<1,1,1>(ap_block_pp2_stage0.read(), ap_const_boolean_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter1.read()))) {
        kh_mem_V_address0 =  (sc_lv<6>) (zext_ln544_4_reg_1032.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        kh_mem_V_address0 = grp_bin_dense_fu_423_kh_mem_V_2_address0.read();
    } else {
        kh_mem_V_address0 =  (sc_lv<6>) ("XXXXXX");
    }
}

void top::thread_kh_mem_V_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp2_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp2_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter1.read())) || 
         (esl_seteq<1,1,1>(icmp_ln879_1_reg_946.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(icmp_ln879_reg_937.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())))) {
        kh_mem_V_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        kh_mem_V_ce0 = grp_bin_dense_fu_423_kh_mem_V_2_ce0.read();
    } else {
        kh_mem_V_ce0 = ap_const_logic_0;
    }
}

void top::thread_kh_mem_V_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp2_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp2_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln887_2_reg_1023.read()))) {
        kh_mem_V_we0 = ap_const_logic_1;
    } else {
        kh_mem_V_we0 = ap_const_logic_0;
    }
}

void top::thread_layer_type_V_fu_437_p4() {
    layer_type_V_fu_437_p4 = layer_mode_V.read().range(2, 1);
}

void top::thread_nc_V_fu_816_p3() {
    nc_V_fu_816_p3 = (!t_V_reg_906.read()[0].is_01())? sc_lv<16>(): ((t_V_reg_906.read()[0].to_bool())? tmp_V_1_fu_788_p4.read(): select_ln879_fu_808_p3.read());
}

void top::thread_or_ln879_fu_779_p2() {
    or_ln879_fu_779_p2 = (trunc_ln792_reg_896.read() | xor_ln879_fu_774_p2.read());
}

void top::thread_p_Result_s_fu_451_p2() {
    p_Result_s_fu_451_p2 = (trunc_ln792_fu_447_p1.read() ^ ap_const_lv1_1);
}

void top::thread_r_V_2_fu_487_p2() {
    r_V_2_fu_487_p2 = (dmem_mode_V.read() ^ ap_const_lv1_1);
}

void top::thread_r_V_fu_589_p2() {
    r_V_fu_589_p2 = (!zext_ln769_reg_932.read().is_01())? sc_lv<16>(): ret_V_8_fu_585_p1.read() << (unsigned short)zext_ln769_reg_932.read().to_uint();
}

void top::thread_ret_V_3_fu_551_p1() {
    ret_V_3_fu_551_p1 = p_0218_0_reg_350.read().range(6-1, 0);
}

void top::thread_ret_V_4_fu_665_p1() {
    ret_V_4_fu_665_p1 = esl_zext<7,6>(ret_V_6_reg_969.read());
}

void top::thread_ret_V_5_fu_547_p1() {
    ret_V_5_fu_547_p1 = p_0218_0_reg_350.read().range(1-1, 0);
}

void top::thread_ret_V_7_fu_543_p1() {
    ret_V_7_fu_543_p1 = p_0700_0_reg_328.read().range(1-1, 0);
}

void top::thread_ret_V_8_fu_585_p1() {
    ret_V_8_fu_585_p1 = esl_zext<16,15>(ret_V_9_fu_575_p4.read());
}

void top::thread_ret_V_9_fu_575_p4() {
    ret_V_9_fu_575_p4 = p_0700_0_reg_328.read().range(15, 1);
}

void top::thread_ret_V_fu_712_p1() {
    ret_V_fu_712_p1 = p_0481_0_reg_361.read().range(1-1, 0);
}

void top::thread_select_ln180_fu_730_p3() {
    select_ln180_fu_730_p3 = (!ret_V_fu_712_p1.read()[0].is_01())? sc_lv<13>(): ((ret_V_fu_712_p1.read()[0].to_bool())? ap_const_lv13_925: ap_const_lv13_0);
}

void top::thread_select_ln700_fu_824_p3() {
    select_ln700_fu_824_p3 = (!t_V_reg_906.read()[0].is_01())? sc_lv<16>(): ((t_V_reg_906.read()[0].to_bool())? ap_const_lv16_2: ap_const_lv16_1);
}

void top::thread_select_ln784_1_fu_657_p3() {
    select_ln784_1_fu_657_p3 = (!icmp_ln879_2_fu_638_p2.read()[0].is_01())? sc_lv<10>(): ((icmp_ln879_2_fu_638_p2.read()[0].to_bool())? ap_const_lv10_0: img_off_V_fu_632_p2.read());
}

void top::thread_select_ln784_fu_649_p3() {
    select_ln784_fu_649_p3 = (!icmp_ln879_2_fu_638_p2.read()[0].is_01())? sc_lv<16>(): ((icmp_ln879_2_fu_638_p2.read()[0].to_bool())? img_idx_V_fu_643_p2.read(): p_0700_0_reg_328.read());
}

void top::thread_select_ln879_fu_808_p3() {
    select_ln879_fu_808_p3 = (!or_ln879_fu_779_p2.read()[0].is_01())? sc_lv<16>(): ((or_ln879_fu_779_p2.read()[0].to_bool())? tmp_V_fu_784_p1.read(): tmp_V_2_fu_798_p4.read());
}

void top::thread_shl_ln_fu_493_p3() {
    shl_ln_fu_493_p3 = esl_concat<2,1>(width_mode_V.read(), ap_const_lv1_0);
}

void top::thread_t_V_1_fu_479_p3() {
    t_V_1_fu_479_p3 = (!trunc_ln792_fu_447_p1.read()[0].is_01())? sc_lv<16>(): ((trunc_ln792_fu_447_p1.read()[0].to_bool())? ap_const_lv16_0: o_index_V.read());
}

void top::thread_t_V_fu_469_p2() {
    t_V_fu_469_p2 = (trunc_ln700_fu_461_p1.read() & p_Result_s_fu_451_p2.read());
}

void top::thread_tmp_3_fu_608_p4() {
    tmp_3_fu_608_p4 = esl_concat<2,10>(esl_concat<1,1>(dmem_mode_V.read(), ret_V_7_fu_543_p1.read()), ap_const_lv10_0);
}

void top::thread_tmp_4_fu_683_p4() {
    tmp_4_fu_683_p4 = esl_concat<6,6>(esl_concat<1,5>(dmem_mode_V.read(), ap_const_lv5_0), ret_V_3_reg_964.read());
}

void top::thread_tmp_5_fu_668_p5() {
    tmp_5_fu_668_p5 = esl_concat<5,7>(esl_concat<2,3>(esl_concat<1,1>(dmem_mode_V.read(), ret_V_5_reg_959.read()), ap_const_lv3_0), ret_V_4_fu_665_p1.read());
}

void top::thread_tmp_6_fu_836_p3() {
    tmp_6_fu_836_p3 = esl_concat<1,11>(r_V_2_reg_925.read(), ap_const_lv11_0);
}

void top::thread_tmp_7_fu_716_p4() {
    tmp_7_fu_716_p4 = p_0481_0_reg_361.read().range(12, 1);
}

void top::thread_tmp_V_1_fu_788_p4() {
    tmp_V_1_fu_788_p4 = kh_mem_V_q0.read().range(31, 16);
}

void top::thread_tmp_V_2_fu_798_p4() {
    tmp_V_2_fu_798_p4 = kh_mem_V_q0.read().range(63, 48);
}

void top::thread_tmp_V_fu_784_p1() {
    tmp_V_fu_784_p1 = kh_mem_V_q0.read().range(16-1, 0);
}

void top::thread_trunc_ln180_fu_594_p1() {
    trunc_ln180_fu_594_p1 = r_V_fu_589_p2.read().range(14-1, 0);
}

void top::thread_trunc_ln700_fu_461_p1() {
    trunc_ln700_fu_461_p1 = kh_index_V.read().range(1-1, 0);
}

void top::thread_trunc_ln792_fu_447_p1() {
    trunc_ln792_fu_447_p1 = layer_mode_V.read().range(1-1, 0);
}

void top::thread_words_per_image_V_fu_509_p2() {
    words_per_image_V_fu_509_p2 = (!zext_ln769_1_fu_505_p1.read().is_01())? sc_lv<5>(): ap_const_lv5_1 << (unsigned short)zext_ln769_1_fu_505_p1.read().to_uint();
}

void top::thread_wt_i_V_address0() {
    wt_i_V_address0 =  (sc_lv<13>) (zext_ln544_1_fu_744_p1.read());
}

void top::thread_wt_i_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()))) {
        wt_i_V_ce0 = ap_const_logic_1;
    } else {
        wt_i_V_ce0 = ap_const_logic_0;
    }
}

void top::thread_wt_mem_V_address0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()))) {
        wt_mem_V_address0 =  (sc_lv<13>) (zext_ln180_6_fu_749_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        wt_mem_V_address0 = grp_bin_dense_fu_423_wt_mem_V_2_address0.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) && 
                esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op171_call_state13.read()))) {
        wt_mem_V_address0 = grp_bin_conv_fu_407_wt_mem_V_4_address0.read();
    } else {
        wt_mem_V_address0 =  (sc_lv<13>) ("XXXXXXXXXXXXX");
    }
}

void top::thread_wt_mem_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()))) {
        wt_mem_V_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        wt_mem_V_ce0 = grp_bin_dense_fu_423_wt_mem_V_2_ce0.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) && 
                esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op171_call_state13.read()))) {
        wt_mem_V_ce0 = grp_bin_conv_fu_407_wt_mem_V_4_ce0.read();
    } else {
        wt_mem_V_ce0 = ap_const_logic_0;
    }
}

void top::thread_wt_mem_V_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln887_1_reg_1004.read()))) {
        wt_mem_V_we0 = ap_const_logic_1;
    } else {
        wt_mem_V_we0 = ap_const_logic_0;
    }
}

void top::thread_xor_ln879_fu_774_p2() {
    xor_ln879_fu_774_p2 = (trunc_ln700_reg_901.read() ^ ap_const_lv1_1);
}

void top::thread_zext_ln1372_fu_726_p1() {
    zext_ln1372_fu_726_p1 = esl_zext<13,12>(tmp_7_fu_716_p4.read());
}

void top::thread_zext_ln180_1_fu_691_p1() {
    zext_ln180_1_fu_691_p1 = esl_zext<64,12>(tmp_4_fu_683_p4.read());
}

void top::thread_zext_ln180_2_fu_678_p1() {
    zext_ln180_2_fu_678_p1 = esl_zext<64,12>(tmp_5_fu_668_p5.read());
}

void top::thread_zext_ln180_3_fu_843_p1() {
    zext_ln180_3_fu_843_p1 = esl_zext<64,12>(tmp_6_fu_836_p3.read());
}

void top::thread_zext_ln180_4_fu_617_p1() {
    zext_ln180_4_fu_617_p1 = esl_zext<14,12>(tmp_3_fu_608_p4.read());
}

void top::thread_zext_ln180_5_fu_696_p1() {
    zext_ln180_5_fu_696_p1 = esl_zext<64,14>(add_ln180_reg_984.read());
}

void top::thread_zext_ln180_6_fu_749_p1() {
    zext_ln180_6_fu_749_p1 = esl_zext<64,13>(add_ln180_1_reg_1013.read());
}

void top::thread_zext_ln180_fu_598_p1() {
    zext_ln180_fu_598_p1 = esl_zext<14,10>(p_0868_0_reg_339.read());
}

void top::thread_zext_ln544_1_fu_744_p1() {
    zext_ln544_1_fu_744_p1 = esl_zext<64,13>(p_0481_0_reg_361.read());
}

void top::thread_zext_ln544_2_fu_570_p1() {
    zext_ln544_2_fu_570_p1 = esl_zext<64,7>(p_0218_0_reg_350.read());
}

void top::thread_zext_ln544_3_fu_565_p1() {
    zext_ln544_3_fu_565_p1 = esl_zext<64,7>(p_0218_0_reg_350.read());
}

void top::thread_zext_ln544_4_fu_765_p1() {
    zext_ln544_4_fu_765_p1 = esl_zext<64,7>(p_0584_0_reg_372.read());
}

void top::thread_zext_ln544_fu_627_p1() {
    zext_ln544_fu_627_p1 = esl_zext<64,7>(p_0218_0_reg_350.read());
}

void top::thread_zext_ln758_fu_475_p1() {
    zext_ln758_fu_475_p1 = esl_zext<16,1>(t_V_fu_469_p2.read());
}

void top::thread_zext_ln769_1_fu_505_p1() {
    zext_ln769_1_fu_505_p1 = esl_zext<5,3>(shl_ln_fu_493_p3.read());
}

void top::thread_zext_ln769_fu_501_p1() {
    zext_ln769_fu_501_p1 = esl_zext<16,3>(shl_ln_fu_493_p3.read());
}

void top::thread_zext_ln879_fu_521_p1() {
    zext_ln879_fu_521_p1 = esl_zext<10,5>(words_per_image_V_fu_509_p2.read());
}

void top::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln887_fu_531_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln887_fu_531_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            break;
        case 8 : 
            if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln887_1_fu_700_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln887_1_fu_700_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state7;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            break;
        case 32 : 
            if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp2_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln887_2_fu_753_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp2_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln887_2_fu_753_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state10;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            }
            break;
        case 64 : 
            if ((esl_seteq<1,1,1>(icmp_ln879_1_reg_946.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()))) {
                ap_NS_fsm = ap_ST_fsm_state13;
            } else if ((esl_seteq<1,1,1>(icmp_ln879_1_reg_946.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(icmp_ln879_reg_937.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()))) {
                ap_NS_fsm = ap_ST_fsm_state12;
            } else {
                ap_NS_fsm = ap_ST_fsm_state11;
            }
            break;
        case 128 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && esl_seteq<1,1,1>(grp_bin_dense_fu_423_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state13;
            } else {
                ap_NS_fsm = ap_ST_fsm_state11;
            }
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 512 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) && esl_seteq<1,1,1>(ap_block_state13_on_subcall_done.read(), ap_const_boolean_0))) {
                ap_NS_fsm = ap_ST_fsm_state14;
            } else {
                ap_NS_fsm = ap_ST_fsm_state13;
            }
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm = "XXXXXXXXXXXX";
            break;
    }
}

void top::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"wt_i_V_address0\" :  \"" << wt_i_V_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"wt_i_V_ce0\" :  \"" << wt_i_V_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"wt_i_V_q0\" :  \"" << wt_i_V_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"kh_i_V_address0\" :  \"" << kh_i_V_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"kh_i_V_ce0\" :  \"" << kh_i_V_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"kh_i_V_q0\" :  \"" << kh_i_V_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"dmem_i_V_address0\" :  \"" << dmem_i_V_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"dmem_i_V_ce0\" :  \"" << dmem_i_V_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"dmem_i_V_q0\" :  \"" << dmem_i_V_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"dmem_o_V_address0\" :  \"" << dmem_o_V_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"dmem_o_V_ce0\" :  \"" << dmem_o_V_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"dmem_o_V_we0\" :  \"" << dmem_o_V_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"dmem_o_V_d0\" :  \"" << dmem_o_V_d0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"n_inputs_V\" :  \"" << n_inputs_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"n_outputs_V\" :  \"" << n_outputs_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"input_words_V\" :  \"" << input_words_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"output_words_V\" :  \"" << output_words_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"layer_mode_V\" :  \"" << layer_mode_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"dmem_mode_V\" :  \"" << dmem_mode_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"width_mode_V\" :  \"" << width_mode_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"norm_mode_V\" :  \"" << norm_mode_V.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

