// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="top,hls_ip_2019_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7k70t-fbv676-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=9.918000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=61,HLS_SYN_DSP=4,HLS_SYN_FF=3506,HLS_SYN_LUT=13740,HLS_VERSION=2019_1}" *)

module top (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        wt_i_V_address0,
        wt_i_V_ce0,
        wt_i_V_q0,
        kh_i_V_address0,
        kh_i_V_ce0,
        kh_i_V_q0,
        dmem_i_V_address0,
        dmem_i_V_ce0,
        dmem_i_V_q0,
        dmem_o_V_address0,
        dmem_o_V_ce0,
        dmem_o_V_we0,
        dmem_o_V_d0,
        n_inputs_V,
        n_outputs_V,
        input_words_V,
        output_words_V,
        layer_mode_V,
        dmem_mode_V,
        width_mode_V,
        norm_mode_V
);

parameter    ap_ST_fsm_state1 = 13'd1;
parameter    ap_ST_fsm_state2 = 13'd2;
parameter    ap_ST_fsm_state3 = 13'd4;
parameter    ap_ST_fsm_state4 = 13'd8;
parameter    ap_ST_fsm_state5 = 13'd16;
parameter    ap_ST_fsm_state6 = 13'd32;
parameter    ap_ST_fsm_state7 = 13'd64;
parameter    ap_ST_fsm_state8 = 13'd128;
parameter    ap_ST_fsm_state9 = 13'd256;
parameter    ap_ST_fsm_state10 = 13'd512;
parameter    ap_ST_fsm_state11 = 13'd1024;
parameter    ap_ST_fsm_state12 = 13'd2048;
parameter    ap_ST_fsm_state13 = 13'd4096;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [12:0] wt_i_V_address0;
output   wt_i_V_ce0;
input  [63:0] wt_i_V_q0;
output  [5:0] kh_i_V_address0;
output   kh_i_V_ce0;
input  [63:0] kh_i_V_q0;
output  [10:0] dmem_i_V_address0;
output   dmem_i_V_ce0;
input  [63:0] dmem_i_V_q0;
output  [6:0] dmem_o_V_address0;
output   dmem_o_V_ce0;
output   dmem_o_V_we0;
output  [63:0] dmem_o_V_d0;
input  [15:0] n_inputs_V;
input  [15:0] n_outputs_V;
input  [15:0] input_words_V;
input  [15:0] output_words_V;
input  [2:0] layer_mode_V;
input  [0:0] dmem_mode_V;
input  [1:0] width_mode_V;
input  [1:0] norm_mode_V;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg wt_i_V_ce0;
reg kh_i_V_ce0;
reg[10:0] dmem_i_V_address0;
reg dmem_i_V_ce0;
reg[6:0] dmem_o_V_address0;
reg dmem_o_V_ce0;
reg dmem_o_V_we0;

(* fsm_encoding = "none" *) reg   [12:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [15:0] kh_index_V;
reg   [15:0] o_index_V;
reg   [11:0] dmem_V_address0;
reg    dmem_V_ce0;
reg    dmem_V_we0;
reg   [63:0] dmem_V_d0;
wire   [63:0] dmem_V_q0;
reg   [12:0] wt_mem_V_address0;
reg    wt_mem_V_ce0;
reg    wt_mem_V_we0;
wire   [63:0] wt_mem_V_q0;
reg   [5:0] kh_mem_V_address0;
reg    kh_mem_V_ce0;
reg    kh_mem_V_we0;
wire   [63:0] kh_mem_V_q0;
reg   [15:0] reg_561;
wire    ap_CS_fsm_state6;
reg   [0:0] icmp_ln879_reg_1393;
reg   [0:0] icmp_ln879_1_reg_1407;
wire   [0:0] icmp_ln887_1_fu_911_p2;
wire   [1:0] layer_type_V_fu_567_p4;
reg   [1:0] layer_type_V_reg_1361;
wire   [0:0] r_V_2_fu_608_p2;
reg   [0:0] r_V_2_reg_1369;
wire   [15:0] zext_ln746_fu_622_p1;
reg   [15:0] zext_ln746_reg_1378;
wire   [6:0] shl_ln746_fu_630_p2;
reg   [6:0] shl_ln746_reg_1383;
wire   [4:0] words_per_image_V_fu_636_p1;
reg   [4:0] words_per_image_V_reg_1388;
wire   [0:0] icmp_ln879_fu_640_p2;
wire   [6:0] zext_ln879_1_fu_654_p1;
reg   [6:0] zext_ln879_1_reg_1397;
wire   [9:0] zext_ln879_fu_658_p1;
reg   [9:0] zext_ln879_reg_1402;
wire   [0:0] icmp_ln879_1_fu_662_p2;
wire   [9:0] ret_V_2_fu_672_p1;
reg   [9:0] ret_V_2_reg_1411;
wire    ap_CS_fsm_state2;
wire   [15:0] i_V_2_fu_681_p2;
reg   [15:0] i_V_2_reg_1419;
wire   [13:0] add_ln180_3_fu_710_p2;
reg   [13:0] add_ln180_3_reg_1424;
wire   [0:0] icmp_ln749_fu_676_p2;
wire   [6:0] add_ln180_2_fu_735_p2;
reg   [6:0] add_ln180_2_reg_1434;
wire   [13:0] trunc_ln749_2_fu_764_p1;
reg   [13:0] trunc_ln749_2_reg_1444;
wire   [15:0] select_ln760_fu_842_p3;
wire    ap_CS_fsm_state3;
wire   [9:0] select_ln760_1_fu_850_p3;
wire   [12:0] i_V_fu_868_p2;
reg   [12:0] i_V_reg_1467;
wire    ap_CS_fsm_state4;
wire   [12:0] add_ln180_1_fu_896_p2;
reg   [12:0] add_ln180_1_reg_1472;
wire   [0:0] icmp_ln887_fu_862_p2;
wire   [6:0] i_V_1_fu_917_p2;
reg   [6:0] i_V_1_reg_1485;
wire   [63:0] zext_ln544_4_fu_923_p1;
reg   [63:0] zext_ln544_4_reg_1490;
wire   [9:0] i_V_3_fu_937_p2;
reg   [9:0] i_V_3_reg_1503;
wire    ap_CS_fsm_state8;
wire    grp_bin_dense_fu_523_ap_ready;
wire    grp_bin_dense_fu_523_ap_done;
reg    ap_predicate_op160_call_state8;
wire    grp_fp_conv_fu_507_ap_ready;
wire    grp_fp_conv_fu_507_ap_done;
reg    ap_block_state8_on_subcall_done;
wire   [0:0] icmp_ln887_2_fu_932_p2;
wire   [1:0] off_V_fu_958_p1;
reg   [1:0] off_V_reg_1513;
wire   [0:0] icmp_ln879_3_fu_962_p2;
reg   [0:0] icmp_ln879_3_reg_1520;
wire   [13:0] zext_ln838_fu_1004_p1;
reg   [13:0] zext_ln838_reg_1525;
wire   [9:0] zext_ln841_fu_1008_p1;
reg   [9:0] zext_ln841_reg_1530;
wire   [0:0] or_ln841_1_fu_1036_p2;
reg   [0:0] or_ln841_1_reg_1535;
wire   [15:0] nc_V_fu_1143_p3;
reg   [15:0] nc_V_reg_1539;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
wire   [15:0] i_V_4_fu_1184_p2;
reg   [15:0] i_V_4_reg_1552;
wire    ap_CS_fsm_state12;
wire   [63:0] zext_ln544_6_fu_1190_p1;
reg   [63:0] zext_ln544_6_reg_1557;
wire   [0:0] icmp_ln838_fu_1179_p2;
wire   [15:0] select_ln849_fu_1286_p3;
wire    ap_CS_fsm_state13;
wire   [9:0] select_ln849_1_fu_1294_p3;
wire    grp_bin_conv_fu_485_ap_start;
wire    grp_bin_conv_fu_485_ap_done;
wire    grp_bin_conv_fu_485_ap_idle;
wire    grp_bin_conv_fu_485_ap_ready;
wire   [12:0] grp_bin_conv_fu_485_wt_mem_V_6_address0;
wire    grp_bin_conv_fu_485_wt_mem_V_6_ce0;
wire   [11:0] grp_bin_conv_fu_485_dmem_V_6_address0;
wire    grp_bin_conv_fu_485_dmem_V_6_ce0;
wire    grp_bin_conv_fu_485_dmem_V_6_we0;
wire   [63:0] grp_bin_conv_fu_485_dmem_V_6_d0;
wire    grp_fp_conv_fu_507_ap_start;
wire    grp_fp_conv_fu_507_ap_idle;
wire   [12:0] grp_fp_conv_fu_507_wt_mem_V_2_address0;
wire    grp_fp_conv_fu_507_wt_mem_V_2_ce0;
wire   [5:0] grp_fp_conv_fu_507_kh_mem_V_2_address0;
wire    grp_fp_conv_fu_507_kh_mem_V_2_ce0;
wire   [11:0] grp_fp_conv_fu_507_dmem_V_2_address0;
wire    grp_fp_conv_fu_507_dmem_V_2_ce0;
wire    grp_fp_conv_fu_507_dmem_V_2_we0;
wire   [63:0] grp_fp_conv_fu_507_dmem_V_2_d0;
wire    grp_bin_dense_fu_523_ap_start;
wire    grp_bin_dense_fu_523_ap_idle;
wire   [12:0] grp_bin_dense_fu_523_wt_mem_V_4_address0;
wire    grp_bin_dense_fu_523_wt_mem_V_4_ce0;
wire   [5:0] grp_bin_dense_fu_523_kh_mem_V_4_address0;
wire    grp_bin_dense_fu_523_kh_mem_V_4_ce0;
wire   [11:0] grp_bin_dense_fu_523_dmem_V_4_address0;
wire    grp_bin_dense_fu_523_dmem_V_4_ce0;
wire    grp_bin_dense_fu_523_dmem_V_4_we0;
wire   [63:0] grp_bin_dense_fu_523_dmem_V_4_d0;
wire   [0:0] trunc_ln791_fu_581_p1;
reg   [0:0] p_013_reg_371;
wire   [0:0] trunc_ln792_fu_577_p1;
reg   [15:0] p_0713_0_reg_382;
reg   [9:0] p_0882_0_reg_394;
reg   [15:0] p_0232_0_reg_406;
reg   [12:0] p_0502_0_reg_417;
wire    ap_CS_fsm_state5;
reg   [6:0] p_0604_0_reg_428;
wire    ap_CS_fsm_state7;
reg   [9:0] p_0660_0_reg_439;
wire    ap_CS_fsm_state11;
reg   [15:0] p_0713_2_reg_450;
reg   [9:0] p_0882_2_reg_462;
reg   [15:0] p_0703_0_reg_474;
reg    grp_bin_conv_fu_485_ap_start_reg;
reg    grp_fp_conv_fu_507_ap_start_reg;
reg    grp_bin_dense_fu_523_ap_start_reg;
wire   [63:0] zext_ln544_3_fu_716_p1;
wire   [63:0] zext_ln544_2_fu_740_p1;
wire   [63:0] zext_ln544_fu_768_p1;
wire   [63:0] zext_ln180_6_fu_773_p1;
wire   [63:0] zext_ln180_4_fu_783_p1;
wire   [63:0] zext_ln180_1_fu_820_p1;
wire   [63:0] zext_ln544_1_fu_902_p1;
wire   [63:0] zext_ln180_2_fu_907_p1;
wire   [63:0] zext_ln544_5_fu_953_p1;
wire   [63:0] zext_ln180_10_fu_1230_p1;
wire   [63:0] zext_ln180_8_fu_1264_p1;
wire   [6:0] dmem_o_V_addr_gep_fu_363_p3;
wire   [15:0] zext_ln791_fu_586_p1;
wire   [15:0] add_ln700_fu_968_p2;
wire   [15:0] add_ln700_3_fu_1151_p2;
wire   [15:0] grp_fu_550_p2;
wire   [15:0] add_ln700_4_fu_1163_p2;
wire   [2:0] shl_ln_fu_614_p3;
wire   [6:0] zext_ln746_1_fu_626_p1;
wire   [1:0] tmp_fu_646_p3;
wire   [0:0] ret_V_3_fu_668_p1;
wire   [11:0] tmp_4_fu_697_p4;
wire   [13:0] zext_ln180_5_fu_706_p1;
wire   [13:0] zext_ln544_6_cast_fu_687_p4;
wire   [5:0] tmp_7_fu_721_p4;
wire   [6:0] zext_ln180_3_fu_731_p1;
wire   [14:0] ret_V_s_fu_745_p4;
wire   [15:0] ret_V_5_fu_755_p1;
wire   [15:0] r_V_fu_759_p2;
wire   [16:0] tmp_8_fu_777_p3;
wire   [13:0] zext_ln749_fu_788_p1;
wire   [0:0] trunc_ln749_3_fu_797_p1;
wire   [11:0] tmp_1_fu_801_p4;
wire   [13:0] add_ln749_fu_792_p2;
wire   [13:0] zext_ln180_fu_810_p1;
wire   [13:0] add_ln180_fu_814_p2;
wire   [9:0] img_off_V_fu_825_p2;
wire   [0:0] icmp_ln879_2_fu_831_p2;
wire   [15:0] img_idx_V_fu_836_p2;
wire   [11:0] tmp_2_fu_874_p4;
wire   [0:0] ret_V_fu_858_p1;
wire   [12:0] zext_ln1372_fu_884_p1;
wire   [12:0] select_ln180_fu_888_p3;
wire   [15:0] zext_ln887_fu_928_p1;
wire   [13:0] ret_V_9_fu_943_p4;
wire   [2:0] lshr_ln_fu_984_p4;
wire   [0:0] icmp_ln883_fu_979_p2;
wire   [4:0] zext_ln1371_fu_993_p1;
wire   [4:0] words_per_out_V_fu_997_p3;
wire   [0:0] icmp_ln841_fu_1012_p2;
wire   [0:0] or_ln841_fu_1017_p2;
wire   [0:0] tmp_9_fu_1023_p3;
wire   [0:0] xor_ln841_fu_1030_p2;
wire   [0:0] icmp_ln879_5_fu_1042_p2;
wire   [0:0] icmp_ln879_6_fu_1051_p2;
wire   [0:0] xor_ln879_fu_1091_p2;
wire   [0:0] or_ln879_fu_1103_p2;
wire   [0:0] icmp_ln879_7_fu_1066_p2;
wire   [0:0] xor_ln879_1_fu_1109_p2;
wire   [0:0] and_ln879_1_fu_1115_p2;
wire   [15:0] tmp_V_2_fu_1071_p4;
wire   [15:0] tmp_V_1_fu_1056_p4;
wire   [0:0] and_ln879_fu_1097_p2;
wire   [15:0] tmp_V_fu_1047_p1;
wire   [15:0] tmp_V_3_fu_1081_p4;
wire   [0:0] or_ln879_1_fu_1129_p2;
wire   [15:0] select_ln879_fu_1121_p3;
wire   [15:0] select_ln879_1_fu_1135_p3;
wire   [0:0] trunc_ln838_fu_1208_p1;
wire   [11:0] tmp_6_fu_1212_p4;
wire  signed [13:0] grp_fu_1302_p3;
wire   [13:0] zext_ln180_9_fu_1221_p1;
(* use_dsp48 = "no" *) wire   [13:0] add_ln180_5_fu_1225_p2;
wire   [0:0] ret_V_4_fu_1175_p1;
wire   [11:0] tmp_5_fu_1245_p4;
wire   [13:0] zext_ln180_7_fu_1254_p1;
wire   [13:0] zext_ln544_12_cast_fu_1235_p4;
wire   [13:0] add_ln180_4_fu_1258_p2;
wire   [9:0] img_off_V_1_fu_1269_p2;
wire   [0:0] icmp_ln879_4_fu_1275_p2;
wire   [15:0] img_idx_V_1_fu_1280_p2;
wire  signed [13:0] grp_fu_1302_p0;
wire   [4:0] grp_fu_1302_p1;
wire   [9:0] grp_fu_1302_p2;
reg   [12:0] ap_NS_fsm;
wire   [13:0] grp_fu_1302_p20;

// power-on initialization
initial begin
#0 ap_CS_fsm = 13'd1;
#0 kh_index_V = 16'd0;
#0 o_index_V = 16'd0;
#0 grp_bin_conv_fu_485_ap_start_reg = 1'b0;
#0 grp_fp_conv_fu_507_ap_start_reg = 1'b0;
#0 grp_bin_dense_fu_523_ap_start_reg = 1'b0;
end

top_dmem_V #(
    .DataWidth( 64 ),
    .AddressRange( 4096 ),
    .AddressWidth( 12 ))
dmem_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(dmem_V_address0),
    .ce0(dmem_V_ce0),
    .we0(dmem_V_we0),
    .d0(dmem_V_d0),
    .q0(dmem_V_q0)
);

top_wt_mem_V #(
    .DataWidth( 64 ),
    .AddressRange( 4682 ),
    .AddressWidth( 13 ))
wt_mem_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(wt_mem_V_address0),
    .ce0(wt_mem_V_ce0),
    .we0(wt_mem_V_we0),
    .d0(wt_i_V_q0),
    .q0(wt_mem_V_q0)
);

top_kh_mem_V #(
    .DataWidth( 64 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
kh_mem_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(kh_mem_V_address0),
    .ce0(kh_mem_V_ce0),
    .we0(kh_mem_V_we0),
    .d0(kh_i_V_q0),
    .q0(kh_mem_V_q0)
);

bin_conv grp_bin_conv_fu_485(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_bin_conv_fu_485_ap_start),
    .ap_done(grp_bin_conv_fu_485_ap_done),
    .ap_idle(grp_bin_conv_fu_485_ap_idle),
    .ap_ready(grp_bin_conv_fu_485_ap_ready),
    .wt_mem_V_6_address0(grp_bin_conv_fu_485_wt_mem_V_6_address0),
    .wt_mem_V_6_ce0(grp_bin_conv_fu_485_wt_mem_V_6_ce0),
    .wt_mem_V_6_q0(wt_mem_V_q0),
    .nc_V(nc_V_reg_1539),
    .dmem_V_6_address0(grp_bin_conv_fu_485_dmem_V_6_address0),
    .dmem_V_6_ce0(grp_bin_conv_fu_485_dmem_V_6_ce0),
    .dmem_V_6_we0(grp_bin_conv_fu_485_dmem_V_6_we0),
    .dmem_V_6_d0(grp_bin_conv_fu_485_dmem_V_6_d0),
    .dmem_V_6_q0(dmem_V_q0),
    .d_i_idx_V(dmem_mode_V),
    .d_o_idx_V(r_V_2_reg_1369),
    .n_inputs(n_inputs_V),
    .o_index_V_6(o_index_V),
    .new_batch_V(icmp_ln879_3_reg_1520),
    .width_mode_V(width_mode_V),
    .norm_mode_V(norm_mode_V)
);

fp_conv grp_fp_conv_fu_507(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_fp_conv_fu_507_ap_start),
    .ap_done(grp_fp_conv_fu_507_ap_done),
    .ap_idle(grp_fp_conv_fu_507_ap_idle),
    .ap_ready(grp_fp_conv_fu_507_ap_ready),
    .wt_mem_V_2_address0(grp_fp_conv_fu_507_wt_mem_V_2_address0),
    .wt_mem_V_2_ce0(grp_fp_conv_fu_507_wt_mem_V_2_ce0),
    .wt_mem_V_2_q0(wt_mem_V_q0),
    .kh_mem_V_2_address0(grp_fp_conv_fu_507_kh_mem_V_2_address0),
    .kh_mem_V_2_ce0(grp_fp_conv_fu_507_kh_mem_V_2_ce0),
    .kh_mem_V_2_q0(kh_mem_V_q0),
    .dmem_V_2_address0(grp_fp_conv_fu_507_dmem_V_2_address0),
    .dmem_V_2_ce0(grp_fp_conv_fu_507_dmem_V_2_ce0),
    .dmem_V_2_we0(grp_fp_conv_fu_507_dmem_V_2_we0),
    .dmem_V_2_d0(grp_fp_conv_fu_507_dmem_V_2_d0),
    .dmem_V_2_q0(dmem_V_q0),
    .d_i_idx_V(dmem_mode_V),
    .d_o_idx_V(r_V_2_reg_1369),
    .kh_index_V_2(p_013_reg_371),
    .o_index_V_2(reg_561),
    .N(n_outputs_V)
);

bin_dense grp_bin_dense_fu_523(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_bin_dense_fu_523_ap_start),
    .ap_done(grp_bin_dense_fu_523_ap_done),
    .ap_idle(grp_bin_dense_fu_523_ap_idle),
    .ap_ready(grp_bin_dense_fu_523_ap_ready),
    .wt_mem_V_4_address0(grp_bin_dense_fu_523_wt_mem_V_4_address0),
    .wt_mem_V_4_ce0(grp_bin_dense_fu_523_wt_mem_V_4_ce0),
    .wt_mem_V_4_q0(wt_mem_V_q0),
    .kh_mem_V_4_address0(grp_bin_dense_fu_523_kh_mem_V_4_address0),
    .kh_mem_V_4_ce0(grp_bin_dense_fu_523_kh_mem_V_4_ce0),
    .kh_mem_V_4_q0(kh_mem_V_q0),
    .dmem_V_4_address0(grp_bin_dense_fu_523_dmem_V_4_address0),
    .dmem_V_4_ce0(grp_bin_dense_fu_523_dmem_V_4_ce0),
    .dmem_V_4_we0(grp_bin_dense_fu_523_dmem_V_4_we0),
    .dmem_V_4_d0(grp_bin_dense_fu_523_dmem_V_4_d0),
    .dmem_V_4_q0(dmem_V_q0),
    .layer_type_V(layer_type_V_reg_1361),
    .d_i_idx_V(dmem_mode_V),
    .d_o_idx_V(r_V_2_reg_1369),
    .o_index_V_4(reg_561),
    .n_inputs(n_inputs_V),
    .n_outputs(n_outputs_V)
);

top_mac_muladd_14lbW #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 5 ),
    .din2_WIDTH( 10 ),
    .dout_WIDTH( 14 ))
top_mac_muladd_14lbW_U62(
    .din0(grp_fu_1302_p0),
    .din1(grp_fu_1302_p1),
    .din2(grp_fu_1302_p2),
    .dout(grp_fu_1302_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_bin_conv_fu_485_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state10)) begin
            grp_bin_conv_fu_485_ap_start_reg <= 1'b1;
        end else if ((grp_bin_conv_fu_485_ap_ready == 1'b1)) begin
            grp_bin_conv_fu_485_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_bin_dense_fu_523_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln887_1_fu_911_p2 == 1'd1) & (icmp_ln879_1_reg_1407 == 1'd0) & (icmp_ln879_reg_1393 == 1'd0))) begin
            grp_bin_dense_fu_523_ap_start_reg <= 1'b1;
        end else if ((grp_bin_dense_fu_523_ap_ready == 1'b1)) begin
            grp_bin_dense_fu_523_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_fp_conv_fu_507_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln887_1_fu_911_p2 == 1'd1) & (icmp_ln879_1_reg_1407 == 1'd1))) begin
            grp_fp_conv_fu_507_ap_start_reg <= 1'b1;
        end else if ((grp_fp_conv_fu_507_ap_ready == 1'b1)) begin
            grp_fp_conv_fu_507_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((grp_bin_conv_fu_485_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        kh_index_V <= add_ln700_3_fu_1151_p2;
    end else if (((1'b0 == ap_block_state8_on_subcall_done) & (1'b1 == ap_CS_fsm_state8) & (icmp_ln879_1_reg_1407 == 1'd1))) begin
        kh_index_V <= add_ln700_fu_968_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (trunc_ln792_fu_577_p1 == 1'd1))) begin
        kh_index_V <= 16'd0;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (trunc_ln792_fu_577_p1 == 1'd0))) begin
        kh_index_V <= zext_ln791_fu_586_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_bin_conv_fu_485_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        o_index_V <= add_ln700_4_fu_1163_p2;
    end else if ((((1'b0 == ap_block_state8_on_subcall_done) & (1'b1 == ap_CS_fsm_state8) & (icmp_ln879_1_reg_1407 == 1'd1)) | ((1'b0 == ap_block_state8_on_subcall_done) & (1'b1 == ap_CS_fsm_state8) & (icmp_ln879_1_reg_1407 == 1'd0) & (icmp_ln879_reg_1393 == 1'd0)))) begin
        o_index_V <= grp_fu_550_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (trunc_ln792_fu_577_p1 == 1'd1))) begin
        o_index_V <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        if ((trunc_ln792_fu_577_p1 == 1'd1)) begin
            p_013_reg_371 <= 1'd0;
        end else if ((trunc_ln792_fu_577_p1 == 1'd0)) begin
            p_013_reg_371 <= trunc_ln791_fu_581_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        p_0232_0_reg_406 <= i_V_2_reg_1419;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        p_0232_0_reg_406 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln749_fu_676_p2 == 1'd1))) begin
        p_0502_0_reg_417 <= 13'd0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        p_0502_0_reg_417 <= i_V_reg_1467;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln887_fu_862_p2 == 1'd1))) begin
        p_0604_0_reg_428 <= 7'd0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        p_0604_0_reg_428 <= i_V_1_reg_1485;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln887_1_fu_911_p2 == 1'd1) & (icmp_ln879_1_reg_1407 == 1'd0) & (icmp_ln879_reg_1393 == 1'd1))) begin
        p_0660_0_reg_439 <= 10'd0;
    end else if (((grp_bin_conv_fu_485_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        p_0660_0_reg_439 <= i_V_3_reg_1503;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        p_0703_0_reg_474 <= i_V_4_reg_1552;
    end else if (((1'b0 == ap_block_state8_on_subcall_done) & (1'b1 == ap_CS_fsm_state8) & ((icmp_ln879_reg_1393 == 1'd0) | ((icmp_ln879_1_reg_1407 == 1'd1) | (icmp_ln887_2_fu_932_p2 == 1'd0))))) begin
        p_0703_0_reg_474 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        p_0713_0_reg_382 <= select_ln760_fu_842_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        p_0713_0_reg_382 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        p_0713_2_reg_450 <= select_ln849_fu_1286_p3;
    end else if (((1'b0 == ap_block_state8_on_subcall_done) & (1'b1 == ap_CS_fsm_state8) & ((icmp_ln879_reg_1393 == 1'd0) | ((icmp_ln879_1_reg_1407 == 1'd1) | (icmp_ln887_2_fu_932_p2 == 1'd0))))) begin
        p_0713_2_reg_450 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        p_0882_0_reg_394 <= select_ln760_1_fu_850_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        p_0882_0_reg_394 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        p_0882_2_reg_462 <= select_ln849_1_fu_1294_p3;
    end else if (((1'b0 == ap_block_state8_on_subcall_done) & (1'b1 == ap_CS_fsm_state8) & ((icmp_ln879_reg_1393 == 1'd0) | ((icmp_ln879_1_reg_1407 == 1'd1) | (icmp_ln887_2_fu_932_p2 == 1'd0))))) begin
        p_0882_2_reg_462 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln887_fu_862_p2 == 1'd0))) begin
        add_ln180_1_reg_1472 <= add_ln180_1_fu_896_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln879_1_reg_1407 == 1'd1) & (icmp_ln749_fu_676_p2 == 1'd0) & (icmp_ln879_reg_1393 == 1'd0))) begin
        add_ln180_2_reg_1434 <= add_ln180_2_fu_735_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln749_fu_676_p2 == 1'd0) & (icmp_ln879_1_reg_1407 == 1'd0) & (icmp_ln879_reg_1393 == 1'd0))) begin
        add_ln180_3_reg_1424 <= add_ln180_3_fu_710_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        i_V_1_reg_1485 <= i_V_1_fu_917_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_V_2_reg_1419 <= i_V_2_fu_681_p2;
        ret_V_2_reg_1411 <= ret_V_2_fu_672_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state8_on_subcall_done) & (1'b1 == ap_CS_fsm_state8) & (icmp_ln879_1_reg_1407 == 1'd0) & (icmp_ln879_reg_1393 == 1'd1))) begin
        i_V_3_reg_1503 <= i_V_3_fu_937_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        i_V_4_reg_1552 <= i_V_4_fu_1184_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        i_V_reg_1467 <= i_V_fu_868_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        icmp_ln879_1_reg_1407 <= icmp_ln879_1_fu_662_p2;
        icmp_ln879_reg_1393 <= icmp_ln879_fu_640_p2;
        layer_type_V_reg_1361 <= {{layer_mode_V[2:1]}};
        r_V_2_reg_1369 <= r_V_2_fu_608_p2;
        shl_ln746_reg_1383 <= shl_ln746_fu_630_p2;
        words_per_image_V_reg_1388 <= words_per_image_V_fu_636_p1;
        zext_ln746_reg_1378[2 : 1] <= zext_ln746_fu_622_p1[2 : 1];
        zext_ln879_1_reg_1397[1] <= zext_ln879_1_fu_654_p1[1];
        zext_ln879_reg_1402[4 : 0] <= zext_ln879_fu_658_p1[4 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state8_on_subcall_done) & (1'b1 == ap_CS_fsm_state8) & (icmp_ln887_2_fu_932_p2 == 1'd1) & (icmp_ln879_1_reg_1407 == 1'd0) & (icmp_ln879_reg_1393 == 1'd1))) begin
        icmp_ln879_3_reg_1520 <= icmp_ln879_3_fu_962_p2;
        off_V_reg_1513 <= off_V_fu_958_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        nc_V_reg_1539 <= nc_V_fu_1143_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state8_on_subcall_done) & (1'b1 == ap_CS_fsm_state8) & ((icmp_ln879_reg_1393 == 1'd0) | ((icmp_ln879_1_reg_1407 == 1'd1) | (icmp_ln887_2_fu_932_p2 == 1'd0))))) begin
        or_ln841_1_reg_1535 <= or_ln841_1_fu_1036_p2;
        zext_ln838_reg_1525[4 : 0] <= zext_ln838_fu_1004_p1[4 : 0];
        zext_ln841_reg_1530[4 : 0] <= zext_ln841_fu_1008_p1[4 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_state6) & (icmp_ln887_1_fu_911_p2 == 1'd1) & (icmp_ln879_1_reg_1407 == 1'd1)) | ((1'b1 == ap_CS_fsm_state6) & (icmp_ln887_1_fu_911_p2 == 1'd1) & (icmp_ln879_1_reg_1407 == 1'd0) & (icmp_ln879_reg_1393 == 1'd0)))) begin
        reg_561 <= o_index_V;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln749_fu_676_p2 == 1'd0) & (icmp_ln879_reg_1393 == 1'd1))) begin
        trunc_ln749_2_reg_1444 <= trunc_ln749_2_fu_764_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln887_1_fu_911_p2 == 1'd0))) begin
        zext_ln544_4_reg_1490[6 : 0] <= zext_ln544_4_fu_923_p1[6 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state12) & (icmp_ln838_fu_1179_p2 == 1'd0))) begin
        zext_ln544_6_reg_1557[15 : 0] <= zext_ln544_6_fu_1190_p1[15 : 0];
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) & (icmp_ln838_fu_1179_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) & (icmp_ln838_fu_1179_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) & (or_ln841_1_reg_1535 == 1'd1) & (icmp_ln838_fu_1179_p2 == 1'd0))) begin
        dmem_V_address0 = zext_ln180_8_fu_1264_p1;
    end else if (((1'b1 == ap_CS_fsm_state12) & (icmp_ln838_fu_1179_p2 == 1'd0) & (or_ln841_1_reg_1535 == 1'd0))) begin
        dmem_V_address0 = zext_ln180_10_fu_1230_p1;
    end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln879_reg_1393 == 1'd1))) begin
        dmem_V_address0 = zext_ln180_1_fu_820_p1;
    end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln879_1_reg_1407 == 1'd1) & (icmp_ln879_reg_1393 == 1'd0))) begin
        dmem_V_address0 = zext_ln180_4_fu_783_p1;
    end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln879_1_reg_1407 == 1'd0) & (icmp_ln879_reg_1393 == 1'd0))) begin
        dmem_V_address0 = zext_ln180_6_fu_773_p1;
    end else if (((ap_predicate_op160_call_state8 == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        dmem_V_address0 = grp_bin_dense_fu_523_dmem_V_4_address0;
    end else if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln879_1_reg_1407 == 1'd1))) begin
        dmem_V_address0 = grp_fp_conv_fu_507_dmem_V_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        dmem_V_address0 = grp_bin_conv_fu_485_dmem_V_6_address0;
    end else begin
        dmem_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state12) & (or_ln841_1_reg_1535 == 1'd1) & (icmp_ln838_fu_1179_p2 == 1'd0)) | ((1'b1 == ap_CS_fsm_state12) & (icmp_ln838_fu_1179_p2 == 1'd0) & (or_ln841_1_reg_1535 == 1'd0)) | ((1'b1 == ap_CS_fsm_state3) & (icmp_ln879_reg_1393 == 1'd1)) | ((1'b1 == ap_CS_fsm_state3) & (icmp_ln879_1_reg_1407 == 1'd1) & (icmp_ln879_reg_1393 == 1'd0)) | ((1'b1 == ap_CS_fsm_state3) & (icmp_ln879_1_reg_1407 == 1'd0) & (icmp_ln879_reg_1393 == 1'd0)))) begin
        dmem_V_ce0 = 1'b1;
    end else if (((ap_predicate_op160_call_state8 == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        dmem_V_ce0 = grp_bin_dense_fu_523_dmem_V_4_ce0;
    end else if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln879_1_reg_1407 == 1'd1))) begin
        dmem_V_ce0 = grp_fp_conv_fu_507_dmem_V_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        dmem_V_ce0 = grp_bin_conv_fu_485_dmem_V_6_ce0;
    end else begin
        dmem_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state3) & (icmp_ln879_reg_1393 == 1'd1)) | ((1'b1 == ap_CS_fsm_state3) & (icmp_ln879_1_reg_1407 == 1'd1) & (icmp_ln879_reg_1393 == 1'd0)) | ((1'b1 == ap_CS_fsm_state3) & (icmp_ln879_1_reg_1407 == 1'd0) & (icmp_ln879_reg_1393 == 1'd0)))) begin
        dmem_V_d0 = dmem_i_V_q0;
    end else if (((ap_predicate_op160_call_state8 == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        dmem_V_d0 = grp_bin_dense_fu_523_dmem_V_4_d0;
    end else if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln879_1_reg_1407 == 1'd1))) begin
        dmem_V_d0 = grp_fp_conv_fu_507_dmem_V_2_d0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        dmem_V_d0 = grp_bin_conv_fu_485_dmem_V_6_d0;
    end else begin
        dmem_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state3) & (icmp_ln879_reg_1393 == 1'd1)) | ((1'b1 == ap_CS_fsm_state3) & (icmp_ln879_1_reg_1407 == 1'd1) & (icmp_ln879_reg_1393 == 1'd0)) | ((1'b1 == ap_CS_fsm_state3) & (icmp_ln879_1_reg_1407 == 1'd0) & (icmp_ln879_reg_1393 == 1'd0)))) begin
        dmem_V_we0 = 1'b1;
    end else if (((ap_predicate_op160_call_state8 == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        dmem_V_we0 = grp_bin_dense_fu_523_dmem_V_4_we0;
    end else if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln879_1_reg_1407 == 1'd1))) begin
        dmem_V_we0 = grp_fp_conv_fu_507_dmem_V_2_we0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        dmem_V_we0 = grp_bin_conv_fu_485_dmem_V_6_we0;
    end else begin
        dmem_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln749_fu_676_p2 == 1'd0))) begin
        if ((icmp_ln879_reg_1393 == 1'd1)) begin
            dmem_i_V_address0 = zext_ln544_fu_768_p1;
        end else if (((icmp_ln879_1_reg_1407 == 1'd1) & (icmp_ln879_reg_1393 == 1'd0))) begin
            dmem_i_V_address0 = zext_ln544_2_fu_740_p1;
        end else if (((icmp_ln879_1_reg_1407 == 1'd0) & (icmp_ln879_reg_1393 == 1'd0))) begin
            dmem_i_V_address0 = zext_ln544_3_fu_716_p1;
        end else begin
            dmem_i_V_address0 = 'bx;
        end
    end else begin
        dmem_i_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state2) & (icmp_ln749_fu_676_p2 == 1'd0) & (icmp_ln879_reg_1393 == 1'd1)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln879_1_reg_1407 == 1'd1) & (icmp_ln749_fu_676_p2 == 1'd0) & (icmp_ln879_reg_1393 == 1'd0)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln749_fu_676_p2 == 1'd0) & (icmp_ln879_1_reg_1407 == 1'd0) & (icmp_ln879_reg_1393 == 1'd0)))) begin
        dmem_i_V_ce0 = 1'b1;
    end else begin
        dmem_i_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        if ((or_ln841_1_reg_1535 == 1'd1)) begin
            dmem_o_V_address0 = dmem_o_V_addr_gep_fu_363_p3;
        end else if ((or_ln841_1_reg_1535 == 1'd0)) begin
            dmem_o_V_address0 = zext_ln544_6_reg_1557;
        end else begin
            dmem_o_V_address0 = 'bx;
        end
    end else begin
        dmem_o_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state13) & (or_ln841_1_reg_1535 == 1'd1)) | ((1'b1 == ap_CS_fsm_state13) & (or_ln841_1_reg_1535 == 1'd0)))) begin
        dmem_o_V_ce0 = 1'b1;
    end else begin
        dmem_o_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state13) & (or_ln841_1_reg_1535 == 1'd1)) | ((1'b1 == ap_CS_fsm_state13) & (or_ln841_1_reg_1535 == 1'd0)))) begin
        dmem_o_V_we0 = 1'b1;
    end else begin
        dmem_o_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        kh_i_V_ce0 = 1'b1;
    end else begin
        kh_i_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln887_2_fu_932_p2 == 1'd1) & (icmp_ln879_1_reg_1407 == 1'd0) & (icmp_ln879_reg_1393 == 1'd1))) begin
        kh_mem_V_address0 = zext_ln544_5_fu_953_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        kh_mem_V_address0 = zext_ln544_4_reg_1490;
    end else if (((ap_predicate_op160_call_state8 == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        kh_mem_V_address0 = grp_bin_dense_fu_523_kh_mem_V_4_address0;
    end else if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln879_1_reg_1407 == 1'd1))) begin
        kh_mem_V_address0 = grp_fp_conv_fu_507_kh_mem_V_2_address0;
    end else begin
        kh_mem_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | ((1'b0 == ap_block_state8_on_subcall_done) & (1'b1 == ap_CS_fsm_state8) & (icmp_ln887_2_fu_932_p2 == 1'd1) & (icmp_ln879_1_reg_1407 == 1'd0) & (icmp_ln879_reg_1393 == 1'd1)))) begin
        kh_mem_V_ce0 = 1'b1;
    end else if (((ap_predicate_op160_call_state8 == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        kh_mem_V_ce0 = grp_bin_dense_fu_523_kh_mem_V_4_ce0;
    end else if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln879_1_reg_1407 == 1'd1))) begin
        kh_mem_V_ce0 = grp_fp_conv_fu_507_kh_mem_V_2_ce0;
    end else begin
        kh_mem_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        kh_mem_V_we0 = 1'b1;
    end else begin
        kh_mem_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        wt_i_V_ce0 = 1'b1;
    end else begin
        wt_i_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        wt_mem_V_address0 = zext_ln180_2_fu_907_p1;
    end else if (((ap_predicate_op160_call_state8 == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        wt_mem_V_address0 = grp_bin_dense_fu_523_wt_mem_V_4_address0;
    end else if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln879_1_reg_1407 == 1'd1))) begin
        wt_mem_V_address0 = grp_fp_conv_fu_507_wt_mem_V_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        wt_mem_V_address0 = grp_bin_conv_fu_485_wt_mem_V_6_address0;
    end else begin
        wt_mem_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        wt_mem_V_ce0 = 1'b1;
    end else if (((ap_predicate_op160_call_state8 == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        wt_mem_V_ce0 = grp_bin_dense_fu_523_wt_mem_V_4_ce0;
    end else if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln879_1_reg_1407 == 1'd1))) begin
        wt_mem_V_ce0 = grp_fp_conv_fu_507_wt_mem_V_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        wt_mem_V_ce0 = grp_bin_conv_fu_485_wt_mem_V_6_ce0;
    end else begin
        wt_mem_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        wt_mem_V_we0 = 1'b1;
    end else begin
        wt_mem_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln749_fu_676_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln887_fu_862_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln887_1_fu_911_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state8 : begin
            if (((1'b0 == ap_block_state8_on_subcall_done) & (1'b1 == ap_CS_fsm_state8) & ((icmp_ln879_reg_1393 == 1'd0) | ((icmp_ln879_1_reg_1407 == 1'd1) | (icmp_ln887_2_fu_932_p2 == 1'd0))))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else if (((1'b0 == ap_block_state8_on_subcall_done) & (1'b1 == ap_CS_fsm_state8) & (icmp_ln887_2_fu_932_p2 == 1'd1) & (icmp_ln879_1_reg_1407 == 1'd0) & (icmp_ln879_reg_1393 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if (((grp_bin_conv_fu_485_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            if (((1'b1 == ap_CS_fsm_state12) & (icmp_ln838_fu_1179_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln180_1_fu_896_p2 = (zext_ln1372_fu_884_p1 + select_ln180_fu_888_p3);

assign add_ln180_2_fu_735_p2 = (zext_ln180_3_fu_731_p1 + zext_ln879_1_reg_1397);

assign add_ln180_3_fu_710_p2 = (zext_ln180_5_fu_706_p1 + zext_ln544_6_cast_fu_687_p4);

assign add_ln180_4_fu_1258_p2 = (zext_ln180_7_fu_1254_p1 + zext_ln544_12_cast_fu_1235_p4);

assign add_ln180_5_fu_1225_p2 = ($signed(grp_fu_1302_p3) + $signed(zext_ln180_9_fu_1221_p1));

assign add_ln180_fu_814_p2 = (add_ln749_fu_792_p2 + zext_ln180_fu_810_p1);

assign add_ln700_3_fu_1151_p2 = (16'd1 + kh_index_V);

assign add_ln700_4_fu_1163_p2 = (16'd1 + o_index_V);

assign add_ln700_fu_968_p2 = (kh_index_V + n_outputs_V);

assign add_ln749_fu_792_p2 = (trunc_ln749_2_reg_1444 + zext_ln749_fu_788_p1);

assign and_ln879_1_fu_1115_p2 = (xor_ln879_1_fu_1109_p2 & icmp_ln879_7_fu_1066_p2);

assign and_ln879_fu_1097_p2 = (xor_ln879_fu_1091_p2 & icmp_ln879_6_fu_1051_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state8_on_subcall_done = (((grp_bin_dense_fu_523_ap_done == 1'b0) & (ap_predicate_op160_call_state8 == 1'b1)) | ((grp_fp_conv_fu_507_ap_done == 1'b0) & (icmp_ln879_1_reg_1407 == 1'd1)));
end

always @ (*) begin
    ap_predicate_op160_call_state8 = ((icmp_ln879_1_reg_1407 == 1'd0) & (icmp_ln879_reg_1393 == 1'd0));
end

assign dmem_o_V_addr_gep_fu_363_p3 = zext_ln544_6_reg_1557;

assign dmem_o_V_d0 = dmem_V_q0;

assign grp_bin_conv_fu_485_ap_start = grp_bin_conv_fu_485_ap_start_reg;

assign grp_bin_dense_fu_523_ap_start = grp_bin_dense_fu_523_ap_start_reg;

assign grp_fp_conv_fu_507_ap_start = grp_fp_conv_fu_507_ap_start_reg;

assign grp_fu_1302_p0 = {{p_0713_2_reg_450[14:1]}};

assign grp_fu_1302_p1 = zext_ln838_reg_1525;

assign grp_fu_1302_p2 = grp_fu_1302_p20;

assign grp_fu_1302_p20 = p_0882_2_reg_462;

assign grp_fu_550_p2 = (o_index_V + n_outputs_V);

assign i_V_1_fu_917_p2 = (p_0604_0_reg_428 + 7'd1);

assign i_V_2_fu_681_p2 = (16'd1 + p_0232_0_reg_406);

assign i_V_3_fu_937_p2 = (p_0660_0_reg_439 + 10'd1);

assign i_V_4_fu_1184_p2 = (16'd1 + p_0703_0_reg_474);

assign i_V_fu_868_p2 = (13'd1 + p_0502_0_reg_417);

assign icmp_ln749_fu_676_p2 = ((p_0232_0_reg_406 == input_words_V) ? 1'b1 : 1'b0);

assign icmp_ln838_fu_1179_p2 = ((p_0703_0_reg_474 == output_words_V) ? 1'b1 : 1'b0);

assign icmp_ln841_fu_1012_p2 = ((width_mode_V != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln879_1_fu_662_p2 = ((layer_type_V_fu_567_p4 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln879_2_fu_831_p2 = ((img_off_V_fu_825_p2 == zext_ln879_reg_1402) ? 1'b1 : 1'b0);

assign icmp_ln879_3_fu_962_p2 = ((p_0660_0_reg_439 == 10'd0) ? 1'b1 : 1'b0);

assign icmp_ln879_4_fu_1275_p2 = ((img_off_V_1_fu_1269_p2 == zext_ln841_reg_1530) ? 1'b1 : 1'b0);

assign icmp_ln879_5_fu_1042_p2 = ((off_V_reg_1513 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln879_6_fu_1051_p2 = ((off_V_reg_1513 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln879_7_fu_1066_p2 = ((off_V_reg_1513 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln879_fu_640_p2 = ((layer_type_V_fu_567_p4 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln883_fu_979_p2 = ((norm_mode_V != 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln887_1_fu_911_p2 = ((p_0604_0_reg_428 == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln887_2_fu_932_p2 = ((zext_ln887_fu_928_p1 < n_outputs_V) ? 1'b1 : 1'b0);

assign icmp_ln887_fu_862_p2 = ((p_0502_0_reg_417 == 13'd4682) ? 1'b1 : 1'b0);

assign img_idx_V_1_fu_1280_p2 = (p_0713_2_reg_450 + 16'd1);

assign img_idx_V_fu_836_p2 = (p_0713_0_reg_382 + 16'd1);

assign img_off_V_1_fu_1269_p2 = (p_0882_2_reg_462 + 10'd1);

assign img_off_V_fu_825_p2 = (p_0882_0_reg_394 + 10'd1);

assign kh_i_V_address0 = zext_ln544_4_fu_923_p1;

assign layer_type_V_fu_567_p4 = {{layer_mode_V[2:1]}};

assign lshr_ln_fu_984_p4 = {{shl_ln746_reg_1383[4:2]}};

assign nc_V_fu_1143_p3 = ((or_ln879_1_fu_1129_p2[0:0] === 1'b1) ? select_ln879_fu_1121_p3 : select_ln879_1_fu_1135_p3);

assign off_V_fu_958_p1 = kh_index_V[1:0];

assign or_ln841_1_fu_1036_p2 = (xor_ln841_fu_1030_p2 | tmp_9_fu_1023_p3);

assign or_ln841_fu_1017_p2 = (icmp_ln883_fu_979_p2 | icmp_ln841_fu_1012_p2);

assign or_ln879_1_fu_1129_p2 = (and_ln879_fu_1097_p2 | and_ln879_1_fu_1115_p2);

assign or_ln879_fu_1103_p2 = (icmp_ln879_6_fu_1051_p2 | icmp_ln879_5_fu_1042_p2);

assign r_V_2_fu_608_p2 = (dmem_mode_V ^ 1'd1);

assign r_V_fu_759_p2 = ret_V_5_fu_755_p1 << zext_ln746_reg_1378;

assign ret_V_2_fu_672_p1 = p_0232_0_reg_406[9:0];

assign ret_V_3_fu_668_p1 = p_0232_0_reg_406[0:0];

assign ret_V_4_fu_1175_p1 = p_0703_0_reg_474[0:0];

assign ret_V_5_fu_755_p1 = ret_V_s_fu_745_p4;

assign ret_V_9_fu_943_p4 = {{kh_index_V[15:2]}};

assign ret_V_fu_858_p1 = p_0502_0_reg_417[0:0];

assign ret_V_s_fu_745_p4 = {{p_0713_0_reg_382[15:1]}};

assign select_ln180_fu_888_p3 = ((ret_V_fu_858_p1[0:0] === 1'b1) ? 13'd2341 : 13'd0);

assign select_ln760_1_fu_850_p3 = ((icmp_ln879_2_fu_831_p2[0:0] === 1'b1) ? 10'd0 : img_off_V_fu_825_p2);

assign select_ln760_fu_842_p3 = ((icmp_ln879_2_fu_831_p2[0:0] === 1'b1) ? img_idx_V_fu_836_p2 : p_0713_0_reg_382);

assign select_ln849_1_fu_1294_p3 = ((icmp_ln879_4_fu_1275_p2[0:0] === 1'b1) ? 10'd0 : img_off_V_1_fu_1269_p2);

assign select_ln849_fu_1286_p3 = ((icmp_ln879_4_fu_1275_p2[0:0] === 1'b1) ? img_idx_V_1_fu_1280_p2 : p_0713_2_reg_450);

assign select_ln879_1_fu_1135_p3 = ((icmp_ln879_5_fu_1042_p2[0:0] === 1'b1) ? tmp_V_fu_1047_p1 : tmp_V_3_fu_1081_p4);

assign select_ln879_fu_1121_p3 = ((and_ln879_1_fu_1115_p2[0:0] === 1'b1) ? tmp_V_2_fu_1071_p4 : tmp_V_1_fu_1056_p4);

assign shl_ln746_fu_630_p2 = 7'd1 << zext_ln746_1_fu_626_p1;

assign shl_ln_fu_614_p3 = {{width_mode_V}, {1'd0}};

assign tmp_1_fu_801_p4 = {{{dmem_mode_V}, {trunc_ln749_3_fu_797_p1}}, {10'd0}};

assign tmp_2_fu_874_p4 = {{p_0502_0_reg_417[12:1]}};

assign tmp_4_fu_697_p4 = {{{dmem_mode_V}, {ret_V_3_fu_668_p1}}, {10'd0}};

assign tmp_5_fu_1245_p4 = {{{r_V_2_reg_1369}, {ret_V_4_fu_1175_p1}}, {10'd0}};

assign tmp_6_fu_1212_p4 = {{{r_V_2_reg_1369}, {trunc_ln838_fu_1208_p1}}, {10'd0}};

assign tmp_7_fu_721_p4 = {{p_0232_0_reg_406[15:10]}};

assign tmp_8_fu_777_p3 = {{add_ln180_2_reg_1434}, {ret_V_2_reg_1411}};

assign tmp_9_fu_1023_p3 = layer_mode_V[32'd2];

assign tmp_V_1_fu_1056_p4 = {{kh_mem_V_q0[31:16]}};

assign tmp_V_2_fu_1071_p4 = {{kh_mem_V_q0[47:32]}};

assign tmp_V_3_fu_1081_p4 = {{kh_mem_V_q0[63:48]}};

assign tmp_V_fu_1047_p1 = kh_mem_V_q0[15:0];

assign tmp_fu_646_p3 = {{dmem_mode_V}, {1'd0}};

assign trunc_ln749_2_fu_764_p1 = r_V_fu_759_p2[13:0];

assign trunc_ln749_3_fu_797_p1 = p_0713_0_reg_382[0:0];

assign trunc_ln791_fu_581_p1 = kh_index_V[0:0];

assign trunc_ln792_fu_577_p1 = layer_mode_V[0:0];

assign trunc_ln838_fu_1208_p1 = p_0713_2_reg_450[0:0];

assign words_per_image_V_fu_636_p1 = shl_ln746_fu_630_p2[4:0];

assign words_per_out_V_fu_997_p3 = ((icmp_ln883_fu_979_p2[0:0] === 1'b1) ? words_per_image_V_reg_1388 : zext_ln1371_fu_993_p1);

assign wt_i_V_address0 = zext_ln544_1_fu_902_p1;

assign xor_ln841_fu_1030_p2 = (or_ln841_fu_1017_p2 ^ 1'd1);

assign xor_ln879_1_fu_1109_p2 = (or_ln879_fu_1103_p2 ^ 1'd1);

assign xor_ln879_fu_1091_p2 = (icmp_ln879_5_fu_1042_p2 ^ 1'd1);

assign zext_ln1371_fu_993_p1 = lshr_ln_fu_984_p4;

assign zext_ln1372_fu_884_p1 = tmp_2_fu_874_p4;

assign zext_ln180_10_fu_1230_p1 = add_ln180_5_fu_1225_p2;

assign zext_ln180_1_fu_820_p1 = add_ln180_fu_814_p2;

assign zext_ln180_2_fu_907_p1 = add_ln180_1_reg_1472;

assign zext_ln180_3_fu_731_p1 = tmp_7_fu_721_p4;

assign zext_ln180_4_fu_783_p1 = tmp_8_fu_777_p3;

assign zext_ln180_5_fu_706_p1 = tmp_4_fu_697_p4;

assign zext_ln180_6_fu_773_p1 = add_ln180_3_reg_1424;

assign zext_ln180_7_fu_1254_p1 = tmp_5_fu_1245_p4;

assign zext_ln180_8_fu_1264_p1 = add_ln180_4_fu_1258_p2;

assign zext_ln180_9_fu_1221_p1 = tmp_6_fu_1212_p4;

assign zext_ln180_fu_810_p1 = tmp_1_fu_801_p4;

assign zext_ln544_12_cast_fu_1235_p4 = {{p_0703_0_reg_474[14:1]}};

assign zext_ln544_1_fu_902_p1 = p_0502_0_reg_417;

assign zext_ln544_2_fu_740_p1 = p_0232_0_reg_406;

assign zext_ln544_3_fu_716_p1 = p_0232_0_reg_406;

assign zext_ln544_4_fu_923_p1 = p_0604_0_reg_428;

assign zext_ln544_5_fu_953_p1 = ret_V_9_fu_943_p4;

assign zext_ln544_6_cast_fu_687_p4 = {{p_0232_0_reg_406[14:1]}};

assign zext_ln544_6_fu_1190_p1 = p_0703_0_reg_474;

assign zext_ln544_fu_768_p1 = p_0232_0_reg_406;

assign zext_ln746_1_fu_626_p1 = shl_ln_fu_614_p3;

assign zext_ln746_fu_622_p1 = shl_ln_fu_614_p3;

assign zext_ln749_fu_788_p1 = p_0882_0_reg_394;

assign zext_ln791_fu_586_p1 = trunc_ln791_fu_581_p1;

assign zext_ln838_fu_1004_p1 = words_per_out_V_fu_997_p3;

assign zext_ln841_fu_1008_p1 = words_per_out_V_fu_997_p3;

assign zext_ln879_1_fu_654_p1 = tmp_fu_646_p3;

assign zext_ln879_fu_658_p1 = words_per_image_V_fu_636_p1;

assign zext_ln887_fu_928_p1 = p_0660_0_reg_439;

always @ (posedge ap_clk) begin
    zext_ln746_reg_1378[0] <= 1'b0;
    zext_ln746_reg_1378[15:3] <= 13'b0000000000000;
    zext_ln879_1_reg_1397[0] <= 1'b0;
    zext_ln879_1_reg_1397[6:2] <= 5'b00000;
    zext_ln879_reg_1402[9:5] <= 5'b00000;
    zext_ln544_4_reg_1490[63:7] <= 57'b000000000000000000000000000000000000000000000000000000000;
    zext_ln838_reg_1525[13:5] <= 9'b000000000;
    zext_ln841_reg_1530[9:5] <= 5'b00000;
    zext_ln544_6_reg_1557[63:16] <= 48'b000000000000000000000000000000000000000000000000;
end

endmodule //top
